### ISSUE TITLE
Attempt to load module sys

### ISSUE THREAD

**Issue by Koshmaar** [QQuick/Transcrypt#115]
Hi, I have a problem. I have installed Python 3.5 and latest Transcrypt (using the .zip file method).

I do run_transcrypt -b somescript.py  and get:

```
Error in program somescript.py, module sys, line 26:
        Attempt to load module: sys
        Can't find any of:
                C:/Dev/kpudlo_tools/Tools/Script/source/__javascript__/sys.mod.js
                C:/Dev/kpudlo_tools/Tools/Script/source/__javascript__/sys.mod.js
                C:/Dev/kpudlo_tools/Tools/Script/transcrypt/transcrypt/modules/__javascript__/sys.mod.js
                C:/Dev/kpudlo_tools/Tools/Script/transcrypt/transcrypt/modules/__javascript__/sys.mod.js
                C:\Dev\kpudlo_tools\Tools\Script\transcrypt\transcrypt/__javascript__/sys.mod.js
                C:\Dev\kpudlo_tools\Tools\Script\transcrypt\transcrypt/__javascript__/sys.mod.js
                C:\Python35\python35.zip/__javascript__/sys.mod.js
                C:\Python35\python35.zip/__javascript__/sys.mod.js
                C:\Python35\DLLs/__javascript__/sys.mod.js
                C:\Python35\DLLs/__javascript__/sys.mod.js
                C:\Python35\lib/__javascript__/sys.mod.js
                C:\Python35\lib/__javascript__/sys.mod.js
                C:\Python35/__javascript__/sys.mod.js
                C:\Python35/__javascript__/sys.mod.js
                C:\Python35\lib\site-packages/__javascript__/sys.mod.js
                C:\Python35\lib\site-packages/__javascript__/sys.mod.js
```

Python should have sys module by default, right? Is it a Python or Transcrypt configuration issue? Is there something addtional to do, ie. install some javascript module for python?

**Comment by JdeH** [comment]
Hi

It seems that your program _somescript.py_ imports the _sys_ module. But it isn't available under Transcrypt. Although a very limited number of CPython modules are available (math, itertools, random, time) and some may follow (re, ...), Transcrypt mostly relies on JavaScript libraries, since they are taylored to the internet/webbrowser environment, whereas existing Python libraries have many functions that only make sense on the desktop, and many others are programmed in C++, which could be compiled by emscripten, but would make downloads huge.

Main design goal with Transcrypt is that it should be fast and small enough to be a serious replacement for JavaScript and that it should have seamless access to any JS library.

Some more info on this you'll find at:

[http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/what_why.html#the-ecosystem-different-batteries](http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/what_why.html#the-ecosystem-different-batteries)

Kind regards
Jacques de Hooge

**Comment by Koshmaar** [comment]
The script is using such functionality:
  sys.version_info
  sys.argv[]
  sys.exit

and getopt

```
try:
    opts, args = getopt.getopt(sys.argv[1:], "v", ["verbose"])
except getopt.GetoptError as err:
    print (str(err))
    print_help()
    sys.exit(2)

```

Which IMHO could be "emulated" in browser. So ie. somebody would have to write sys module as javascript with certain functions that can be supported, right? So that's probably not going to happen soon (btw I don't have time for that now).

**Comment by daboross** [comment]
Yes, someone would have to write a sys module to support those functions. It wouldn't necessarily have to be written in JavaScript, but it would need to be written without references to the actual python sys module, so that it could be transpiled to JavaScript in Transcrypt.

Out of curiosity, what would you want the sys module to do in those cases? `sys.version_info` could probably be done easily, but it seems less clear what `sys.exit` and `sys.argv` should mean in the context of a browser, or in any other JavaScript environment.

**Comment by JdeH** [comment]
In itself the presence of (parts of) the standard libraries won't bloat Transcrypt, since they're included only when needed. Some of them, like re, could probably be thin encapsulations of JavaScript facilities. And indeed for a library like sys (let alone os) only part of it would make sense. But still those parts would be useful.

Since such libraries aren't tightly integrated with the core of Transcrypt, and can be implemented step by step by someone mastering JS and Python. An example of such a contribution is the 'time' library for windows, contributed by AXGKl. I invite anyone reading this to give it a try.

**Comment by JdeH** [comment]
Some important libraries like re, math, cmath, itertools and random have been added. I think sys is to much desktop-oriented to add, so I'll close this issue.
