### ISSUE TITLE
Invitation: showcases for the new Transcrypt website.

### ISSUE THREAD

**Issue by JdeH** [QQuick/Transcrypt#116]
Currently a shiny new website is being build for Transcrypt. It would be good to add some more showcases to it, so if you used Transcrypt for a site that can be linked to,  or otherwise are willing  to show something you made, you're very welcome to share it!

**Comment by icarito** [comment]
Although you closed this I still feel invited as soon as I have something to show! Thanks for your hard work!

**Comment by JdeH** [comment]
By closing it I didn't mean that it isn't important anymore. It is very important. Just don't want to nag people into fatigue.. So you're still very much invitated.

**Comment by JdeH** [comment]
I've reopened, since it is important for acceptance of Transcrypt.

**Comment by icarito** [comment]
Hi @JdeH as per your invitation and related to both #137 and #67, even #152 - I'm sharing with you https://github.com/somosazucar/python-web - I'd appreciate your comments!

**Comment by JdeH** [comment]
Hi Sebastian,

Thanks for your message!
I want to take a good look at this and then I will get back to you.
Will be a few days.

Kind regards
Jacques

**Comment by icarito** [comment]
Hi Jacques,
Please don't feel obligated to review or comment my code, just the fact that you are aware of my effort and approach, is a great motivation. I am a great fan of your work and have been eagearly reading your conversations with @AXGKl  - I too learned BASIC and I agree with some of your ideas - although I have experienced the pain of API breakage and working with unmantained software because I was heavily involved giving volunteer support for the OLPC programs here in Peru (they feature a Python based GTK desktop called Sugar).

Regrettably at this point Sugar is still at Python2.7 and is slowly fading into bitrot because of dissappearing dependencies and lack of update (not to mention users).

So this is why I look into Web as a new platform for the same ideas, and to the contrary to your opinion, I still can run old pages in new browser, whereas I have games in GTK2 + pygame + sugar which are a pain to get running in modern systems, which is a pity.

One goal I have is to try to minimize / make *compat.py / compat.pyj* simpler but would like to avoid to have to transform / preprocess the source for it.

I'll also try, when I can, to add Javascrypton to this template. I expect to use it very soon, so hopefully I'll update it.

**Comment by icarito** [comment]
Admittedly the live reload mechanism is simple, but I'm sure we can improve it!

**Comment by ZenifiedFromI2P** [comment]
Hmm, I have two questions.

1. Is the new website gonna be OSS? I'd love to help.

2. What kind of exact help do you need, I'm very much willing to help..

Transcrypt saves me hoardes of time, I use it in my webapp. :smile:

**Comment by Tset-Noitamotua** [comment]
@ZenifiedFromI2P would you mind to link your webapp? ;-)

**Comment by JdeH** [comment]
Hi, I am curious about the webapp too.

About the site: it currently isn't OSS since it's based on a proprietary web server.
What it lacks currently is main good, real life examples of the use of Transcrypt.

Unfortunately the non-trivial projects I know are all closed source. 
So if  anyone writes something publicly ascessible, we'd welcome a link!

Kind regards
Jacques

**Comment by RunasSudo** [comment]
I see you've recently closed this issue, but in case you're looking for more examples, you're more than welcome to use https://github.com/RunasSudo/Eos

It's a proof of concept web application for cryptographic voting. Transcrypt is used so a single codebase can be shared across the Python backend and Javascript frontend, to guarantee consistency of data representation and cryptographic operations.

Very much non-trivial, and most definitely open source!

**Comment by JdeH** [comment]
A valuable example, especially because of the code sharing between CPython and Transcrypt.
I've added a link in the Gallery section of transcrypt.org.
Thanks!
