### ISSUE TITLE
cls.__new__ is not a function at cls 

### ISSUE THREAD

**Issue by Bottersnike** [QQuick/Transcrypt#133]
After compiling my code, I get the error `cls.__new__ is not a function at cls` when trying to run my code. The code is at http://pastebin.com/mvQcb4GT
**EDIT:**
After some dev console testing, it would appear that creating a class (i.e. `var c = className("data", "moreData")`) is throwing the error.

**Comment by JdeH** [comment]
Thanks for the feedback!

I suspect the problem is that your classes inherit from str, which is not (yet) possible in Transcrypt, since str is mapped to a pure JavaScript class (or rather prototype) and doesn't support Trancrypt's class based inheritance mechanism.
I'll take a look as soon as I am finished with the current work on TS and get back on this as soon as the cause is known.
If I am right (which I am not sure of) it would be to have your  classes contain a string rather than inherit from it.
Of course it would be better if Transcrypt just supported your use case.

Kind regards
Jacques de Hooge

**Comment by AXGKl** [comment]
`type.__new__` is also required for metaclass support, they also are inheriting from `type`

**Comment by JdeH** [comment]
@AXGKI Currently I am working on issue #113, orginally brought in by @daboross. It should make the JS6 code much more natural, but it's not easy to really seamlessly mix JS and Py iterators, generators and iterables. Iis kind of hard to do properly, with efficient code generation, but I think it will work out.

The coming weeks some other projects will also require my attention.

After that I'll try to solve the bugs in the queue. After that some low hanging fruit for enhancements. And after that a serious look into metaclasses.

**Comment by Bottersnike** [comment]
Okay. I've made some modifications to my code to avoid inheritance from str and I'm just running it through transcrypt now.

**Comment by JdeH** [comment]
@Bottersnike 
OK, curious about the results.

**Comment by Bottersnike** [comment]
Well... :P my string implementation is throwing up some errors despite working perfectly when in python (`Uncaught TypeError: Cannot use 'in' operator to search for '_str__' in NaN`). I believe the problem is hasattr but I'm unsure.

**Comment by JdeH** [comment]
Metaclasses and __new__ are in now, but maybe that doesn't solve all issues you mentioned.
Still problems?

**Comment by JdeH** [comment]
No news is good news? If needed, feel free to reopen.

**Comment by Bottersnike** [comment]
Sorry.. :P. I haven't been reading the thread. I'll see if I can find my code and give it a quick check

**Comment by JdeH** [comment]
Thx
