### ISSUE TITLE
items in dict

### ISSUE THREAD

**Issue by neriusmika** [QQuick/Transcrypt#148]
```
d = {
    'items': [1, 2, 3],
    'items2': [4, 5, 6],
}

for k, v in d.items():
    console.log(k + ': ' + v)
```
such code now returns only `items2: 4,5,6` because key 'items' is conflicting with method items, but in CPython both keys are returned. Is there any solution to this problem?

**Comment by JdeH** [comment]
Cannot be completely solved without an alternative compilation pragma to use Map's rather than JS objects for a dict. But this makes interop with JS libs much more complicated and has many other undesirable consequences, so it will indeed at best be an option. Will postpone it for now, as the effort is large compared to the benefits.

Will make clashes less likely by using py_items alias rather than items. The py_ prefix has a special meaning. Slightly less readable, but prevents many problems. A prefix like __@@py@@__ would even cause less clashes but is unacceptable from a readability point of view...

**Comment by neriusmika** [comment]
It's ok for me, just accidentally used such name. I can change it. But it would be good to mention somewhere in documentation, that some names are reserved and cannot be used.

**Comment by JdeH** [comment]
Indeed.
So I should make a py_items alias for the function, and make clear in the docs that some keys starting with py_ cannot be used.

**Comment by AXGKl** [comment]
there are a few other entries on the forbidden list as well, I was recently bitten by `.type` :

```javascript

	(function () {
		var A = __class__ ('A', [object], {
			type: 'an A class'
		});
		console.log (A.py_metatype);
		__pragma__ ('<all>')
			__all__.A = A;
		__pragma__ ('</all>')
	}) ();
	return __all__;
}
r ();
```
from 

```python
~ $ cat r.py 
class A:
    type = 'an A class'

console.log(A.type)
```

I know its not a clever choice to use `.type` but definitely worth an entry on the reserved names and attrs list ;-)

**Comment by JdeH** [comment]
Indeed, I'll add it.

**Comment by JdeH** [comment]
Done
