### ISSUE TITLE
the 'in' operator

### ISSUE THREAD

**Issue by GULPF** [QQuick/Transcrypt#150]
The 'in' operator for dictionaries compiles into really slow code. Here's how the relevant function looks:
```javascript
var __in__ = function (element, container) {
	if (py_typeof (container) == dict) {
		return container.py_keys () .indexOf (element) > -1;
	}
	// ...
}
```

`py_keys` iterates all keys in the container and filters some out, which means it has time complexity O(n). Additionally, `indexOf` also has to iterate the elements until it finds the correct one. Instead, `container.hasOwnProperty`([mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwnProperty)), with time complexity O(1), should be used.

This will also improve behavior. Currently `1 in {1: 2}` will evaluate to false (because JS-object can only have strings as keys, so it will turn into `['1'].indexOf(1)`), but with hasOwnProperty it will work as expected (because it casts the key to check for to a string).

**Comment by JdeH** [comment]
Quite right.
Fixed and autotested, works fine.
I assume it will also pass the shipment test, so it'll be in the next commit.

One nitpicky question fo my own education: This is a significant performance improvement. Still I wonder how hasOwnProperty can be O (1). Is it purely hash based? And do you assume the number of keys c.q. attribs is small enough not to cause any collisions? O (1) for ANY nr of keys is impossible I would expect, unless using a quantum computer.

**Comment by GULPF** [comment]
Like you say, because of hash collisions it won't be exactly O(1), but since there are generally few collisions per key (assuming the hash map is resized properly as it grows), it doesn't result in much extra work. See https://en.wikipedia.org/wiki/Hash_table#Collision_resolution

**Comment by GULPF** [comment]
I now noticed that in the else case of \_\_in\_\_, JavaScripts `in` is used if there is no indexOf:
```javascript
return container.indexOf ? container.indexOf (element) > -1 : element in container;
```
This will also give some strange behavior. It means that

1. Transcrypts `in` will work with non-iterable Python classes (which is an exception in python/cpython)
2. Transcrypts `in` will give results inconsistent with Pythons `in` for non-dict objects without `indexOf` (e.g objects sent from JavaScript code). Like `'toString' in x` (almost) always being true (because JavaScripts `in` will also check for properties on the prototype, not only on the object itself).

§1 might be acceptable since it doesn't affect working python code. §2 can be solved by switching to `hasOwnProperty` instead of `in`.

**Comment by JdeH** [comment]
There has been a lot of discussion about 'in' as part of issue #96. Python itself doesn't generally support it, unless the object has an overloaded __contains__ operator, which is not (yet) supported in Transcrypt. But from the opinions there I gathered that for JS objects, Transcrypts 'in' should behave like JS 'in', because that is what people expect when converting JS code containing 'in' to Transcrypt code.

So they expect to be the properties of the prototype to be there. And indeed, 'toString' would nearly always be there, as it would in 'JS'.

Since the use of 'in' on JS objects was introduced at proposal of these contributers, @AXGKl  and @daboross, what's your opinion on this?

**Comment by GULPF** [comment]
After skimming through the arguments in #96, it seems reasonable. I still think it would be preferable to use `hasOwnProperty` instead of `in` though, since it's closer to the python behavior. It's just inconsistent to have Transcrypts `in` check the prototype in some cases, but not for objects with `.indexOf` or dictionaries.

An alternative would be to use JS `in` for all cases, which would also be consistent.

**Comment by AXGKl** [comment]
hi, thanks for checking back with us. 
I'm happy that @GULPF is pragmatic about §1 (In the beginning I was religious about absolute CPython compilance but after a while the attitude changes a bit as explained in that longish  #96).

Regarding `hasOwnProperty`: I did not know it but it seems its exactly what people would expect (plus way faster). => perfect. To be precise not perfect because of [this](https://felipec.wordpress.com/2013/10/07/the-linux-way/) but I think in this phase of Transcrypt we can still afford to do it, innovators are more tolerant than late majority. 

=> @GULPF : I'm greatful that you found it, in this phase !!

**Comment by JdeH** [comment]
@AXGKI @daboross: I then assume that you both had similar use cases. It is indeed important to change this now, before to much user code depends upon it. @GULPF: If it passes the shipment test it will be in the next commit and sub-release.
