### ISSUE TITLE
string interpolation

### ISSUE THREAD

**Issue by punkdit** [QQuick/Transcrypt#155]
Code such as
```
"keydown: %s" % e.key
```

seems to produce the string "NaN".

Is string interpolation trying to do modulo arithmetic?

**Comment by JdeH** [comment]
% for string formatting is not supported.
<string>.format (...) is the way to do it with Transcrypt.
This is part of the "lean and mean" strategy.
'format' is flexible enough to cover all cases,
although the 'string formatting mini language' isn't supported.

Seems Python 3.6 has some innovations on the string formatting front.
Haven't looked into them yet but probably they will be partially supported.

**Comment by punkdit** [comment]
Is there somewhere where these limitations are documented? Or is it left to the hapless programmer to find out which part of the language you decided to implement?

**Comment by JdeH** [comment]
Not yet. Transcrypt started out as a "Small Sane Subset" transpiler (I believe it still modestly reports that when you run it). The autotest suite served as an overview of what it could do:

http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/supported_constructs.html

and what wasn't there, well, you couldn't. In the beginning I held the conviction that it would remain a small subset, to be able to produce lean code. But much more turned out to be possible. To my initial amazement it turned out to be possible to implement most of the language, still compiling to lean JS code.

So the strategy of: Just read the examples doesn't work anymore. What's needed is a 'Limitations' chapter, telling what it can't, rather than can, do. At this moment many small features still get added, often on user request. I find my role to be a door guard, indeed deciding what gets in and not.

One of the dangers is to go overboard on adding everything, making it 'big' after all. So sometimes a painful choice (like string formatting) is made. Unfortunately the dead code removal of Google Closure isn't powerful enough yet to allow a lot of "sleeping" features without bloat. When using the highest compression mode, it makes semantic mistakes.

So indeed, since Transcrypt approaches Python so closely, it's efficient to have a limitations, rather than a features chapter in the docs, and there will be. Since features can be exhaustively tested in theory, but limitations can't, it will be called something like: main limitations. It should offer the programmer an overview at a glance, without too much bumping in, like you did.

**Comment by punkdit** [comment]
Hi Jaques, thankyou for your thoughtful comments. I'm not sure I understand your perspective entirely, but I just wanted to say that I am enjoying using Transcrypt very much. I am taking a philosophy of "tread lightly" and so hopefully don't get into too much trouble.

Many years ago I was involved in the pypy project (tangentially) and in particular got quite excited about their compiled version of python, RPython. I wrote a large-ish commercial system using that language, but at some point the intoxication wore off and I was left with a decent hangover. 

Anyway, I will continue to play with Transcrypting, consensual adult style. And maybe I can contribute something aswell.

**Comment by JdeH** [comment]
Glad you're having fun with it, I think that's important, at least for me it is.
And of course you're welcome to contribute.
