### ISSUE TITLE
Add support for float('inf') and float('-inf')

### ISSUE THREAD

**Issue by GULPF** [QQuick/Transcrypt#169]
Would be a nice addition since `Infinity` gets transpiled into `py_Infinity`

**Comment by JdeH** [comment]
Infinity is translated to py_Infinity so that this identifier can be used without special meaning, e..g. as the name of a class.

Properly translating float ('inf') and float ('inf') would require some special purpose code in the compiler, since depending on the context (a call to float), 'inf' would have a special meaning. My first impression is that this should be doable.

From first sight (didn't think about this enough)` float ('inf') `should be translated to` Infinity` and `float ('-inf')` should be translated to` -Infinity`, right?

**Comment by JdeH** [comment]
Done, added to autotest, committed, uploaded to PyPi: v3.5.238
