### ISSUE TITLE
Compile from Json.stringyfy....

### ISSUE THREAD

**Issue by artyprog** [QQuick/Transcrypt#170]
Hello Jacques,

What code did you use to compile Python code from ace editor ?
I have setup a websocket server, I can send the code from ace editor.
I am searching the best way to compile the code 

Eventualy could  I use your compile servcice ?

Regards

Salvatore

**Comment by JdeH** [comment]
Hi Salvatore,

Do yo mean someone editing code in the browser, uploading it for compilation.  downloading the result and running it?

As you may have noted the turtle demo is set up like that:

http://www.transcrypt.org/live/turtle_site/turtle_site.html

Here's the relevant part of the server code:

```
class CompilePage (Page):
	def get (self):
		super () .get ()
		
		userDirName = self.app.siteDirName + '/user'
		
		if len (self.json) < maxChars:
			with open ('{}/{}'.format (userDirName, 'turtle_code.py'), 'w') as sourceFile:
				sourceFile.write (json.loads (self.json))
				
			origDir = os.getcwd ()
			os.chdir (userDirName)
			os.system ('/home/sterlicht/install/python3.5/bin/transcrypt -b -n turtle_code.py > out.txt')
			os.chdir (origDir)
			
			with open ('{}/__javascript__/{}'.format (userDirName, 'turtle_code.mod.js')) as targetFile:
				self.content = [json.dumps (targetFile.read ())]
```

And here's the relevant part of the client code:

```
# For use by eval'ed turtle applet
import turtle
import random
import math

def run ():
	def success (result):
		turtle.reset ()
		eval (result)
	
	def fail (a, b, c):
		print ('Run error:', a, b, c)

	# N.B. The request has to be explicitly encoded, but the response is already implicitly decoded
	jq.ajax ({
		'url':'http://www.transcrypt.org/compile',
		'type': 'POST',
		'data': JSON.stringify (editor.getValue ()),
		'dataType': 'json',
		'contentType': 'application/json',
		'success': success,
		'fail': fail
	})
```

As you can see the client code is written  in Transcrypt (of course). Since the compiled (so JavaScript) code that came in via JSON is eval'ed, it runs in the context of the client's compiled (so also JavaScript) code. Since that imports turtle, random and math, these modules are also available to the eval'ed code that the client uploaded. Note that the eval is in fact a JavaScript, rather than a Python eval, run JavaScript generated from the user's program module in the context of JavaScript compiled from the client itself.

So only the module made by the user is uploaded, and only the JavaScript code of that module is downloaded again.

Take care, you of course need Python 3.5 on your server to make this work. 3.4 won't cut it. My provider didn't have that, so I installed it locally in my home dir, as you can see in CompilePage.

The provider that allows you complete freedom to do tricks like this is Alwaysdata (www.alwaysdata.com) in France. I am very satisfied with them. They also have free accounts, but of course with limited memory.

Warning: getting this to work is easier said then done. It took me quit a while to get some trivial bugs out.

Kind regards
Jacques

**Comment by artyprog** [comment]
Thank you very much Jacques
The server code you posted is exactly what I needed.

For running the process on the server, I intend to use websocket (with http://websocketd.com/),
like that I don't need have  to manageand  with http server.

Concerning the provider I use OVH for the backend and blogspot on the frontend.

I am very glad the way Transcrypt is evolving :-)

Thanks for your wise advices
I will of course get in touch as soon the site is up

Regards

Salvatore
