### ISSUE TITLE
CI Run Script Success when Tests Fail

### ISSUE THREAD

**Issue by RCL-Carl** [QQuick/Transcrypt#173]
Hi, 

I'm trying to get an understanding of this code base and I've run into an issue with the CI run script / test server. The CI script in `transcrypt\development\continous_integration\run` seems looks for an error message from the `test_server.py` script. Unfortunately, no error message gets generated when tests fail. Errors do get generated on timeout - but not when a unit test fails.

On line 214 in `test_server.py`, the script does a comparison to look for errors in the output from the HTML unit tests. Specifically: 

```
if "ERROR" in res:
    return stop( ... )
print G('SUCCESS'), test
```

The result in `res` returned by the HTML does not contain "ERROR" if a single unit test fails. This is the content that is returned on failure:

```
u'<div style="red"><b>Test failed</b></div>'
```

The timeout command does report "ERROR" in the result so that does work 

I'm pretty sure the issue is because of test_server.py line 153 - 

```
        if not ctx.get('stop'):
            # we are alraedy in d:
            js += ('\nlocation.href="/result?test=%s&res=" + '
                'document.getElementById("message").innerHTML;' % os.getcwd())
```

This is pulling res from the element `#message` which doesn't get set to "ERROR" when the test fails. It gets set to "Test failed".

**Comment by RCL-Carl** [comment]
You can see an example here: 

https://travis-ci.org/RCL-Carl/Transcrypt/builds/176208669

Goto line 557-558. The script says success and CI passes but you can clearly see on line 558 that the test has failed.

**Comment by GULPF** [comment]
Hi, I noticed you are working on a implementation of re for transcrypt. [I recently started working on that as well](https://github.com/GULPF/rescrypt) :) Instead of duplicating effort, it would be preferable if we contributed to the same code base. 

After skimming through your code it seems like you've implemented basically the entire API (which I haven't), but without any translation of re regexes to js regexes (which I have, this enables support for named groups, conditionals and lots of other stuff).

**Comment by RCL-Carl** [comment]
Ah - I see you posted in the issue on the regex library. You scooped me :)

I'm happy to collaborate - but perhaps we should move this discussion to that thread because I don't want to confuse the issue here. I'll post a message to introduce the idea and discuss how we can best integrate.

**Comment by JdeH** [comment]
@AXGKl 
I've again taken the liberty to assign you to this issue, since it concerns CI.

**Comment by AXGKl** [comment]
@RCL-Carl : checked it and you are 100% right: The testoutput of the autotest.html was indeed not containing "ERROR", leading to false negatives in the testsuite(!)

Many thanks for reporting this!!

@JdeH : here is a PR fixing it: https://github.com/QQuick/Transcrypt/pull/175

**Comment by AXGKl** [comment]
@JdeH : One thing: The set1 still continues to fail due to that rounding problem on my local machine. 

Thats bad because with just transcrypt in set1 developers will see the tests all the time failing, with the same environment than I have.

Not possible to round the last digit of that float off ?

<img width="1375" alt="screen shot 2016-11-16 at 13 08 49" src="https://cloud.githubusercontent.com/assets/9989548/20348423/b08a44fa-ac05-11e6-8a49-482c67a31e00.png">

**Comment by RCL-Carl** [comment]
Ok - in ubuntu 16.04, the build is broken in firefox 49. In chrome 53 the build runs and works fine.

**Comment by JdeH** [comment]
@AXGKI: I remember that rounding off didn't solve it, since in edge cases that happens differently. This is a nasty little problem. Maybe for now just kick module_math out of the test, until I've taken a good look at this. Is that OK with you?

**Comment by AXGKl** [comment]
sure ok with me, had a similar one with time due to the time difference of python run and javascript run time and yes I guess the test would still break if you run it exactly it certain times in the year ...

Btw: This one would fix it for me locally than the tests are running but I guess no way to do it rite?

```
diff --git a/transcrypt/development/automated_tests/transcrypt/module_math/__init__.py b/transcrypt/development/automated_tests/transcrypt/module_math/__init__.py
index fec3701..fa1123d 100644
--- a/transcrypt/development/automated_tests/transcrypt/module_math/__init__.py
+++ b/transcrypt/development/automated_tests/transcrypt/module_math/__init__.py
@@ -1,44 +1,53 @@
 from math import *
 
+def _check(nr, autoTester):^M
+       # we just compare the first 15 digits of floats due to precision deviations^M
+       # in browser and CPython:^M
+       if isinstance(nr, float):^M
+               nr = str(nr)[:15]^M
+       autoTester.check(nr)^M
+^M
+^M
 def run (autoTester):
-       autoTester.check (pi)
-       autoTester.check (e)
+       check = lambda nr: _check(nr, autoTester)^M
+       check (pi)^M
+       check (e)^M
```

**Comment by AXGKl** [comment]
@JdeH : this one can be closed, the stupid test assertion bug which @RCL-Carl reported is fixed.

**Comment by JdeH** [comment]
Fine!

**Comment by JdeH** [comment]
I think 'isinstance' is good enough now to attempt including this in the autotester itself. Will try as soon as I finished some other fixes here (console I/O not working properly). Since I cannot reproduce the roundoff problem locally, this action may again break it. If so, I trust you let me know... ;)

**Comment by AXGKl** [comment]
> you let me know... ;)
 I will ;-)


If you put into the autotester itself then you want to refine `nr = str(nr)[:15]` into sth which only cuts the digits by length after the dot.  In my tests here the tests worked up to 15 total length so I think 13 should be the cut off length for everything after the dot.

**Comment by JdeH** [comment]
(Also have put this in a comment on one of your commits, but just to be sure...)

@AXGKl : I invite you to take up ownership (as described in #193 / T-RFC1) of the continuous integration facilities, a.o. the contents of ../development/continuous_integration. What this means that all modifications on that module happen in consultancy and with approval of you. What it doesn't mean is that you have to code all or any of it yourself.
