### ISSUE TITLE
Bug with backslash in autotester

### ISSUE THREAD

**Issue by GULPF** [QQuick/Transcrypt#182]
This is really bizarre. The first call to `autoTester.check(str)` with a string containing a backslash will always fail, but any call after the first will work correctly. So in this code:

```
autoTester.check('\\')
autoTester.check('\\')
autoTester.check('\\')
```

The first test will fail, but the other two will succeed.

**Comment by JdeH** [comment]
Maybe not as bizarre as it may seem. The autotester is much like a bumblebee: It can't fly, but since it doesn't know that, it routinely flies. Seriously: This may or may no be easy to solve. I'll take a look. Meanwhile think of it as a limitation...

**Comment by RCL-Carl** [comment]
I've run into this issue with the re stuff as well - There seems to be a difference in how javascript and python interpret strings with escape sequences. 

For example - octal escape sequences: 
in python "\\141" -> "\\141"
in js "\\141" -> "\141"

Might have to do with the way that the results from the python run are stored in HTML in the autotester.py script

**Comment by RCL-Carl** [comment]
Ok - so this is two separate issues. The first issue is that the test was not reporting the same results for each occurence of the string. This has been fixed with the transition to the table-based autotester results. 

The second issue is an issue with the way that the strings in javascript are represented compared with the python. In javascript, the string representation is shown after escaping. In python, all characters except backslash are shown escaped. The backslash character seems to have special status in raw and normal strings in python. I'm not sure there is an easy way to fix this in transcrypt. We can't really just change the `str()` function because then if you want to copy a string, the resulting string and the original will actually be different strings in javascript. Python stores `\\` as one character and shows it as two. Javascript stores `\\` as one character and then shows it as one character `\`. I think this problem will exist anytime `\\` is used in a string.

**Comment by JdeH** [comment]
I can live with this and wouldn't know a lean way to solve it.
Feel free to reopen if you know a solution for the backslash limitation.
