### ISSUE TITLE
Attempt to load module index/hello

### ISSUE THREAD

**Issue by jneuendorf** [QQuick/Transcrypt#186]
I just recently installed transcrypt on **macOS Sierra** using **python3.5** and similarly to #115 I get this error when trying to build (with `transcrypt -b`) the demo `hello.py` (the one with the solar system - source code [here](https://github.com/QQuick/Transcrypt/blob/master/transcrypt/demos/hello/hello.py)

```
Error in program /usr/local/lib/python3.5/site-packages/transcrypt/demos/hello/hello.py, module hello:
    Attempt to load module: hello
    Can't find any of:
    ...
    # Looking for '__javascript__/hello.mod.js' at different locations
```

When I try to just run it (with `transcrypt -r`) I get another error:

```
Error: cannot run /usr/local/lib/python3.5/site-packages/transcrypt/demos/hello/hello.py using CPython: name 'chain' is not defined

Aborted
```

When I copy the source code from the example into a new file at another location I get yet another error using `transcrypt -b`:

```
Error in program what_should_i_eat/static/what_should_i_eat/js/index.py, module index: 
    Attempt to load module: index
    Can't find any of:
    ...
    # Looking for '__javascript__/index.mod.js' at different locations
```

Using `transscrypt -r` with the newly created copy of `hello.py` outputs the same error as above (`'chain' is not defined`).

**So my questions are:**
- Why does the demo not work? Why is transcrypt looking for a module file when there is no import other than `itertools` (which is built-in)?
- How can the same source code produce different errors (when building)?

I would love to get this to work - pretty excited about using python for the browser. :)
Thanks is advance.

**Comment by RCL-Carl** [comment]
I'm on Mac OS X 10.11.6 so I can't test macos Sierra, but I don't think it should matter. Are you building from the `transcrypt/demo/hello` directory ? I can get the error message you do if I build form another directory. For example:

```
$> cd transcrypt
$> transcrypt demo/hello/hello.py 
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.2
Copyright (C) Geatec Engineering. License: Apache 2.0


Error in program hello/hello.py, module hello: 
	Attempt to load module: hello
	Can't find any of:
	/Users/.../transcrypt/Transcryptmaster/transcrypt/demos/hello/__javascript__/__init__.mod.js
        <More Madness> 
```

But if I run from the hello directory it works: 

```
$> cd transcrypt/demo/hello
$> transcrypt hello.py
(tspy) grumpy-2:hello callendorph$ transcrypt hello.py
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.2
Copyright (C) Geatec Engineering. License: Apache 2.0

Saving result in: /Users/.../transcrypt/Transcrypt-master/transcrypt/demos/hello/__javascript__/hello.js
Saving minified result in: /Users/.../transcrypt/Transcrypt-master/transcrypt/demos/hello/__javascript__/hello.min.js

Ready
```

I would definitely agree that this is not optimal but I'm not familiar enough yet to know what the complications are. 

> I just recently installed transcrypt on macOS Sierra using python3.5 and similarly to #115 I get this error when trying to build

Issue #115 is a little different actually. That issue is trying to build a script that uses the `sys` module. Currently, this project doesn't have a `sys` module yet. It can't possibly build. The hello script should definitely build.

**Comment by jneuendorf** [comment]
Thanks for your fast reply. Your description also works for me, so thanks! :)
So does this principle always work? I mean do I always have to `cd` into the directory that (directly) contains the file I want to compile? That would make it more difficult to compile a whole bunch of files in different directories...

Or is the reason it worked that you `cd`'ed into the package directory?

**Comment by RCL-Carl** [comment]
Well - I know that the unit tests compile a bunch of sub-modules so I there is definitely a structured way to handle code in different files and directories. I'm pretty sure that the compiler traces through the imports and compiles as it goes even if they are separate directories. I think the compiled javascript for each module ends up in created subdirectory __javascript__ in those separate directories.

> Or is the reason it worked that you cd'ed into the package directory?

No I think it is because you were in the same directory as the "hello.py" file. The compiler compiles the hello.py file into a JS module in __javascript__/hello.mod.js. Then when it makes the top-level file that includes the transcrypt framework, it tries to include the hello.mod.js file from there. But because you aren't in the same directory - it can't find the module it just created. 

I may have missed some details - @JdeH anything you want to add ?

**Comment by jneuendorf** [comment]
Alright. Then I'm gonna play around with it a little and see how far I get.

**Comment by JdeH** [comment]
Currently Transcrypt must be run from the directory that the main program is in. 
Would be better if it could be run from anywhere.

**Comment by JdeH** [comment]
For now labeled as postponed (see issue #258 for what this means)
