### ISSUE TITLE
Transcrypt tries to write to its installation folder

### ISSUE THREAD

**Issue by kozec** [QQuick/Transcrypt#189]
Apparently to write source maps there.

```
transcrypt -m -n -e 5 index.py 
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.1
Copyright (C) Geatec Engineering. License: Apache 2.0


[Errno 13] Permission denied: '/usr/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/__javascript__/extra'Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/transcrypt/__main__.py", line 117, in main
    compiler.Program (compilerPath, __symbols__)
  File "/usr/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 123, in __init__
    Module (self, ModuleMetadata (self, self.baseModuleName))
  File "/usr/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 282, in __init__
    self.generateJavascriptAndMap ()
  File "/usr/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 405, in generateJavascriptAndMap
    self.modMap.save ()
  File "/usr/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/sourcemaps.py", line 286, in save
    with utils.create (self.mapPath) as mapFile:
  File "/usr/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/utils.py", line 87, in create
    os.makedirs (os.path.dirname (path), exist_ok = True)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/__javascript__/extra'
```

This basically prevents any kind of use.

**Comment by kozec** [comment]
I was able to workaround issue using [this very wrong patch](http://pastebin.com/FUjtfa3q).

You would probably want at least to use better way to decide when location is not writable.

**Comment by JdeH** [comment]
Since Transcrypt keeps .py files, generated .js files, generated sourcemaps and other optionally generated files (like a parse tree) together, resulting in one 'module directory tree', it indeed has to be installed in a directory where you have write privilege.

The reason that it's done like this, is that there are also JavaScript-only modules which are part of the installation, hence should be stored in the installation directory. To further complicate matters, developers can generate JavaScript modules from Python modules and distribute the former as JavaScript-only modules. This would mean that the right place to store a JavaScript module varies depending on whether or not it is a JavaScript-only module.

This would mean duplicating part of the module tree in some cases, and not in others, which would add a lot of complexity and make the whole thing harder to understand. The Transcrypt import mechanism is much more straightforward than the CPython mechanism, which is very complicated indeed (and getting ever more so).

Prebuilding everything in the distribution prior to installation would make the distribution needlessly large and, without special measures, cause a lot of spurious diff's in GitHub. So the best way to get out of these dilemma's is to build everything as part of the installation procedure itself. The only downside to that is that installation procedures that build things tend to be vulnerable, especially if it has to work on may Windowses, Linuxes and OsXes (Don't know if you're familiar with the problems e.g. installing Numpy on some systems). Nevertheless it is something to consider. If the build would fail, local installation with write privilege would still be possible as a fallback.

So: As it stands now, you need write priv to your install dir, but the problem you indicate is real enough and has our attention.

**Comment by JdeH** [comment]
Thanks for the patch, that will solve the problem temporarily on most linuxes. I'll refer to it for now if other bump into the same problem.

**Comment by kozec** [comment]
I don't think your way of installation would work anywhere outside of probably Windows 95 :)

Even Python on Windows doesn't normally have write access to installation directory.

**Comment by JdeH** [comment]
Haven't had any problems on my Win8 and Unbuntu systems. But I'm superuser on all those. It's acknowledged this is a 'must have'.

I've attached a 'help wanted' label to this one.
**To be very specific, the requirements for a good solution are:

- No duplication of the module directory tree, .py, .js, .map, .tree etc. files stay together as they are now.
- Building everything as part of the installation.
- Ignoring the -b flag in case of read-only target files.
- As simple as possible, no big, intrusive impact on the compiler.**

That's hard. And that's why it's got postponed. But if anyone sees the light, please consult with me first to prevent loss of effort!

Kind regards
Jacques

**Comment by Enerccio** [comment]
Please dont tell me you run ubuntu as root all the time...

**Comment by JdeH** [comment]
Have been running everything as root for 30 years and never crashed an OS.

**Comment by JdeH** [comment]
I've looked into this a  little bit further.
If the JS files that result from compilation are stored in a user directory than they aren't centrally available anymore.
I think the best solution is to use virtualenv for each project, where the project participants all have write privilege. 
In this way .js files resulting from compilation of libraries aren't compiled over and over again.
I am using virtualenv myself this way on linux. To actually I don't use my admin privilege, I can use Transcrypt just being logged in as a user (and project team member).

**Comment by kozec** [comment]
> I think the best solution is to use virtualenv for each project, where the project participants all have write privilege. 

Virtualenv magic affects only PYTHONPATH & co, it will _not_ allow Transcrypt to write `/usr/bin` subdirectory. It will not redirect writing operation somewhere else either.

```
(venv) [tom@silver test]$ transcrypt -m -n -e 5 test.py 
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.1
Copyright (C) Geatec Engineering. License: Apache 2.0


[Errno 13] Permission denied: '/usr/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/__javascript__/extra'Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/transcrypt/__main__.py", line 117, in main
    compiler.Program (compilerPath, __symbols__)
  File "/usr/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 123, in __init__
    Module (self, ModuleMetadata (self, self.baseModuleName))
  File "/usr/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 282, in __init__
    self.generateJavascriptAndMap ()
  File "/usr/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 405, in generateJavascriptAndMap
    self.modMap.save ()
  File "/usr/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/sourcemaps.py", line 286, in save
    with utils.create (self.mapPath) as mapFile:
  File "/usr/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/utils.py", line 87, in create
    os.makedirs (os.path.dirname (path), exist_ok = True)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/__javascript__/extra'


Aborted
(venv) [tom@silver test]$ 
```

> If the JS files that result from compilation are stored in a user directory than they aren't centrally available anymore.

I don't believe user needs those centrally available. In fact, allowing random user to change js files included by compiler and thus inject anything into code of another user sounds pretty catastrophic from security viewpoint.

By the way, I'm surprised you haven't this problem before. Am I first one ever trying to run Transcrypt on Linux? :)

**Comment by JdeH** [comment]
Hi,

Personally I use Windows for development and Ubuntu for additional testing. Most developers are on Linux a.f.i.k.. I have a Miniconda / Python3.5 / Numpy installation in my home dir. I remember using virtualenv to install packages like Transcrypt in a project-specific directory where only project team members had access. So security wasn't an issue. But maybe it was different from what I remember.

Could any regular Linux user shed a bit more light on this subject?

**Comment by AXGKl** [comment]
> Could any regular Linux user shed a bit more light on this subject?

    PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.5/site-packages/transcrypt/modules/org/transcrypt/__javascript__/extra'

sounds to me that the permissions to write into the install dir is only required at the very first run of transcrypt, where it compiles core modules from python to js. 

All subsequent compilations won't need the permission, since the files are then there.

=> so I would not consider the problem major (?) Maybe a pip install should do the compilation while having sudo perms, though.

**Comment by JdeH** [comment]
Problem is that there are several, switch controlled, ways to compile. Compiling for ES6 will produce code that differs from ES5 code. The same holds for --fcall and other switches.

**Comment by kozec** [comment]
> sounds to me that the permissions to write into the install dir is only required at the very first run of transcrypt, where it compiles core modules from python to js.

Not only on first run. Every time when new script from /usr/something... directory is imported. Make some random test.py, compile it as root and you _can_ compile it as regular user after. But try adding `import math` and you are crashing with PermissionError. And what's worse, instead of actual error, you'll get `Can't import module 'math'` message. That's not really usable for anything...

I can understand this concept being foreign for Windows user, but on *nix, programs and libraries are not  user-writable for good reasons. And as it stands now, Transcrypt don't seems to be usable on normal system without very special configuration.

**Comment by AXGKl** [comment]
Reading through the whole thread:

> ...pretty catastrophic from security viewpoint. By the way, I'm surprised you haven't had this problem before. Am I first one ever trying to run Transcrypt on Linux? :)

Let me assure you, that I'm happily using Transcrypt (also in production) since over half a year and last time I was developing on a windows machine was sth. with Excel 4.0, some 25 years ago...

Having said that: On Linux you seem to do sth wrong with your venv isolation, you must clearly prevent it from using system packages but fully isolate it, if you have no perms there. Thats the default in Python3 since long:

```
 --no-site-packages    DEPRECATED. Retained only for backward compatibility.
                        Not having access to global site-packages is now the
                        default behavior.
  --system-site-packages
                        Give the virtual environment access to the global
                        site-packages.
```

Note: My previous answer was referring to the fact that after a first compile you still CAN play around on a site wide installation of transcrypt w/o even creating a venv but you are clearly restricted regarding importing site wide mods and thats how it should be, in the end this is a transpiler. If you want your own transcrypt then pip install it into a properly configured venv and have no restrictions.

So:  

This is after a default virtualenv install followed by activation and pip install transcrypt within:

```python
[klessinger@localhost ~]$ touch /usr/bin/foo
touch: cannot touch '/usr/bin/foo': Permission denied
[klessinger@localhost ~]$ . venvtest/test/bin/activate
(test) [klessinger@localhost ~]$ vi t.py
(test) [klessinger@localhost ~]$ cat t.py 
import math

print (sin(42))

(test) [klessinger@localhost ~]$ transcrypt -bn t.py 
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.3
Copyright (C) Geatec Engineering. License: Apache 2.0

Saving result in: /home/klessinger/__javascript__/t.js

Ready
```

Btw: 

Conda based python setups work equally well, clear, *all* remains local in the users' $HOME.


Last one:

> Virtualenv magic affects only PYTHONPATH & co, it will not allow Transcrypt to write /usr/bin subdirectory. 

Virtualenv magic prevents the python binary even consider the root folder. 


Cheers,
G.

**Comment by JdeH** [comment]
@AXGKl 

Thanks for the clarification, that's exactly how I used virtualenv and indeed everything was local to the project directory where virualenv was activated. Since I needed Numpy for Python 3.5 I now use Miniconda, indeed also like you describe.

 @kozec 

If you don't need Numpy, probably the virtualenv route is to be preferred, since you may need different setups for different projects, using different compiler switches. An educational project would have -o switched on, a high volume website would have -f switched on, an intranet site may have -e 6 switched on etc.. By separating your projects in this way, there's no need to compile all of the libs over and over again, which should speed up compilation, especially if you exclude minification during development by using the -n switch.

Hope this helps.

**Comment by JdeH** [comment]
Seems virtualenv can solve this.
If not, please reopen.

**Comment by kozec** [comment]
It's not really solution, just dirty workaround for rather big problem.

I can't really use virtualenv for what I'm doing here, but I already found another python to javascript solution that actually works, so if this really _is_ how Transcrypt is supposed to work, there is no issue.

**Comment by JdeH** [comment]
Thanks for your reaction.
I was unaware that there are situations in which virtualenv can't be used!
Could you tell me a bit more about that.

**Comment by GULPF** [comment]
Honestly, even if there where no situations where virtualenv can't be used, it's a bit silly that virtualenv is __required__. Especially when it's not mentioned anywhere (as far as I know). When I first got this error with the math module, I simply assumed transcrypt didn't implement it.

Why does the compiled JS have to be centrally available?

**Comment by RCL-Carl** [comment]
I havent had an issue with venv, but i agree that the current deployment
model is lacking in this regard. It is my opinion that the short comings
with respect to using "git status" issue #172 is also linked with this
limitation. I personally think that a build directory, that possibly mimics
the transcrypt's distribution directory structure, in the directory where
transcrypt is called might be a better solution. All the built js files
would then be put into the build subdirs. Any js files from transcrypt
could be included by copy or symlink.

This would also prevent the issue of "git status because there would not be
a combination of build files and source files in the transcrypt directory.

**Comment by kozec** [comment]
> I was unaware that there are situations in which virtualenv can't be used!
Could you tell me a bit more about that.

I'm using build machine that starts every build in fresh home directory. It helps catching that kind of weird bugs which seemingly happens everyone but on my own machine. Build script, of course, doesn't have any rights that common user don't, so Transcrypt falls right into its face.

It would be _probably_ possible to install virtualenv there, but it would mean to reinstall every library every time when build is started. Frankly, that's PITA on such level where it's easier to search for another compiler solution.

In any case, I believe that using virtualenv as workaround for writing data to installation directory is just wrong :)

**Comment by AXGKl** [comment]
@kozec : Here is a solution which 

1. does not require perms beyond user
1. allows you to use any system python library
1. does not require venv:


```
~ $ whoami
gk
~ $ touch /usr/bin/foo
touch: /usr/bin/foo: Permission denied
~ $ mkdir test; cd test
~/test $ pip3 install --install-option=--prefix="$HOME/test" transcrypt
(...)Collecting transcrypt
  Using cached Transcrypt-3.6.3.zip
Installing collected packages: transcrypt
  Running setup.py install for transcrypt ... done
Successfully installed transcrypt
~/test $ tree -L 4 
.
├── bin
│   └── transcrypt
└── lib
    └── python3.5
        └── site-packages
            ├── Transcrypt-3.6.3-py3.5.egg-info
            └── transcrypt

6 directories, 1 file
~/test $ export PATH="$HOME/test/bin:$PATH"
~/test $ export PYTHONPATH="$HOME/test/lib/python3.5/site-packages:$PYTHONPATH"

~/test $ echo "import math
> print(math.sin(1))" > r.py
~/test $ transcrypt -bn r.py 
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.3
Copyright (C) Geatec Engineering. License: Apache 2.0

Saving result in: /Users/gk/test/__javascript__/r.js

Ready
~/test $ tail -n 10 __javascript__/r.js 
		var math = {};
		__nest__ (math, '', __init__ (__world__.math));
		print (math.sin (1));
		__pragma__ ('<use>' +
			'math' +
		'</use>')
	}) ();
	return __all__;
}
window ['r'] = r ();
```

**Comment by kozec** [comment]
> But this specific issue here is just an absolute no brainer for anybody who has a bit experience on Linux. I'm with @RCL-Carl, i.e. its not exactly nice that transcypt writes those build files into its lib folders but its definitely not the showstopper you seem to want(?) it to be.

To be blunt, it literally makes Transcript unusable without specific, undocumented configuration. On top of that, this unexpected behavior may and will cause errors with misleading messages.

Anyone with experience with Linux should run away screaming from that :D

--

But I appreciate your help, this way should work without reinstalling _everything_ with every build. But reinstalling Transcript is still needed, so it would make my build script _less_ crazy, not sane as I would like it.

**Comment by AXGKl** [comment]
@kozec: Okay okay, I beg a pardon, guess you DO have 'a bit experience on Linux', hope you accept my excuse, I had a hard day ;-)

I don't think you need to reinstall Transcrypt for a less crazy build script, I mean not more than for the other stuff (some people always start from scratch in builds, as you know). Why? Because there is the clean switch on the transcrypt CLI, where it disregards anything built previously, it won't affect your current build.
So you have clean conditions, even when your install folders are "messed up" as you say.

And if you don't believe me than throw a copy on write layer over it and you are also done. 

I personally would do it via a hg clone which efficient and which I'd delete after each build.

There are so many ways.

----

having said all this: Yes, we are all with you that its not nice what Transcrypt does - but its advantages by far outweigh this (for example I could not live w/o multiinheritance and only Transcrypt....)

**Comment by JdeH** [comment]
I think having the build-directory like @RCL-Carl proposes, represents a descent tradeoff between investment / complexity and returns. So propose to make it that way. Probably it should be under a switch, not to break any existing setups.

**Comment by JdeH** [comment]
While this is very important, it should be solved in combination with things like modular distribution.

**Comment by JdeH** [comment]
This issue will be cured with the release of Transcrypt 3.7.1
