### ISSUE TITLE
T-RFC1: Cooperation and division of labour.

### ISSUE THREAD

**Issue by JdeH** [QQuick/Transcrypt#193]
[EDIT]

------

As a result of this RFC, the discussion below and experiment that followed it, @JdeH decides the following:

> 1. To keep the subjects and the subject owners, since without them the scope of my mind is too much the limiting factor. My impression is the subject/owner thing really speeds up the project and enhances its quality. While maintaining course, I will base myself largely on the judgement of the subject owners for details.
> 2. Keep the janitor team with push privilege to the whole repo. currently it's having me as only member, but that may be altered simply by adding other team members, on temporary or lasting basis if the need arises. Let's cross that bridge if we get to it, currently I don't think it's a problem.
> 3. To create labels to assign issues to subjects. Such a label is a request from the janitor to the subject owner to take the issue under his (m/f) care.
> 4. To keep the subject teams, simply as an explicitation of who the subject owners are.
> 5. To do away with subject branches. Nice try but didn't work as expected.
> 6. To NOT introduce subtree's, submodules, subrepo's or whatever they may be called, since they tie directory structure to subject structure, which is far too restrictive. File level permissions maybe come closest to what we really need, but GitHub currently doesn't allow that.

------

[END EDIT]

Transcrypt: the transition from chapel to bazaar
------------------------------------------------

Now that more people are getting involved in developing Transcrypt, I'm looking for a way to allow this project to grow orderly without myself being a bottleneck. This means that I'll have to let go without losing control.

What I would like to do is to take some parts of Transcrypt, I'll name them subjects, and assign them to  an owner. Any changes to a particular subject go through the owner for approval before being commited. The owner takes responsibility for the code quality of that subject, and it is upto him/her to decide if an when to refactor. I'll stay in the loop as far as code functionality is concerned, and I'll also do the final merges for now, but I will not impose my ideas on code structure upon every part of Transcrypt.

Ownership: coordinated freedom
------------------------------

When I work on a piece of code alone, it's structure is like a sawtooth. When adding a new feature, I primarily try to get it to work, structuring my code as well as I can, but sometimes postponing reorganization. Until I discover that the sub-optimal structure starts to interfere with my productivity. I then stop adding features and concentrate on refactoring for a while.

But suppose my code is currently in flux, not yet being refactored, and someone else starts adding features in the "messy" stage my code is in, then I'm in for trouble. This is because this other person doesn't know what orderly, consequent structure I had in mind. He just thinks the current structure is how I wanted it and starts out from there. Because he doesn't have the eventual structure in mind, it will be harder for me to refactor, after he added his features. So what I would do in that case is consult with him, either explaining what the structure will be, or asking him to wait a little until I've made it shipshape again. In other words I assume a coordinating role for that piece of code, I "own" it. 

Smallest common multiple rather than largest common denominator
---------------------------------------------------------------

I believe that in a good development team, people should be empowered to use their specific talents and hard fought skills, including their individual design and coding style, which makes up a great part of the added value of a good developer. I've worked a lot in companies where the lowest common denominator was the norm. Don't want to do that here, it kills the fun and wastes talent. Still for a certain coherent subject, thinly interfaced with the rest, there must probably be one style. But it is the style favored by the owner of that subject, not by me. This holds for interesting parts like overall structure, uses of classes, inheritance, parameters or members, patterns etc., but also for the superficial, often religious ones, like code layout and naming conventions.

Saying all this I am well aware that any contribution to this project is and will remain on a volunteer basis. Nevertheless I sense that working on an open source project sparks commitment and enthusiasm. The quality of the contributed code I've seen, often surpasses what I get when working with fixed, professional development team. To streamline development of Transcrypt, some permanent, lightweight organisational structure is needed. People assuming certain roles may change, but the roles themselves should be well thought through. And of course, people staying in certain role for a longer time have a positive influence on unity of concept and productivity.

So with this T-RFC, I'd like to introduce the notions of 'subject' and 'subject owner'
-------------------------------------------------------------------------------------------

A subject within Transcrypt is a piece of functionality or activity that is internally highly interconnected, but has a thin interface to other subjects. While this is what programmers call a module, this term is deliberately avoided, since in the Python world it has a very specific meaning. Also a subject doesn't need to concern source code. Probably the concept is made most clear by example. Subjects are e.g.:

- The Transcrypt core (`__main__.py, compiler.py, __core__.js, __builtins__.js, __standard__.py, __base.py__, ...`)
- The continuous integration system
- The autotest system
- A certain library or group of libraries
- External communications, e.g. the website
- The development process (what I am trying to streamline a bit rightnow)
- Planning and managing of releases
- Commit / merge / branch management
- The demo's
- Tutorials
- ...

QQuick and invitations
----------------------

To fit the GitHub way of doing things, a distinction is made between an organisation and a project. The organization that 'hosts' the Transcrypt project is QQuick. It's aim is to produce open source software. Anything produced by the QQuick organization is open source distributed under a liberal license like Apache 2, MIT or the legacy QQuick license. Since QQuick is still small, I'll make no attempt to invite owners for each and every subject related to Transcrypt. But if someone clearly seems the most knowledgeable about certain part, chances are that he/she will receive an invitation. QQuick isn't yet a legal entity. But it could become one in the long run, probably a foundation. It will never have the aim of making a profit. The current website of QQuick is a legacy thing, which doesn't matter much, since the website of Transcrypt is more important.

Let me be clear: An invitation is just an invitation. There isn't any pressure to accept! If you just contribute code, bug reports or idea's: great, keep up this essential work! But if you feel it would indeed be best for the project if you would own a certain subject, then accept the invitation. Ownership does **not** mean you'll have to code everything (or anything) yourself. If you accept it, issue's and PR's about that subject will be routed via you. Overall functionality still goes through me, and I'll keep a final say in what gets in and what not. But I'll rely on the subject owners to a large extent. Currently I invite myself to be owner of the Transcrypt core. And I've decided to accept.

Jacques de Hooge

**Comment by AXGKl** [comment]
Hi, Jacques, good idea to assign owners of certain subjects. 

I did not fully understand what you expect from e.g. me regarding CI when I accept ownership for CI: Am I exepected to follow all issues all the time then? Or would you send me an email with "Pls ack this and that" ? Because staying up to date and read ALL transcrypt issues ALL the time I can't guarantee at least not forever, as much as I would like to, its not realistic.

=> question: maybe its a good idea to split Transcrypt then into different repos where you can then freely assign push perms to certain people you deem capable enough to not screw the whole thing, i.e. owners but also others.

I would see (first shot, not too much thinking):

- transcrypt_core
- transcrypt_documentation
- transcrypt_testing
- transcrypt_continuous_integration
- transcrypt_modules [ time, re, logging, ...]
- transcrypt_backend {nothing yet there}
- transcrypt_assets (like demos but also maybe webapps 

I mean then the owner could directly push and also assign push perms to others, core always only you, here only way to get code in is via a concrete PR (or a request to you). The core than just has refs to certain version of those subrepos.  (I just know how this works in mercurial but I think in git its also possible to include subrepos in the main one, keep the version fixed until a PR for it come from the owner or an authorized delegate).


Then you don't have to follow each and every discussion regarding sub repos and just can relax and await the final conclusion in the form of a PR for a git subrepo version change within transcrypt_core
Also as an owner of e.g. CI, with full perms on that I could directly give also full perms to e.g. @RCL-Carl, to speed up agility on such a non critical subrepo.

**Comment by JdeH** [comment]
Hi,

**About 'what you expect from me'**

Competent and energetic team members like you will in most cases be very busy in their professional activities and beyond. So, as I hopefully made clear in T-RFC1, I can 'expect' nothing, if 'expect' would mean claim in any sense. Currently my idea is to assign something to you if it's in your subject, which is the GitHub workstream equivalent of 'please look into that'.  So I would do the watching, that's not a big problem for me. Assigning would not mean 'please solve it' but rather 'please decide upon it, delegate it and QC the result'.

What IS a big problem is that as Transcrypt expands, while I can keep up with the overall direction and functionality of Transcrypt, I cannot possibly keep up  with following each in-depth discussion of every subject. My instinct is to try to control everything on a detail level, but I have to resist that instinct, since that would be a 'cathedral', not a 'bazaar' approach. So I have to rely on the opinion of the owner of a particular subject. Only by relying on other peoples expertise and judgement will this project transcend the limits of individual capabilities.

I hope this puts your mind at ease with regards to what you're getting into. Ownership is something that can be tried, interrupted, transferred, continued or terminated on your request any time. It may be that for many months you don't have time and someone else will have to take over. If no one will, lastly I'll have to do it myself. But the more this type of thing can be distributed MOST OF THE TIME, the faster the project will move. Also,  I expect the quality of the decision outcomes to be far better. It would be rather foolish of me to assume that I know everything better and of course I know I don't. But I DO have to guard the overall design goals. And indeed I do have my own subject to attent to which is the core.

**About splitting in multiple repo's assigning push privileges**

In the end that's what has to happen. But I only want to move it one step at a time. Transferring Transcrypt from a personal account to an organization was a first step. I have accepted that currently the major part of my attention should go the process, rather than the content, only to free up myself later to work on the core again. Taking the steps you describe should be done properly, since there's hardly a way back, and, if done wrong, there will be chaos. So I first want to gain experience with subjects and ownership.

I want to make one thing fully clear. My hesitation is has to do with fathoming the possibilities and limitations of GitHub, not with trusting push privileges on to you and other team members. We can make the move to multiple repositories only if the technical consequences are fully clear.

So yes, eventually the repository should be split, and push privileges with it. It is simply the most powerful, scalable approach. But for now let's look how the subject/owner thing turns out in practice. 
Meanwhile I try to get my head around what exactly is and what isn't possible with GitHub organisations and repos.

**Comment by AXGKl** [comment]
ok, fully understood. So I accept the ownership and you can (continue to) assign issues with CI and time module and also the (unfortunatelly but prio2) still missing config module to me. But please keep a note that you don't need to wait for my approval if certain people I consider capable send you PRs regarding those subjects. Like Carl for CI. Accept them like you would accept mine.

Regarding the splitting into repos: Key, imho, is submodules. One main repo which only you push containing refs to subrepos in certain revisions.

**Comment by JdeH** [comment]
I am very pleased that you accept the ownership of CI! As for the config module: take your time. I absolutely agree that you gave priority to CI.

Splitting the repo: glad I'm not the only one that considers GitHub complicated, perhaps vulnerable at some points. Indeed it seems that many things could have been more straightforward.  On the other hand I greatly appreciate what's there, and it seems to be rather stable, although some days ago they went flat on the floor for several hours. Most important thing is that it's mainstream. We'll find a way make it do what we want, I guess. Will dive into that.

**Comment by AXGKl** [comment]
Thanks god we have the git manpage gen: https://git-man-page-generator.lokaltog.net

have a look at it ;-)

**Comment by JdeH** [comment]
LOL!

**Comment by AXGKl** [comment]
think people widely [agree](http://softwareengineering.stackexchange.com/questions/87217/why-is-mercurial-considered-to-be-easier-than-git) mercurial is simpler while not at all less powerful. 

Without GitHub I dare to claim that mercurial would be the leading DVCS. But well, github does not support mercurial and bitbucket seems no alternative we'll have to struggle on with git and its unnecessary complexities. Maybe some day I come up with a proposal of using a mercurial to git bridge for the two of us (since no body else seems to have problems with git ;-) )

**Comment by RCL-Carl** [comment]
@JdeH - per your invitation in another thread, I can take on the autotester browser view part of the code base. I'm assuming that the responsibilities you are looking for are:

1. Guide development of this module specifically with respect to arch and features. This would include providing feedback to other developers about what code changes we should make in the future
2. Code review for changes being applied to the autotester. This would include pulling the code down and testing any new changes to QA it if possible. 
3. Possibly continue submitting code to maintain this or delegate to others if possible. 

As I don't have write access to this repo, the most that I can do is comment on PR's and give a sign-off of sorts. Is this what you are looking for?

----------

> maybe its a good idea to split Transcrypt then into different repos where you can then freely assign push perms to certain people

I think this is an interesting idea. It also allows some control of robustness for @JdeH at the higher level. The concept that @AXGKl describes with updating the referenced hashs in the main project is what I had in mind as well. As @JdeH discussed at length, I think we should be careful about taking this idea on too fast. I think starting small with perhaps the core including docs, testing, and ci in one repo and the non-core library modules in another repo referenced as a git submodule from the core could be an interesting first step toward this when everyone is comfortable with it. We could then evaluate the efficacy of this approach in a chunk that is reversible (certainly not trivial but also not impossible while preserving git revision history of all files). 

----------

@JdeH you touched on several things and I'd like to discuss just a few of them in further detail. 

> Still for a certain coherent subject, thinly interfaced with the rest, there must probably be one style. But it is the style favored by the owner of that subject, not by me. This holds for interesting parts like overall structure, uses of classes, inheritance, parameters or members, patterns etc., but also for the superficial, often religious ones, like code layout and naming conventions.

I think I agree in essence of what you are saying here - a certain amount of individualism is needed and allows for freedom to solve problems that might not have been envisioned by others. But I also think there are some core pieces that we need to all agree on. Specifically, I think "tabs" vs "spaces" for indentation is necessary because of the nature of python (damn you "IndentationError"). It is my understanding that the core of the python and javascript is using tabs which I like, but there are files I run into every once in a while that have spaces instead of tabs. I'm not saying that we need to change anything right now but I do think we should have a agreed upon decision of how all files will be formatted. 

I think that the code formatting style in the strictest sense is possibly less important but I do think
that there are some aspects of code format that many would agree are important. For example, my
list of these items would include: 

1. Line length limit -  lines should not be 1000's of characters long. I personally try to keep it in the 80 char range, but I've seen other projects select the 120 char range.
2. Choice of documentation formatting - I think projects like [epydoc](http://epydoc.sourceforge.net/) are great, but possibly doxygen might be better for this project as it could apply to both javascript and python. Regardless, a consistent documentation style will allow us to more easily automate documentation generation.

There are others that could be on this list but I think these are the most important. I don't think these limit the creativity of the author but they do provide a communal benefit.

> But suppose my code is currently in flux, not yet being refactored, and someone else starts adding features in the "messy" stage my code is in, then I'm in for trouble. 

I understand what you mean in this section and I agree that this is a difficult thing to manage especially for an open source project where you don't want to make it seem like you are discouraging contribution. One thing that I think could help with this is a roadmap list, possibly tied to Issues in github, that outlines:

1. What is the highest priority right now 
2. What tasks are currently in progress
3. Where are we going from here 

One item that @AXGKl had mentioned in a separate thread was the concept of maybe a backend that integrates with transcrypt. I'm not sure how I feel about that yet, but for a project that I'm in the process of formulating in my mind, I know I will want to build something like that. My ideas of what that looks like, compared to @AXGKl and @JdeH, are likely very different. I'm not even sure it necessarily makes sense for them to be included here - it may make more sense for them to be in a separate project/repo. It may make more sense to concentrate efforts on getting a more stable transcrypt framework first. My biggest complaint with a lot of javascript projects is instability, exceptions galore, etc. so that is a priority for me. 

But a roadmap could at least provide a list of the items that this project is concentrating on right now and where the group wants the project to go at least in the short and medium term. Perhaps this roadmap already exists and I missed it. 

--------------

This is a personal preference to a certain extent and partly aesthetic, but I feel this is probably a good place to bring it up. When I manage projects with git where there are multiple contributors, I like to use `git rebase` on as many of the PR as I possibly can. This has the nice feature that the git repository history is linear in most respects. Additionally, it removes a lot of the commits that have a comment that is basically just "merged PR 123". I feel that it is also more effective for doing regression examination using `git bisect`. Anyway - just an idea.

**Comment by AXGKl** [comment]
2 cents here regarding **coding conventions**, specificically regarding **Tab vs Spaces**:
I see the problem in different conventions across one repo and I'm not religious about pep 8 but we have to see that the vast majority of python devs (incl. me) is using spaces and forcing them to use tabs in *their* code could cause pain. I think for independent modules/parts of transcrypt we should continue to allow spaces as well - but not have 2 different conventions e.g. in one directory. Plus we should begin to insert declarations, think its called ctags(?) in the beginning of the files, telling the editor to adapt automatically.
This one can also be postponed since convertable automatically.

**Comment by JdeH** [comment]
@RCL-Carl:

> Is this what you are looking for?

 That's exactly what I am looking for. I am very happy that you will assume ownership of this part of Transcrypt!

------

@RCL-Carl @AXGKI:

Lots of valuable information in what you both propose. It'll take me some time to digest and think. So it's too early for me to react on everything, but I will certainly get back on this. Think it's important to let this take solid shape in our heads  before doing anything. My limited GitHub knowledge is an impediment, but I'll try to resolve that in the coming days.

------

While I can not yet react to most of your ideas in a way that does justice to their quality, I can already share my opinion on the code formatting issue.

Transcrypt originally is an offspin of a longer running research project with multiple people working on it.    This is why upto now, I've quite rigidly adhered to some things that aren't mainstream in the Python world. Partially I'll keep on doing so, but on some points it is wiser now to adapt.

The tabs / spaces thing is one such point. Since most of the Python community uses them, I propose to completely switch to spaces, even though my personal pref lies with tabs. So tabs will be banned a.f.i.k., even from the core. No need for a big bang operation here, the transition can be made per file, as we encounter them. I prefer to convert the core myself.

Furthermore I'd like to restrict the line length to preferably 180 chars or at least 160 chars. For a high-resolution screen like almost anyone has these days, that's perfectly OK. And if not there's always automatic wrapping. Since long lines mean more info per screen, more context is shown, which I consider essential in keeping an overview without sacrificing any trees (we used to call that printing). Of course anyone is free to make shorter lines, it's just an upper limit. Going lower that 160 chars would really be a severe and unneeded handicap for me, and I may not be the only one. There's no dogma behind this, but I am one of the developers who want to bring the full quality of my working habits to this project.

For Transcrypt core identifiers that are in the API, like \_\_envir\_\_.transpiler_name, I think it's wise to enforce adherence to PEP, but only there.

For the rest of the formatting story: Lets leave people completely free. I for one need that freedom to be productive.

------

One thing I also consider important: If I work on a module that someone else created, I try to adhere to the code style of the creator. So if some created a module using pothole case and max 80 chars, I'll adhere to that. I'd like this type of flexibility and respect for the way of working of others to be the norm for anyone working on this project.

------

As said I can currently only react on something as superficial as code formatting. There are other parts in the proposals that are more important, but as said, I need some time on them since we have to do them right the first time if possible. Finding a clever way in this issues maybe is more important to the project now than line by line code quality, so I'll give it priority.

To be continued...

**Comment by JdeH** [comment]
I've been looking quite extensively into the possibilities of GitHub with respect to splitting up a repository into "partial repos".

There are currently at least three ways to do that: submodules (https://git-scm.com/book/en/v2/Git-Tools-Submodules), subtrees (https://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/) and subrepos (https://github.com/ingydotnet/git-subrepo).

------

What all of these "partial repo" approaches have in common is that they equate the directories to subjects as defined in T-RFC1 / Issue #193.
Since the directory hierarchy in the repo is also the directory hierarchy in the installation, for any of these approaches the following equality holds.

<folder in the installation> == <folder in the repo> == <partial repo>

There are two =='s here, one that's desirable and one that in my view isn't.

I like the left one: <folder in the installation> == <folder in the repo>
It is conceptually simple and makes installation and even partial replacement of an installation easy and intuitive.
With regard to transparence it's the opposite of the dreaded registry, that makes (un)installation of anything on Windows a perilous adventure.
Even Microsoft eventually came up with the notion of XCopy installation, which boils down to: <folder in the installation> == <folder in the repo>.
(Admitted DLL's are still hidden all over the system like easter eggs in a garden)

But I do not at all like the right one: <folder in the repo> == <partial repo>
The reason I don't like the right one is that the transitivity of == leads to: <folder in the installation> == <partial repo>
This would tie the evolving way we want to divide ownership of subjects to the installation folder hierarchy.

I consider that too restrictive. We should be able to place elements of Transcrypt anywhere we see fit from an installation point of view.
The design decision with regard to where in the directory hierarchy to place a file, should not be dictated by the way we want to split ownership.
Subject and ownership boundaries must be able to be freely choosen and moved, sometimes splitting things that are in the same directory over multiple subjects,
sometimes taking things that are not in the same directory (like __main__.py and compiler.py) together in one subject (core).

Apart from that all, three 'partial repo' approaches add a lot of complexity and vulnerability. Apart from bugs in these facilities that may result in loss of work, they are relatively complex compared to the very simple, very logical basis of Git. Note that I am not saying that the command line interface of Git or the web interface of GitHub are simple. Especially the command line interface is (in my view) needlessly complex. But Linus' notions of immutable, hash-addressed blobs pointing to each other, and branches just being moveable 'labels', is of a beautiful simplicity and highly robust. Subrepo's or variations on that have a reputation of complicating version management and being prone to human mistakes. Therefor I'd rather not use them.

------

There's a simple low-tech alternative to all this complexity, that matches the following requirements:

R1. Subject owners should have enough rights to accept PR's on their own judgement without consultation.
R2. Before anything goes enter the central repo, there's an extra check on 'intersubject consistency', by a central 'guard', currently me.
R3. Division into subjects doesn't force any directory hierarchy and can easily shift without changing the structure of any repo.

All that this takes is one repository per subject, inside the organization, updated from the central repo when the subject owners sees fit.
And, again when the owner sees fit, a pull request from this subject repo to the central repo is issued.
The 'guard' of the central repo doesn't look into all technicalities of this pull request.
He (m/f) just checks that the files are indeed inside that subject and if not, takes an extra good look at the ones that aren't (but may nevertheless be accepted).

Note that the subject repositories are indeed inside the project, they aren't private repos, like the individual contributers development repos.
The subject repos and the central repo currently will only have a master branch for simplicity. The boundaries between subjects can be shift easily,
just creating new subject repo's while the old ones still exist and, when the time is right, issuing pull requests from the new ones rather than from the old ones.

Of course the repo's of the individual contributers don't have any such restriction, they can have as much complexity as the distributer can handle.

Updating the subject repo's from the central repo using a pull is very simple most of the time, since the subjects are highly disjunct.

So the 'flow' is as follows:

<local repo> --(developer)-->
<developer repo in individual account> --(subject owner)-->
<subject repo in qquick organization> --(central guard)-->
<central repo in qquick organization>

In my view this structure warants optimal flexibility, minimal complexity and a good scalability and separation of concerns.

------

@AXGKl, @RCL-Carl, others, what do you think of this approach?

**Comment by AXGKl** [comment]
request for confirmation: You suggest we fork the master transcrypt repo a few times within the qquick organisation, then add there subject specific stuff, until happy then send from those, from time to time a PR to the master transcrypt repo? So basically like feature branches but within seperated forks, with their own issue lists right? Would this be even possible in github, to have the same repo a few times?

**Comment by JdeH** [comment]
Yes, thats what I mean.

Would it be possible? Well, I blindly assumed that it would, but I may have been too optimistic. Well, I guess the worst thing that could happen is that each subject corresponds to a Git account. I hope that's not needed, will look into it. The main point is that neither Git limitations, nor subject boundaries should dictate our directory structure.

I'll take an even closer look at Git, but probably you're right, in which case we'll find a way around it, e.g. separate accounts, and a paragraph about contributing on the main repo's readme with hyperlinks to the subject accounts. Base line is that (within reason) we'll make Git do what we want, rather than let it dictate crucial design decisions for us. It is after all only a VCS...

**Comment by AXGKl** [comment]
I must say *I* actually like the idea to have a full transcrypt at hand for the subject specific stuff, makes all the handling and testing very simple - and the PRs, and the subject specific issue lists w/o the need to filter all the time. Guess the standard git way to do what you propose is to use feature branches and filters on github for the isolation of contributions but your proposed way I like better, since we both seem to have the same attitude towards git (and that is: stay shallow with it ;-))

Checked a bit around and it does not seem to be possible though to have same repos in one org - so I suggest we do the accounts ?  Account name then like transcrypt_continuous_integration ?

**Comment by JdeH** [comment]
Indeed account names would be like you propose, but lets keep this under consideration for a (short)while.

Problem with simply using branches is that push privilege isn't per branch. There has been discussion of that, but not any sign that's going to be built in.

As to not using branches and what people think of it. We should choose what gives us maximum leeway in development. In that way we'll have a superior product and I hope that's what people focus on first. We may even set a trend... (or encourage Git people to build in privileges per branch).

**Comment by AXGKl** [comment]
@JdeH : Topic unrelated sidenote regarding merc: I keep mentioning it ONLY to sort of excuse my lack of git know how, I 100% know that github is the only place where Transcrypt belongs, there is no alternative.
Sidenote to the sidenote: Python split with merc at least *also*, because the mercurial people have the exact [same problems]( https://www.mercurial-scm.org/wiki/SupportedPythonVersions#Python_3.x_support) with Python 3's unicode everywhere fubar, I mentioned elsewhere.

**Comment by JdeH** [comment]
Hi,

Seems that GitHub can do what we need after all, inside one organisation.
I've first experimented with organisation QQuickTryout, a dummy repo with protected branches and dummy teams.
All seems to work fine.
Then I put in place this structure in the regular QQuick organization.
Since it doesn't alter any of the facilities that we already had, I propose to try out this new structure.
I see no obvious risks in this.

1. Each subject has a protected branch
2. For each subject there's an owner team
3. The subject owner is member of the owner team (but shared or delegated ownership is trivially possible)
4. The protected branch grants writing access only to the owner team 
5. There's one master branch (just the one we already had)
6. For this master branch there's a master merge team
7. Currently I am the only member of that team (but this task can also trivially be shared or delegated)
8. The master branch grants writing access only to the master merge team
9. PR's for a certain subject always are directed to one of the subject branches
10. The subject owner (or rather members of the s.o. team for that s.) determines which PR's to accept
11. Contributions of the subject owner are also run through the subject branch
12. Whenever the subject owner sees fit, he (m/f) issues a pull request to the master branch
13. The master merger (or rather members of the m.m. team) checks the PR superficially, mainly whether it is indeed within the subject. For parts that aren't he consults with the owners of the subjects that are touched by it.
14. The master merger either gives feedback to the originator of the PR (so the owner of the subject branch that the PR 'came from' or accepts it.

I have a strong feeling that this will work like a charm. Maybe small adjustments are needed. Maybe I also missed something crucial... If not, lets just start doing it this way. Anyhow I'll start by committing core contributions along this route.

Reactions most welcome.

**Comment by JdeH** [comment]
@AXGKl, @RCL-Carl, others

**Seems github can supports subjects  and owner privileges after all, even inside one repo**

Seems that GitHub can do what we need after all, inside one organisation.
I've first experimented with organisation QQuickTryout, a dummy repo with protected branches and dummy teams. All seems to work fine. After that I've put in place this structure in the regular QQuick organization. Since it doesn't alter any of the facilities that we already had, I propose to try out this new structure. I see no obvious risks in this, correct me if I'm wrong.

> **1. Each subject has a permanent, protected branch
> 2. For each subject there's an owner team
> 3. The subject owner is member of the owner team (but shared or delegated ownership is trivially possible)
> 4. The protected branch grants writing access only to the owner team
> 5. There's one master branch (just the one we already had)
> 6. For this master branch there's a master merge team
> 7. Currently I am the only member of that team (but this task can also trivially be shared or delegated)
> 8. The master branch grants writing access only to the master merge team
> 9. PR's for a certain subject always are directed to one of the subject branches
> 10. The subject owner (or rather members of the s.o. team for that s.) determines which PR's to accept
> 11. Contributions of the subject owner are also run through the subject branch
> 12. Whenever the subject owner sees fit, he pulls from the master branch (not to be confused with 14)
> 13. While the subject owner can technically also pull from other subject branches, this should be avoided other than for test purposes, since it will result in PR's to the central branch that cross subject boundaries and contain code that's not yet considered mature by the owner of the other subject that was pulled from.
> 14. Whenever the subject owner sees fit, he (m/f) issues a pull request to the master branch
> 15. The master merger (or rather members of the m.m. team) checks the PR superficially, mainly whether it is indeed within the subject. For parts that aren't he consults with the owners of the subjects that are touched by it.
> 16. The master merger either gives feedback to the originator of the PR (so the owner of the subject branch that the PR 'came from' or accepts it.**

It's seems quite a mouthful, but basically it's rather straightorward. I have a strong feeling that this will work like a charm. Maybe small adjustments are needed. Maybe I also missed something crucial... If not, lets just start doing it this way. Anyhow I'll start by committing core contributions along this route.

Reactions most welcome.

**Comment by RCL-Carl** [comment]
@JdeH 

I'm not super familiar with Github's Organizations concept so I don't know what level of control there is. From [this link](https://help.github.com/articles/enabling-branch-restrictions/), it seems what you are talking about is possible - so that is great.  

I certainly would like this approach better than having separate full repos for the different subject areas. I do think that if it is possible, it has some benefits over the rigid "submodule" approach. 

I like that we can try this and if it works well enough, great - we tweak and continue. If it doesn't work, we can just blow the subject branches away and try something else. It is very low cost. 

One concern with this approach is that it may make the repository history tree even more complicated. For example, in the current repo tree:
 
<img width="286" alt="screen shot 2016-11-24 at 11 18 00 am" src="https://cloud.githubusercontent.com/assets/15036736/20608543/b6a71c36-b237-11e6-94e5-dfa3d569655b.png">

There is a lot of complexity here. If we add another layer of indirection with a subject branch merge in between the user contribution and master, I think this tree will get further complicated. I personally see this as a bad thing. If we use rebase appropriately, I think we can avoid this extra complicated repository history tree. It may make sense to keep track of the merge info in requests in the master branch. 

Here is a link to the github docs on [rebase and merge](https://github.com/blog/2243-rebase-and-merge-pull-requests).

> An open question is what to do with PR's from people outside the team that are directed to the master branch. It seems asking a bit much to urge them to resubmit to a subject branch.
> Maybe the 'receiver' can change the destination: https://github.com/blog/2224-change-the-base-branch-of-a-pull-request ?

Ya - I think the process in that link is a pretty painless one and not unreasonable to ask of a new contributor. Additionally, it has the added benefit that if there are other outstanding changes in the subject branch that are similar, it won't cause a nasty conflict that has to be dealt with by the subject team later. 

> Meanwhile the janitor can rapidly conclude if a PR from a subject branch to the master branch is (reasonably) within bounds, by just inspecting the file list. And if it isn't there still may be a pressing reason for the subject owner to offer it like that, motivated in his comments. And the janitor may still accept it after consulting with the owner of the subject that was "trespassed upon". In short: human beings decide what's ok and what isn't, not a computer program. So it won't get in our way.

Yes - that seems reasonable. It does incur some more overhead in review - but perhaps that is not a bad thing.

**Comment by RCL-Carl** [comment]
So - after playing with this new method, I have an observation. What I'm noticing is that the HEAD of each of the subject_* branches are all at different places in the history repository. Which means that unless we micromanage heavily the updating of each individual branch, there is a high probability that previous commits that bring subject_* HEAD to the top of master will also be included in any PR. I'm not sure this is a problem necessarily, but it certainly makes these PRs less clear. 

Take for example, the [latest PR I've issued again subject_libraries](https://github.com/QQuick/Transcrypt/pull/215). It has a bunch of commits from the bugfix to autotester and the callable update. This is because whoever owns "subject_libraries" (I have no idea who owns this) didn't update to the latest master yet and I've at least attempted to keep it updated so that I can use `callable`. There is a string of like 10 commits that have nothing to do with the added code, and 50% of them are "Merged \#xxx" commits.

**Comment by JdeH** [comment]
@RCL-Carl

I've noticed the same and I'd like to see way this of working as an experiment.
There's nothing wrong with an experiment as long as we correct the situation according to our findings.

@RCL-Carl @AXGKl others

Must say I am very pleased with the subjects and owners in itself. Me having a say in every detail simply isn't scalable enough and it does no justice to the fact that others, being 'into' a subject probably have a better judgement. So I'd really like to keep that.

But the only thing that's essential to that, is that the subject owners, apart from contributing, set the course for their subject and evaluate contributions of others. This can also be done simply by the janitor (currently e) labeling an issue as 'request for evaluation' to the subject owner. Since determining the boundary of a subject while merging from subject branch to master is done informally anyhow, I don't see  how the current protected subject-branch system means much improvement in that.

The specific technical reason to introduce subject branches was to allow for more fine-grained privileges. The opposite would be to grant all subject owners write permission to the repo. With three subject owners that's doable, but if the nr of subjects grows, and ownership occasionally is transferred, the risk of chaos grows. So I think it would be unwise to take that step.

What has also come to my mind is that the complexity of the current system will frighten off others from contributing. Instinctively people will clone and branch from master, while they'll have to  PR to a subject branch that may be out of sync. Complications like the one @RCL-Carl  noticed really make the whole version history overly complex.

So I propose:

- To keep the subjects and the subject owners, since without them the scope of my mind is too much the limiting factor. My impression is the subject/owner thing really speeds up the project and enhances its quality. While maintaining course, I will base myself largely on the judgement of the subject owners for details.
- Keep the janitor team with push privilege to the whole repo. currently it's having me as only member, but that may be altered simply by adding other team members, on temporary or lasting basis if the need arises. Let's cross that bridge if we get to it, currently I don't think it's a problem.
- To create labels to assign issues to subjects. Such a label is a request from the janitor to the subject owner to take the issue under his (m/f) care.
- To keep the subject teams, simply as an explicitation of who the subject owners are.
- To do away with subject branches. Nice try but didn't work as expected.
- To NOT introduce subtree's, submodules, subrepo's or whatever they may be called, since they tie directory structure to subject structure, which is far too restrictive. File level permissions maybe come closest to what we really need, but GitHub currently doesn't allow that.

Opinions, please...

Kind regards

**Comment by RCL-Carl** [comment]
Ya - I think keeping it simple is the way to go. I think that lots of projects operate with one person (or a small team) holding read/write access and accepting PRs from a diverse set of people/teams. 

If I may make a suggestion, perhaps you might reach out to some of the organizers of medium or large size projects on github. They may have some lessons learned and guidance as far as how to structure a project for growth or what they eventually settled on. I'm not saying we would do the exact same because every project is going to be different, but not having to reinvent the wheel is nice.

That being said, I think that the management of the project so far, before and during the experiment, was doing just fine. So I don't think we necessarily need to change much if anything. I think the use of labels as you have outlined is a good idea. I've been trying to see if there is a way to get an rss feed for issues and issues with a particular label. Haven't found much in that regard. Github does publish atom feeds for commits and tags. Not sure about what else though.
