### ISSUE TITLE
Conceptual - Thinking about modules

### ISSUE THREAD

**Issue by RCL-Carl** [QQuick/Transcrypt#232]
Hi, 

The following is intended to start a conversation about a thought that I had last night. I'm not necessarily advocating that resources be committed to it but I do think it deserves some discussion. 

As I understand it, modules are currently compiled into a file `__javascript__/<name>.mod.js` which contains the implementation of the js module. If we take the `logging` module for example, it looks something like this:

```
	__nest__ (
		__all__,
		'logging', {
			__all__: {
				__inited__: false,
				__init__: function (__all__) {
					var time = {};
					var warnings = {};
					__nest__ (time, '', __init__ (__world__.time));
					__nest__ (warnings, '', __init__ (__world__.warnings));
					
					//... More Implementation Details going forward...
					
					__pragma__ ('<use>' +
						'time' +
						'warnings' +
					'</use>')
					__pragma__ ('<all>')
						__all__.BASIC_FORMAT = BASIC_FORMAT;
						__all__.BufferingFormatter = BufferingFormatter;

						// ... More defs here ...

						__all__.warn = warn;
						__all__.warning = warning;
					__pragma__ ('</all>')
				}
			}
		}
	);
```

This module then gets included into the main file for the application by copying it into the file, resulting in one large file. There are simplicity benefits to this approach but there are also some limitations to this approach: 

1. It is very difficult to cache the modules in this approach. This means that every time the page is loaded, even if there was just a tiny tweak to the main module, the entire file is reloaded, even the components of the file that have not changed.
2. We have to select whether to load ecma5 or ecma6 at compile time - not at runtime when we actually know what the client is capable of.
3. This is a custom module format that is different from more standard module formats like CommonJS, AMD, etc. which means we have to build custom tools to support it. 
4. All modules are statically compiled, so there is no opportunity really for scheduling optimization of when a module is loaded.

I'm wondering if a better approach might be to use something like [requirejs](http://requirejs.org/) to implement the module format. There are some really nice features that could be added:

1. RequireJS can cache modules so it may be possible to have parts of the core and certain library modules be cached on the client side which would mean that subsequent load bandwidth is reduced.
2. RequireJS modules could be stored on a CDN which could help with deployment of user projects in the future - for example, we could host the latest parts of the core and modules on google CDN or something, and new users could just use them instead of having to host all the files themselves.
3. RequireJS has lazy loading - which means that you could have the `import` function load modules when needed instead of compiling them all into the file. Perhaps we would make a `dynamic_import` or something to differentiate - I don't know - just thinking out loud. But this could be really interesting for single-page applications where you don't necessarily need to load every single page in the tree at the beginning, but can begin loading parts of the tree as the user traverses the site map. 
4. This off-loads a lot of code that this project would otherwise have to maintain that is not necessarily in the core mission of the transcrypt project.
5. We can load other javascript modules in the same format using import just like you would use 3rd-party modules in python - this could make deploying modules on pip or other package manager sites a lot easier.

I'm not saying that this would necessarily be trivial. I haven't thought through everything yet and there may be some critical details that I'm missing. 

Thoughts?

**Comment by AXGKl** [comment]
Hi, a few people had been asking for this already, especially the hot module reloading seems to be sth js SPA devs are used to, using webpack based pipelines.
So yes, I think many many people would like to see requirejs compatible modules...
But, yes, I think not trivial, there is a lot of namespace indirection involved as far as I understand how that works... 

Curiosity: I personally like a js free server - do you think building requirejs compatible modules for hot module reloading could be done with python only on the server side without huge effort?

**Comment by RCL-Carl** [comment]
> Curiosity: I personally like a js free server - do you think building requirejs compatible modules for hot module reloading could be done with python only on the server side without huge effort?

I'm not sure I see where any server side code would be needed. The way I see it, the modules would be compiled in the transcrypt into AMDs and then could be hosted on any CDN. There is no server side code in this model. The client determines what it needs to load, checks the cache to see if it already has the latest, if not, it pulls the appropriate version of the AMD module from the CDN. There may be a security issue here if someone inserts a malicious link to an AMD module you don't own so I think this would assume HTTPS at a minimum.

**Comment by AXGKl** [comment]
Ah I see. I thought those (huge) webpack build pipelines where compiling the js modules into sth different, I mean with one namespace per module so that it can be later reloaded without breaking dependent stuff. But you must be right, since require.js works via CDNs as well it must be possible to do that also/only in the browser.  Sorry for my blatant knowlege gap.

=> Abslutely deserves a "want to have" then, imho.

**Comment by AXGKl** [comment]
wow, I had the permissions to add a prio. @JdeH : is this ok?

**Comment by JdeH** [comment]
Wow, a difficult discussion, this early in the morning (for me).
But it's a subject that had to come on the table at some time.

------

@AXGKl 

About assigning prio's: Since we can only assign one prio to an issue, we can't use them as a voting system.
In general I want to use the prio's in the following way:

- They should balance costs and yields
- The opinion of a subject owner on a prio concerning his subject weighs heavily
- Where possible we should more or less agree on them
- I want to have a final say in which prio something gets

So currently please propose, rather than assign prio's. In general I'd like to do the labeling myself, unless something e.g. clearly is a bug.

------

On the matter brought up by @RCL-Carl : 

The matter of dynamic module loading touches upon many other design choices, the combination of which really poses a big challenge that we must not underestimate.

When we look to dynamic module loading, we ought to take into account all the consequences, and there are a lot. I've assigned it to a subject SUB_infrastructure, although it also touches SUB_core.

It's this infrastructure in general we have to talk about. Honestly I am hesitant to even embark on this discussion, since it's really a hornets nest, but I agree that it's needed. And we should discuss it as part of a roadmap, which is needed as well, although it must not limit our flexibility too much/

I'll create an T-RFC issue for the roadmap and use it to put down some thoughts about priorities for the coming years. Maybe it sounds like overkill, but I think that's the scale we have to think on when taking on subjects like this.

**Comment by AXGKl** [comment]
@JdeH : Regarding **Prios**: Yes, I thought that it can't be wanted that I could assign the prio, will result in a total mess by definition due to the simple fact that prios change (literally) all the time alone for one prio owner.   Left it set to demonstrate that I could do it for you to know that its possible.

For issues clearly touching CI only, I think I can keep the prios in my head, if not I'll ask you to create a CI prio namespace then.
-----

**Comment by JdeH** [comment]
For CI the prio's should be your prio's. So propose a prio for any CI items and I almost blindly follow them.

**Comment by RCL-Carl** [comment]
I think these are all reasonable responses. Again, I wasn't trying to suggest that we attack this immediately. Merely musing that there may be a more general way to approach modules that might make them more flexible.

**Comment by JdeH** [comment]
You were clear about that, and it's good to start and maintain a thinking process about these things. For me it always takes time to integrate it all in my mind. I find it very hard not to overlook things. The way to go with infratructure, I guess, is to have a clear final goal and, in to some detail, a route in mind, but dividing it in small steps that are in itself rewarding. So indeed lets take our time on this one.

**Comment by RCL-Carl** [comment]
> This is something to guard like a fox terrier... I've seen that recently the minified downloads have grown from 19k to 23k. Anything upto 50k is no problem, but still I really want to keep a brake upon this as much as reasonable.

I agree that this is a major concern. From my research in other similar types of projects, many of them require very long load times. In my opinion, this is a deal breaker. I think there are many solutions to this. One is to carefully select what code is generated and included in the core/libraries as you have described. In reality, this will always be the case. There are other tools though that can amplify this diligence.

> One design decision taken early on in the development of Transcypt is to go for 'joined minification' rather than 'per module minification'.

I'm curious, in your experience, how much of a difference does "application wide" minification make compared to "per module" minification?

> Transcrypt currently uses cascaded sourcemaps, enabling a dev to debug minified target code from the Python source.

I had not considered source maps at all. I'll have to investigate a little more how requirejs handles that.

**Comment by JdeH** [comment]
@RCL-Carl:

I do not know exactly what difference application-wide minfication makes, because currently Google Closure just can't do this properly. Whenever I set a higher compression level than the most basic one, it starts to make semantical errors in the minified code. But it's at least a year ago I tried. Of course it is a matter of size of the API versus size of the 'internals' of a module. I expect it's currenly only about 20%-30% for a module with source code of ca. 5kB and no external libraries, but I didn't measure this.

It becomes more interesting if Google can be config'ed on such a compression level that it will leave out unused code in an application. That should really make a big difference for e.g. a bulky library fabric.js, of which only a small part is used, but also still a considerable difference for \_\_builtins\_\_. My assumption is that at some point someone will indeed make a minifier that understands JS well enough to leave out "dead code" for a particular app. Two years ago there was some talk that Google Closure could do this, but in my experience it can't yet. If that happens joined minification can easily shrink a program from 150kB to 20kB, e.g. the pong demo, currently carrying the dead weight of the whole fabric.js library.

Of course fabric isn't needed for this simple demo, and of course you can download taylored versions of fabric and other libs, but dead code removal should be able to do a far better job. So, just as with convergence between JS and Python, this is a long term direction that doesn't yet pay off.
