### ISSUE TITLE
is it possible to convert code with numpy and scipy library?

### ISSUE THREAD

**Issue by Erichliu00** [QQuick/Transcrypt#246]
After searching document, i am not sure if it possible to convert with numpy and scipy library. 
For numpy, i import it as `import numpy as np` and use some functions: 
`np.random.permutation()`, `np.multiply()`,`np.matmul()`, `np.hstack()`,`np.mean()`;
For scipy, i use it to io file.

**Comment by geatec** [comment]
Hi,

Numpy and Scipy are both written in C(++) and unfortunately cannot be used from Transcrypt. A start has been made with a port of a small part of Numpy to Transcrypt. It is called Numscrypt and currently can already do some of the things you mention. Numscrypt will be expanded in the near future,  but it will always be more limited than Numpy. Scipy is not yet on the agenda.

Numscrypt has not been tested with the newest release of Transcrypt. Should you encounter any problems with it, let me know, so that I can bring it up to date.

[https://github.com/QQuick/Numscrypt](https://github.com/QQuick/Numscrypt)

Kind regards
Jacques
