### ISSUE TITLE
Conflict using multiple independent javascript files in one page

### ISSUE THREAD

**Issue by pjbonestroo** [QQuick/Transcrypt#247]
I have 2 independent javascript files, both generated by Transcrypt. Using them in one single page gives me a problem. It gives the error **Cannot redefine property: format**.
It redirects me to the line:
`Object.defineProperty (String.prototype, 'format',` ...
The property **format** on the String prototype cannot be defined twice.

How to solve this problem?
Is the only possible solution to merge the two files, or are there other possibilities?

Edit:
I changed the transcrypt file **__builtin__.mod.js** and added a check:
```
if(!String.prototype.hasOwnProperty('format')){
    Object.defineProperty (String.prototype, 'format', {
    ...
}
```

and:
```
if(!Function.prototype.hasOwnProperty('__setdoc__')){
    Object.defineProperty (Function.prototype, '__setdoc__', {value: __setdoc__, enumerable: false});
}
```

After recompiling my python files it worked as I hoped for.
Can this idea be used for the next release?

**Comment by AXGKl** [comment]
Hi,

you don't have to merge the 2 files but you can import the second within the first (just like with real python) - and therefore have everything available by just transpiling one file, the first.

Is this feasible for you?

**Comment by pjbonestroo** [comment]
I would like to have 2 separated javascript files, since it are 2 independent 'applications'. On the most paged in my web-application I only need 1 of the 2 files. But on one page I need them both. And then the conflict occurs.

I think it is valuable to have the possibility to use multiple javascript files on one page, all independently transpiled by Transcrypt. In this way it is better possible to serve the development of javascript libraries.

One of the FAQ on the Transcrypt page asks:
Can I write libraries in Transcrypt and distribute them in the Javascript world?
Answer: Sure you can, without restriction.
I think this should be reconsidered because of what I said above.

I think the **Object.defineProperty** on **String.prototype** and **Function.prototype** should first check if it is possible. If not, you might assume that there is already a transpiled javascript file, and it does not need to be done again.

Best regards

**Comment by AXGKl** [comment]
Hi, thanks, I think I understood your use case.  Allowing to have the transcrypt core evaluated twice does have many problems though, even if you bypass the global overloads via a check. The biggest is the double shipping of transcrypt core to the browser.

I suggest to consider one of these options:

1. On the page where you need both modules you set, in javascript, a global variable like `load_mod2 = true' - and check that in the main module like:  `if load_mod2: import mod2`. If you don't like to change the main module then do it in an umbrella file like "app.py" where you import page modules conditionally, dependent on page setup. 

2. If you look into the `__javascript__` folder you see that transcrypt produces TWO files for one python source file: e.g. "mod2.js" and "mod2.mod.js" for "mod2.py".
The ".mod" file does *not* contain the transcrypt core and can be imported on your second page, w/o the overload problem when running the core twice. 

This second file imho justifies the statement on the FAQ: If you already have a full transcrypt module in your page: Just download the ".mod". Otherwise include the full ".js" file in your page - with same results.

Let me know if this works for you.

**Comment by pjbonestroo** [comment]
Thanks for your detailed answer!
I already tried the second option you mentioned, by using "mod2.mod.js". But it doesn't seem to work for me. But "mod2.mod.js" is not from a single python file, but also uses `import`, and so calls the method `__nest__` in javascript. I get the error `Uncaught ReferenceError: __nest__ is not defined`.
Am I doing something wrong?

**Comment by AXGKl** [comment]
> Am I doing something wrong?

funny - I get the same error now => I beg a pardon for my suggestion nr2.
What really really puzzles me is that I actually tried it before writing my answer to you (because I never used the '.mod' files directly, so I had to try) and it worked(!) - but now I see same probs like you, even w/o a subsequent import in the second module (__nest__ not defined or __pragma__ not defined). Strange.

=> @JdeH: When you are back from holidays, can you tell us if it is possible to use the xyz.mod.js files loaded standalone, via script tags? Or any other possiblity to use their code w/o shipping and evaluating the full transcrypt core twice but also w/o having to touch other modules?

**Comment by pjbonestroo** [comment]
Ok. I now have made a solution manually.
I first made an empty python file called **transcrypt_core.py** and compiled it to **transcrypt_core.js**. Then I removed the first line and the last few lines in the javascript file manually, to have all functions like `__nest__` and `__class__` globally available.
This file I added to my html page, before loading `mod1.mod.js` and `mod2.mod.js`.
It is just a workaround to show that it is possible.
Best regards

**Comment by AXGKl** [comment]
Hi, thats actually very nice and maybe a step towards 'hot module (re)loading' which a few people requested already. 
Thanks for that, lets see if @JdeH decides to include a compile switch or sth like that to support your use case "officially".

**Comment by pjbonestroo** [comment]
Unfortunately, I think my solution isn't complete and ready to support.
When I add an import to mod2.py, to include mod2a.py, it doesn't work.
Still I think these problems can be solved, to get more flexibility in creating independant libraries. I need to find out how.

**Comment by pjbonestroo** [comment]
> Allowing to have the transcrypt core evaluated twice does have many problems though, even if you bypass the global overloads via a check. The biggest is the double shipping of transcrypt core to the browser.

@AXGKl 
After thinking about it, I still don't understand why bypassing the global overloads is not a good solution. Imagine you have two totally independant (Transcrypted) libraries, from different providers, and you want to use them on the same page.
Since the transcrypt core isn't big compared to the applications itself, it is not a problem, right?

**Comment by AXGKl** [comment]
Hi @pjbonestroo, after
- my problems yesterday downloading and using a mod2 independently and
- understanding again that the apps would otherwise really be nicely isolated against each other namespace wise
I begin to get second thoughts as well about that "_totally_ decoupled" scenario.

@JdeH: If  you don't see other  reasons against it I support @pjbonestroo's suggestion, i.e. to prevent double overloads by a check.
Further rationale: Even if we do support e.g. a compiler switch in the future, allowing for a global transcrypt core / dependent module architecture we'll always support the current way of doing things as well, i.e. the all in one approach -> people will run into @pjbonestroo's problem, which seems easily preventable and the rest  seems to work as expected, w/o the standalone apps tapping on each other's toes ?

Or do we both not see the obvious way to do it?

**Comment by JdeH** [comment]
@pjbonestroo 

With regard to:

> One of the FAQ on the Transcrypt page asks:
> Can I write libraries in Transcrypt and distribute them in the Javascript world?
> Answer: Sure you can, without restriction.
> I think this should be reconsidered because of what I said above.

You're right, only one library generated from TS can be loaded at a time.
Moreover, modifying JS primitives is on one hand a hack, on the other hand the only way to make things fast, so it's a price that is paid deliberately.
The consequence is that Transcrypt couldn't cooperate with libs using the same kind of hack, which should be in the FAQ, I'll add it.
This problem is currently not pressing and can be solved by user defined aliases if it becomes a problem.
This would require a modification to the compiler but is doable in my view, it is not fundamentally different from other name clashes solved by aliases. Only now the 'clashee' comes from another lib, not from JS itself.

Using this trick for TS versus TS would be needlessly inefficient. I like the checks proposed by @pjbonestroo better.

@pjbonestroo @AXGKl 

Then about separately loading libs.
The desire has been expressed by several people to have hot module loading.
It was postponed for a significant period since it's really a major reorganisation, influencing e.g. sourcemaps in a very hairy way. Honestly this is so complex that I want to be very careful not triggering the "second system" effect. Still Pareto's rule is pervasive design paradigm in the whole of TS.

But preventing double 'enrichment' of primitives like @pjbonestroo proposes would take most pain out of the problem. It would allow coexistence of several libs generated from TS. Indeed the core would be doubly included.

In practice this wouldn't be a big problem.

TS is primarily meant for complex single page apps.
To sprinkle some code, JS is OK.
To sprinkle much code, the overhead of double inclusion would be relatively small.

By the way there is a trick that I used for the turtle graphics demo, I've mentioned it before I think. Indeed user code is load dynamically there. But it is too hackish to become an official part of TS.

For now the checks proposed by @pjbonestroo seem the most sensible thing to do.
In this way JS libs with TS source will be fully self contained, avoiding versioning problems.
Since TS is still fully evolving, such versioning problems would be severe in practice.

If we ever embark on independent module loading, some standards will have to be established quite firmly. Altering certain things will have consequences comparable to the JS version circus, including things like polyfills.

For now I think we have to keep it simple.
So I will make a stab at the checks.

KR
Jacques

**Comment by pjbonestroo** [comment]
@JdeH 
> To have two TS libs loaded on the same page would require them to be compiled with the same or at least compatible TS versions.

I think the need for compatibility is not really painful, since it is only needed for the functions for which the checks are performed, i.e. the `String.prototype.format` and the `Function.prototype.__setdoc__`

> Still I'd like to stress that TS is primarily meant for statefull single page apps.

I agree that TS is primarily meant for statefull single page apps. But I really like the possibility to have 2 separated libraries, both generated with TS on one single page. I have a use case which I unfortunately cannot share. It is a web application which holds one small library which I use on many pages, and one large library (with a lot of calculations, etc) which I use on only one page.

Kind regards,
Pieter Jan

**Comment by JdeH** [comment]
Hi,

Fixed and committed.
Test is in transcrypt/development/manual_tests/incidental_tests/conditional_property_def
Let me know it it works for you.

    // Conditional property installer function, prevents redefinition of properties if multiple Transcrypt apps are on one page
    var __setProperty__ = function (anObject, name, descriptor) {
        if (!anObject.hasOwnProperty (name)) {
            Object.defineProperty (anObject, name, descriptor);
        }
    }
    __all__.__setProperty__ = __setProperty__
    

KR
J

**Comment by JdeH** [comment]
@pjbonestroo 

The versioning problem is a bit more severe, though not more severe than e.g. with JQuery versions.
It doesn't only occur at call locations of __setProperty__. A fragment like

    String.prototype.capitalize = function () {
        return this.charAt (0).toUpperCase () + this.slice (1);
    };

also requires compatibility.

But since its semantics are defined by CPython, I think it's a manageable problem.

**Comment by pjbonestroo** [comment]
@JdeH 
You're right, I forgot about that.
Thanks for your help on this issue, and the great work for Transcrypt.

**Comment by JdeH** [comment]
@pjbonestroo 
And thanks for contributing this fix! The only thing I did is put it in a function.
