### ISSUE TITLE
No support for __lshift__ or __or__ overloading (and related operations)

### ISSUE THREAD

**Issue by RunasSudo** [QQuick/Transcrypt#249]
Using the following code, for example:

```python
 __pragma__('opov')
a = 7
b = a + 7
c = a - 9
d = a << 4
e = a | 3
```

Generates the following code snippet on 3.6.3:

```js
var a = 7;
var b = __add__ (a, 7);
var c = __sub__ (a, 9);
var d = a << 4;
var e = a | 3;
```

As you can see, the `+` and `-` operations have correctly been converted to use overloading-aware code, and replacing `a` with an object with overloaded operators, the `__add__` and `__sub__` functions are called correctly.

However, the `<<` and `|` operations are not replaced with overloading-aware versions, and hence `__lshift__` and `__or__` are not similarly called. I presume this problem also exists for other operators, too.

**Comment by JdeH** [comment]
Hi,

(Status: added and commited)

In order to keep Transcrypt lean, initially only the arithmetic operators were overloadable, since there was a clear usecase (NumScrypt).

Since it doesn't make the \_\_builtin\_\_ module much larger, I've added the bitwise ops.
Hopefully this covers your usecase, if not let me know.

In general Transcrypt tries to follow Pareto's rule: A reasonable balance between cost and benefit.

An explicit priority of Trancrypt is to keep it lean and mean. This means it'll never be as complete as CPython. Other projects (Brython, PyPyJs, Skulpt, Rapydscript) strike a different, balance.

What's best depends on what you need it for. I hope Transcrypt with this addition suits your needs.

The following code, which is part of the operator_overloading testlet, exercises the overloaded bitwise ops.:
```

    bitwise = Bitwise ()
    
    __pragma__ ('opov')
    
    bitwise << []
    [] << bitwise
    autoTester.check (32 << 2)
    
    bitwise >> []
    [] >> bitwise
    autoTester.check (32 >> 2)
    
    bitwise | []
    [] | bitwise
    autoTester.check (1 | 4)
    
    bitwise ^ []
    [] ^ bitwise
    autoTester.check (11 ^ 13)
    
    bitwise & []
    [] & bitwise
    autoTester.check (12 & 20)
    
    __pragma__ ('noopov')

    autoTester.check (32 << 2)
    autoTester.check (32 >> 2)
    autoTester.check (1 | 4)
    autoTester.check (11 ^ 13)
    autoTester.check (12 & 20)

```

Thanks for the feedback!
Jacques
