### ISSUE TITLE
Programmatically setting module variables

### ISSUE THREAD

**Issue by AXGKl** [QQuick/Transcrypt#251]
Hi, connected to https://github.com/QQuick/Transcrypt/pull/250 I had trouble to programmatically populate module variables. Do I miss sth.?

In CPython I would do sth like:

```
for key, value in some_dict.items():
      globals()[key] = value
```

on module level, but I understand that supporting `globals()` in general would be very hard due to runtime versus transpile time problems. Nevertheless I think allowing dynamic module level vars *somehow* would be appreciated by people, if its not too hard.

E.g. by supporting  sth like: `setattr(__mod__, key, value)` , that afaik would not involve too much hassle(?)

**Comment by JdeH** [comment]
Fixed and committed.
Test is in transcrypt/development/manual_tests/incidental_tests/conditional_property_def
Let me know it it works for you.

KR
J

**Comment by JdeH** [comment]
BTW, seems we're about to get some exposure at the next edition of 'Python in a Nutshell:

[https://www.safaribooksonline.com/library/view/python-in-a/9781491913833/ch01.html#idm140040762534496](url)

**Comment by AXGKl** [comment]
really really great. Transcrypt being the one and only pick, amazing.

**Comment by JdeH** [comment]
Hi,

The `globals ()` thing was actually quite hard.
I think the main functionality is captured now.

Very brief:

In the same module:
   -  globals () can retrieve all vars, wether created via globals () or in the normal way
   - vars created via globals () can only be retrieved by globals (),  not as a normal var

From a different module:
   - globals () can retrieve all vars, wether created by globals () or in the normal way
   - vars created by globals () can retrieved by globals (), but also as a normal var

Since imports are done (statically) at compile time, from ... import * will not include the vars created (dynamically) via globals ().
You can however import the whole module, e.g. `import <longName> as <shortName>` and then use `<shortName>.<dynamicallyCreatedVar>`.

There's a globals_function testlet that shows what it can do (and hopefully implicitly what not).
I'll pay some more attention to its limitations in the docs.
The code of the testlet is as follows;

Main module

```
from globals_function import sub

xxa = 'mainXxa'
xxb = 'mainXxb'

for name in ('xxp', 'xxq'):
    globals () [name] = 'main{}'.format (name.capitalize ())    
    
def f ():
    for name in ('xxr', 'xxs'):
        globals () [name] = 'main{}'.format (name.capitalize ())
        
def run (autoTester):
    f ()                 # All vars of main added
    sub.run (autoTester) # Shouldn't override vars of main
    
    autoTester.check ('Check main 1', xxa, xxb)
    autoTester.check ('Check main 2', * [globals () [name] for name in ('xxa', 'xxb', 'xxp', 'xxq', 'xxr', 'xxs')])
    autoTester.check ('Check main 3', sub.xxa, sub.xxb, sub.xxp, sub.xxq, sub.xxr, sub.xxs)
    autoTester.check ('Check main 4', * sorted ([value for key, value in globals () .items () if key.startswith ('xx')]))
```

Sub module

```
xxa = 'subXxa'
xxb = 'subXxb'

for name in ('xxp', 'xxq'):
    globals () [name] = 'sub{}'.format (name.capitalize ())

def f ():
    for name in ('xxr', 'xxs'):
        globals () [name] = 'sub{}'.format (name.capitalize ())
        
def run (autoTester):
    f ()
    autoTester.check ('Check sub 1', xxa, xxb)    
    autoTester.check ('Check sub 2', * [globals () [name] for name in ('xxa', 'xxb', 'xxp', 'xxq', 'xxr', 'xxs')])
    autoTester.check ('Check sub 3', * sorted ([value for key, value in globals () .items () if key.startswith ('xx')]))

```

I also attempted some trickery with eval `('var a = 3')` and `eval ('a')`, but this:

- Cannot be done in strict mode, since creating vars via `eval ()` is prohibited, as it would destroy performance.
- Cannot be done inside a function, since `eval ()` would create something function-local, rather than module-local.
- Introduces the risk of breaking lots of user code in the future, since browser manufacturers have proven to be very rude at deprecating stuff that many, many developers depend on.

So I prefer keeping it on the safe side and again following mr. Pareto.

@AXGKl : I sincerely hope this covers your usecase...

KR
Jacques

**Comment by AXGKl** [comment]
absolutely amazing. thanks !!
