### ISSUE TITLE
WebGL gl.clear() broken?

### ISSUE THREAD

**Issue by johanfforsberg** [QQuick/Transcrypt#254]
I ported a simple WebGL example to Transcrypt (see below), to try it out, and it just worked! Apart from one detail; seems like the gl.clear() call is somehow not translated properly, as it gives the following error in Firefox: 
```
TypeError: gl.py_clear is not a function
```
Commenting the line out makes the example work. I don't know why, but I'm guessing that Transcrypt can not actually know of the entire browser API and therefore makes some assumptions of what's a javascript call, and misses this one.

```python
from org.transcrypt.stubs.browser import document, __new__


def make_shader(gl, vs, fs):

    prog = gl.createProgram()

    def add_shader(type_, source):
        s = gl.createShader(gl.VERTEX_SHADER
                            if (type_ == 'vertex')
                            else gl.FRAGMENT_SHADER)
        gl.shaderSource(s, source)
        gl.compileShader(s)
        if not gl.getShaderParameter(s, gl.COMPILE_STATUS):
            return
        gl.attachShader(prog, s)

    add_shader('vertex', vs)
    add_shader('fragment', fs)
    gl.linkProgram(prog)
    if not gl.getProgramParameter(prog, gl.LINK_STATUS):
        raise RuntimeError("Could not link the shader program!")

    return prog


def attribute_set_floats(gl, prog, attr_name, rsize, arr):
    gl.bindBuffer(gl.ARRAY_BUFFER, gl.createBuffer())
    gl.bufferData(gl.ARRAY_BUFFER, __new__(Float32Array(arr)),
                  gl.STATIC_DRAW)
    attr = gl.getAttribLocation(prog, attr_name)
    gl.enableVertexAttribArray(attr)
    gl.vertexAttribPointer(attr, rsize, gl.FLOAT, False, 0, 0)


def draw():
    gl = document.getElementById("webgl").getContext("webgl")
    gl.clearColor(0.8, 0.8, 0.8, 1.0)  
    gl.clear(gl.COLOR_BUFFER_BIT)  # <- error!

    prog = make_shader(gl,
                       ("attribute vec3 pos;"
                        "void main() {"
                        "    gl_Position = vec4(pos, 2.0);"
                        "}"),
                       ("void main() {"
                        "    gl_FragColor = vec4(0.5, 0.5, 1.0, 1.0);"
                        "}"))

    gl.useProgram(prog)

    attribute_set_floats(gl, prog, "pos", 3, [
        -1, 0, 0,
        0, 1, 0,
        0, -1, 0,
        1, 0, 0
    ])

    gl.drawArrays(gl.TRIANGLE_STRIP, 0, 4)


draw()
```

```html
<!DOCTYPE html>
<html>
    <head>
	<meta charset="utf-8" />
	<title>Example</title>
    </head>
    <body>
        <canvas id="webgl" width="640" height="480"></canvas>
        <script type="text/javascript" src="__javascript__/webgl.js">
        </script>
    </body>
</html>
```

**Comment by JdeH** [comment]
Hi,

The name 'clear' is an aliased name, since otherwise it would conflict with Python dictionary 'clear' method, that receives special treatment by Transcrypt to allow arbitrary dictionary content.

(Transcrypt has no means of predicting the type of an object or variable since Python is dynamically typed.
If you use 'js_clear' instead, it should work.

So:

`gl.js_clear(gl.COLOR_BUFFER_BIT)`



An alternative is to 'unalias' that name, but I would advise against that as a habit.

All aliases are listed in;

[http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/special_facilities.html#pragma-alias](http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/special_facilities.html#pragma-alias)

Also explained there is how to unalias a name.

**Comment by JdeH** [comment]
By the way, if you are a member of StackOverflow:

This is a question that could benefit other users running into the same problem.
Not everyone uses GitHub, many people just pip-install.
If it's not too much work, could you copy your question there.
I'll copy the answer as well, so that other people can easily find it.
No obligation of course!!

**Comment by johanfforsberg** [comment]
Thanks for the quick reply!

I verified that it works, and I can definitely live with the workaround. 

I guess this kind of problem is likely to appear elsewhere too. Is this something that might be possible for the compiler to warn about, if it can't be "fixed"? It's a pretty small issue but can be annoying to figure out.

Anyway, I think transcrypt is a very neat project which I'm going to play around with further! Here's the SO question: http://stackoverflow.com/questions/41535146/webgl-clear-issue

**Comment by JdeH** [comment]
Unfortunately, since Python is dynamically typed, the compiler cannot tell whether <something>.clear () correct or not.

Take a loop like like:

```
for anObject in aList:
   andObject.clear (aParameter)
```
Where aList may contain gl objects as well as dict instances.
The compiler cannot predict what it will encounter.
Hence unfortunately it cannot tell wether or not 'clear' is corrrect.
It only discovers at runtime and the contents of aList may vary from run to run.

The only way around this is static typing.

**Comment by JdeH** [comment]
Things like this should become part of a troubleshooting list in the docs.
