### ISSUE TITLE
Autotest for regular expressions has fallen over

### ISSUE THREAD

**Issue by JdeH** [QQuick/Transcrypt#259]
Today I discovered that the re autotest isn't yet part of the shipment test.

When I ran it separately, there were some errors. Are these just things that are not yet implemented and should I outcomment them, or has something fallen over indeed.

@RCL-Carl @GULPF Since you're more familiar with this code, could any of you give me a hint.
Probably I should add a command line switch or something?
I'd like to make the re autotest part of the shipment and CI tests!

KR
Jacques

![re_err](https://cloud.githubusercontent.com/assets/1730289/21815738/ff85824e-d75d-11e6-89be-723d7e36ed8f.png)

**Comment by RCL-Carl** [comment]
Yes - that test has never been fully passing. There is a bug in the translation of conditional groups in the python regex to the javascript regex. The translation works but the number of groups detected is much larger than the python conditional regex would predict. In the closed issue thread (Issue #98), there are some comments by @GULPF about what could info could be used to fix it. I have not had the time to look at the problem recently due to other commitments.

**Comment by JdeH** [comment]
Well, seems I was to quick with #98, should have read better...

For now I'll outcomment the offending tests, since having most of re in the regression test suite will prevent things falling over that first worked.

I'll reopen the original issue and close this one.

KR
K
