### ISSUE TITLE
Failed to find module

### ISSUE THREAD

**Issue by artelse** [QQuick/Transcrypt#265]
Have seen more problems with module loading, but haven't found a solution. When it try to transpile with `transcrypt -b driver.py` I get this error:

```
Error in program driver.py, module _socket, line 49:
	Attempt to load module: _socket
	Can't find any of:
		/Users/x/develop/path/__javascript__/_socket.mod.js
```
It seems to balk on an `import socket` or on another file it falls over `import struct`. Any ideas how to resolve?

**Comment by JdeH** [comment]
Hi,

It seems that module driver.py uses a module called _socket that indeed it can't find.
I don't know exactly what the problem is since I am not familiar with those modules but note the following:

- Transcrypt doesn't come with the usual set of standard libraries (with some exceptions like math, cmath,, random, itertools, loggin, re). Instead it is able to use any JavaScript library.

- Libraries written in the (quite large) subset of Python that Transcrypt supports can be used and of course you can write sucg libs yourself.

- Transcrypt cannot use any libraries written in C(++), or libraries using other libraries written in C(++). This is because running C++ in the browser (using something called emscripten) would result in exceedingly large downloads.

So what you've bumped into is a limitation. In most cases using JS libraries is the best thing to do, but some libs are hard to replace by JS equivalents.

Kind regards
Jacques

**Comment by artelse** [comment]
Thanks for the explanation on inherent limitations.
