### ISSUE TITLE
from x import y statements cause errors when used within a function

### ISSUE THREAD

**Issue by daboross** [QQuick/Transcrypt#269]
I believe this is due to Transcrypt trying to export modules imported only within a specific function?

Test code: `inner/__init__.py` is empty.

`inner/moda.py`:

```python
from inner import modb

def modafunc():
    return "stuff"


def both():
    return modb.modbfunc()
```

`inner/modb.py`:

```python
def modbfunc():
    from inner import moda
    return moda.modafunc()
```

`main.py`:

```
from inner import moda

print(moda.both())
```

Output:
```
/home/daboross/Projects/Python/TranscryptTest/target/main.js:2080
						__all__.moda = moda;
						               ^

ReferenceError: moda is not defined
    at Object.__init__ (/home/daboross/Projects/Python/TranscryptTest/target/main.js:2080:22)
    at __init__ (/home/daboross/Projects/Python/TranscryptTest/target/main.js:42:28)
    at Object.__init__ (/home/daboross/Projects/Python/TranscryptTest/target/main.js:2047:17)
    at __init__ (/home/daboross/Projects/Python/TranscryptTest/target/main.js:42:28)
    at /home/daboross/Projects/Python/TranscryptTest/target/main.js:2088:14
    at main (/home/daboross/Projects/Python/TranscryptTest/target/main.js:2096:5)
    at Object.<anonymous> (/home/daboross/Projects/Python/TranscryptTest/target/main.js:2099:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

Generated `main.js`: https://gist.github.com/daboross/2ae5db3f25356372c00253f551c93754

This does not occur if `moda.py` and `modb.py` are top-level modules, and only `import modb` is used. However, with that setup, `moda` is still exported, just as an empty object!

**Comment by JdeH** [comment]
Hi David

Because Transcrypt is precompiled rather than interpreted, all imported modules have to be known statically at compilation time, so they will be included in the generated JS.

This means that module imports cannot take place in a function, since they then should only occur when that function is called, which is determined at runtime rather than compiletime.

The Transcrypt differs from the CPython mechanism in the following aspects:

- Since imports are resolved during one-pass compilation they have to be at global level, preferably at the start of a module.
- Conditional imports can be achieved using the __pragma__ ('ifdef', <symbol>) family of pragmas, which do their work compile time rather than runtime, just like C++'s #ifdef macros.
- Imports cannot be cyclic.
- Before searching for globally available modules (that are also available to CPython, that is), Transcrypt will first search the "modules" directory of the Transcrypt installation directory. In that way Transcrypt can have special inplementations of modules that CPython has as well. If you e.g. import math, it will import the Transcrypt math, rather than the CPython math. The same holds e.g. for re, which under the hood uses JS regexes, rather than CPython regexes written in C++. The user doesn't have to do anything special to get these Transcrypt compatible standard lib modules.

Kind regards
Jacques

**Comment by daboross** [comment]
Thank you for the detailed information!

With this architecture, it makes complete sense to not allow cyclical imports that are at a module-level, however, I would think that it should be technically possible to allow cyclical imports when one of them is within a function - or at least allow imports within a function that aren't cyclical.

The original case I ran into this did not have any cyclical imports, and was simply using `from x import y` inside of a function to avoid polluting the module's namespace. While testing to see what the cause was however, I saw that the above code (with cyclical imports) does actually work if both modules are top-level, and `import y` is used instead of `from x import y`.

The following code:

```python
import modb

def modafunc():
    return "stuff"


def both():
    return modb.modbfunc()
```

```python
def modbfunc():
    import moda
    return moda.modafunc()
```

Works correctly, and allows cyclical imports, generating the following: https://gist.github.com/daboross/fa97d5c3312b135aedbd8b99f5782fc3


I believe if line 2080 in the original gist were removed, the original code would also work correctly, and allow cyclical imports. It's the only line which is erroring, besides that the cyclical import should not actually cause an error since both modules will have been initialized when moda requests modb inside the function. Line 2080:
```javascript
	__all__.modbfunc = modbfunc;
```

**Comment by daboross** [comment]
If it doesn't break anything else, the PR I submitted should fix this issue.

**Comment by JdeH** [comment]
Both your diagnosis and your proposed solution are right.
Importing inside a function prevents endless recursion at initialisation.
And indeed, since the imported names are local to the function, they shouldn't be exported, which can be done by a scope check.

**Comment by daboross** [comment]
Thanks!

**Comment by boxed** [comment]
I seem to have hit this problem, even though this ticket seems to imply it's fixed...
