### ISSUE TITLE
Multiplicating a list results in NaN

### ISSUE THREAD

**Issue by sebnozzi** [QQuick/Transcrypt#281]
It seems that duplicating a list through multiplication (e.g. `[1,2,3] * 2` which in Python normally results in `[1,2,3,1,2,3]`) does not work as expected.

I tried this:
```
x = [1,2,3] * 2
print(x)
print(x == [1,2,3,1,2,3])
```

This was the result on the JavaScript console:
```
NaN
False
```

**Comment by sebnozzi** [comment]
This might be related to issues #264 and #276 ... ?

**Comment by JdeH** [comment]
This requires operator overloading to be enabled.
You can do that globally with a command line switch,
but it's better to do it locally through the use of pragma's,
like in the code below:

```
__pragma__ ('opov')

x = [1,2,3] * 2
print(x)
print(x == [1,2,3,1,2,3])

__pragma__ ('noopov')
```

which prints:

```
[123123]
True
```

The reason to make operator overloading optional is found here:

`http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/special_facilities.html#operator-overloading-pragma-opov-and-pragma-noopov`

Note that since Python has dynamic typing, it can fundamentally not be established in advance whether a variable contains e.g. a number, a matrix or a list. It may hold different types at different times. Generating function calls for a + b where a happens to be 1 and b happens to be 2 would be slow and bulky.

**Comment by sebnozzi** [comment]
Ok, thanks. Good to know.

While we are at it, is this also related to a feature having to be enabled?

```
my_map = {}
my_map[(1, 2)] = 'blah'
```

On the JS Console:
```
Uncaught TypeError: my_map.__setitem__ is not a function
```

Do I have to enable something in order for this to work?

Thanks in advance.

**Comment by JdeH** [comment]
No, it isn't.
Currently dicts are just JS objects, so the following:

```
d = {}

v = 'key1'
def f ():
    return 'key2'

d ['key0'] = 1
d [v] = 2
d [f ()] = 3

print (d)
```

will generate

```
		var d = dict ({});
		var v = 'key1';
		var f = function () {
			return 'key2';
		};
		d ['key0'] = 1;
		d [v] = 2;
		d [f ()] = 3;
		print (d);

```

While it would be quite possible to support (1, 2) as key by adding __setitem__ and __getitem__ members to class dict and convert (1, 2) to key string '(1, 2)', this wasn't done because it would be slow and doesn't fit the way JS objects and attributes are used. 

In the transition from JS5 to JS6 the type Map has been added, that supports keys like (1, 2) natively. An option is planned to choose between JS Maps (compound keys allowed and sensible) and plain JS objects (string keys). The default will be plain JS objects to achieve good interop with JS libs and JSON like notation. The option, controlled by a switch as well as a pragma, will be use Maps and allow (1, 2) as key.

So

**Comment by JdeH** [comment]
Added and committed
