### ISSUE TITLE
Python interpreter layer

### ISSUE THREAD

**Issue by punkdit** [QQuick/Transcrypt#303]
I've had a somewhat curious idea that I'd like to share...

A number of people have commented on the lack of various python features in transcrypt, such as % string formatting. However, it is clear that Jacques has a specific direction for transcrypt that involves being small and fast, and so this excludes the addition of these features. On top of this, there are "semantic" issues, such as the empty list being True in an if-statement.

As far as I can tell, transcrypt can be seen as syntactic sugar on top of javascript. This sugar looks like python, but it is not really the same thing. It's another language, "transcrypt".

So my proposal is to write an actual python interpreter, in the transcrypt language. This interpreter would accept python bytecode and run the opcodes as they should be run, and forget about being fast or small. Sometimes we don't care about those things, and would just like to run a bit of python code in the webbrowser, no matter how slow it is. One may be concerned that this would lead to a big download of a python runtime, but it may not be so bad as that.

This approach is similar to how the pypy project works. There is a "restricted" version of the python language (rpython) that is compiled to various targets (asm, c, etc.) And then using this language they implement a real python interpreter, that handles opcodes, objects, etc.

Finally, an idea from the cython community. This is a way of gaining some speed, at the cost of a larger code-blob, and that is to "unroll" the python bytecode into the corresponding "object" calls. (Where these object semantics have been implemented in the transcrypt language.)

All in all, given the speed of current javascript engines, this thing might actually work well.

**Comment by JdeH** [comment]
Hi

Features missing:

- Empty list being true: This can be altered with the "tconv" switch or pragma

http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/special_facilities.html#automatic-conversion-to-truth-value-pragma-tconv-and-pragma-notconv

- % formatting not supported: A similar solution may be choosen, but it didn't seem urgent due to presence of the `format` string method. However the string formatting mini language still misses

But in general indeed, Transcrypt currently doesn't cover Python for 100%, though it covers a large part. And it will never be 100%, since things like eval and exec cannot work, since it's a compiler, not an interpreter.
As  you indicate there are contexts where speed is less important than completeness. There's a whole range of projects fitting different needs. And indeed Transcrypt is targetted towards use for production code that has to be fast and small to compete with JavaScript.

Having a Python virtual machine running in the browser can guarantee that the whole of C Python can be covered (e.g. an educational context, as targetted e.g. by Sculpt/Trinkets). However for a truly Pythonic experience, also the standard libs (many written in C) have to be converted. This means C has to be compiled to something running in the browser, e.g. asm.js or webassembly.

You mention PyPy, and there's a project doing just that:

http://pypyjs.org/

It takes a very long time to download, but if someone wants pure and complete Python, it will do the job.

You propose to write a VM in Transcrypt. I don't immediately see the advantage over PyPy.js. Can you tell me why you would favor such an approach over PyPy.js?

**Comment by punkdit** [comment]
I appreciate what you are doing, and am not wanting to argue with you about the direction of transcrypt. But, as I said above, I don't agree that all this pragma stuff is "covering" python. It is another language you are building, even though it is embedded in the python syntax.

I would hope that a smaller/lighter vm could be built on transcrypt (it's lean and fast, right?) than pypy.js which is too heavy for what I have in mind. It's hard to know without trying some experiments. I'm not looking for a pure and complete python, but something pure with well-defined boundaries.

**Comment by JdeH** [comment]
Well, it would be great if a small, fast VM could be build, so I'd certainly welcome the experiment.

As far as language conformance is involved, it isn't as with the difference between French and English but more like Cockney and High English. Could we settle for a dialect... ;)

**Comment by theodox** [comment]
If you're interested in a python VM that reads bytecode in Javascript: https://pybee.org/project/projects/bridges/batavia/

My impression is it's not particularly speedy at the moment

**Comment by JdeH** [comment]
I don't expect anything happening on this front anytime soon, so I'll close this for now.
