### ISSUE TITLE
Help request: Exception in autotest minification

### ISSUE THREAD

**Issue by Michael-F-Ellis** [QQuick/Transcrypt#307]
Just installed transcrypt.  Autotest compilation succeeds but fails at minification.  I tried updating to JRE 8, but same error.  Any advice for making it work?

Thanks!

```
$ uname -a
Darwin Michaels-Mac-mini 15.6.0 Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64 x86_64

$ python --version
Python 3.5.1 :: Anaconda 4.0.0 (x86_64)

$ transcrypt -h
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.24
Copyright (C) Geatec Engineering. License: Apache 2.0

$ java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

$ transcrypt -b autotest.py 
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.24
Copyright (C) Geatec Engineering. License: Apache 2.0

Saving result in: /Users/mellis/anaconda3/lib/python3.5/site-packages/transcrypt/development/automated_tests/transcrypt/__javascript__/autotest.js
Saving minified result in: /Users/mellis/anaconda3/lib/python3.5/site-packages/transcrypt/development/automated_tests/transcrypt/__javascript__/autotest.min.js
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

Ready

```

**Comment by geatec** [comment]
Hi

From the your console output it seems that, while you installed JRE 8, your system still uses JRE 6:

> $ java -version
> java version "1.6.0_65"
> Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
> Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

Since you'r on Apple, there should be a "system preferences" dialog. As soon as there's more than one version of the JRE on you machine, there should be an item in this dialog that allows you to change the settings for Java, including which version it will default to.


See also:

http://stackoverflow.com/questions/12770622/java-lang-unsupportedclassversionerror


You can also change these settings via the command line, see:

http://stackoverflow.com/questions/21964709/how-to-set-or-change-the-default-java-jdk-version-on-os-x


Kind regards
Jacques

**Comment by JdeH** [comment]
Hi

From the your console output it seems that, while you installed JRE 8, your system still uses JRE 6:

$ java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)
Since you'r on Apple, there should be a "system preferences" dialog. As soon as there's more than one version of the JRE on you machine, there should be an item in this dialog that allows you to change the settings for Java, including which version it will default to.

See also:

http://stackoverflow.com/questions/12770622/java-lang-unsupportedclassversionerror

You can also change these settings via the command line, see:

http://stackoverflow.com/questions/21964709/how-to-set-or-change-the-default-java-jdk-version-on-os-x

Kind regards
Jacques

**Comment by Michael-F-Ellis** [comment]
Thanks, Jacques.  The links pointed me in the right direction. I ended up fixing it by finding the new java executable and creating a symlink to it in my virtual environment. Compiling autotest.py now completes and generates a minified file.

The compilation reports a few warning that seem to be due to empty try{} statements. For example
```
						try {
						}
						catch (__except0__) {
							if (isinstance (__except0__, AssertionError)) {
								var exception = __except0__;
								autoTester.check (exception);
							}
							else {
								throw __except0__;
							}
						}                    
```

produces

```
/Users/mellis/anaconda3/lib/python3.5/site-packages/transcrypt/development/automated_tests/transcrypt/__javascript__/autotest.js:4400: WARNING - unreachable code
						catch (__except0__) {
						^
```

I'm guessing those are known and of no consequence but felt compelled to a least mention them :-)

Thanks very much for creating Transcrypt and especially for the superb documentation.  I think it may fill a need for me.  Much of my work involves embedded control systems written in Python and running on small-board systems (Raspberry Pi, BeagleBone, ...).

My clients all want web interfaces.  I've previously been using CoffeeScript for the browser side (JS is, to me, unbearably ugly) but I'd really like to code everything in Python.

Best,
Mike

**Comment by JdeH** [comment]
Hi Michael,

Since the answer to this question could help others that encounter the same problem,
if you find the time could you please ask it also on Stackoverflow (there's a [transcrypt] tag).
I will answer it there, so others can view it as well.

No obligation of course!

KR
Jacques

**Comment by Michael-F-Ellis** [comment]
Hi Jacques,
Done, just now.  Would you prefer, in general, to have usage questions (as
opposed to bug reports and/or suggestions) posted to SO?
Cheers,
Mike

**Comment by JdeH** [comment]
Thanks!

Currently Transcrypt is still relatively unknown, and "early adopters" will probably look on GitHub.
But in the long run I anticipate that there will be more people just installing it from PyPi and using it, without bothering where it comes from.

For me if I have a question about using some other language or library, I always look on SO first.
So I guess that's the place where other developers will also look if they indeed just use Transcrypt.
Posing questions on SO to me seems like one way to get Transcrypt "established".

The distinction between a question and a bug report isn't always clear, but in case of an obvious usage question, I'd indeed prefer SO for this reason. But of course questions are welcome on GitHub too.

KR
Jacques
