### ISSUE TITLE
Use external javascritp library

### ISSUE THREAD

**Issue by schef** [QQuick/Transcrypt#315]
Hi guys. Thanks for this great project.
Curently i am using
```
sound = __new__ (Audio('./tones/ogg/65.ogg'))
sound.play()
```
for adding and playing audio file.

Now i want to use external library like howler.js.
The documantation says that i should add the sound and play like this:
```
var sound = new Howl({
  src: ['sound.mp3']
});
sound.play();
```

I tried to add like this:
```
sound = __new__ (Howl({ src: ['./tones/ogg/65.ogg']}))
sound.play()
```

but for some reason it doesnt work.
I have included howler.js in script in html file.

**Comment by JdeH** [comment]
Hi,

Preferably use the followng Python syntax:

```
sound = __new__ (Howl({ 'src': ['./tones/ogg/65.ogg']}))
sound.play()
```

So with quotes around src, since it's a string literal (I'd expect).

Alternatively, if you like the (somewhat loose) quoteless JS syntax better, you may use a pragma or a command line switch, as described here:

http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/special_facilities.html#keeping-your-code-lean-pragma-jskeys-and-pragma-nojskeys

**Comment by schef** [comment]
Thanks for your anwser.
For some reason it still doesn't work.
I will try to figure it out.

**Comment by JdeH** [comment]
Maybe it helps to take a look at the generated JavaScript.
I am curious what the cause of this is.

**Comment by schef** [comment]
I found the problem. The problem is that i used old js library and was looking at new documentation. Instead of using src i had to use urls. Thanks!

**Comment by JdeH** [comment]
OK, thanks for the feedback!
