### ISSUE TITLE
Difficulty catching simple exceptions

### ISSUE THREAD

**Issue by Levtastic** [QQuick/Transcrypt#317]
```Python
mylist = []
try:
    mylist.remove('value')
except ValueError:
    pass
```
Regular python handles this correctly, ignoring the thrown error, but Transcrypt gives me an ambiguous `Uncaught exception` message with no further info. This code works fine if I catch ALL exceptions, not just ValueErrors, but I've always been of the opinion that you should only catch what you expect to be thrown, so I'd prefer to be able to specify.

Am I doing something wrong or is this a limitation of Transcrypt, to avoid having to catch and rethrow reformatted javascript exceptions all the time?

**Comment by JdeH** [comment]
Doesn't look like planned behaviour...
Will look into this a.s.a.p.
Thanks!

**Comment by JdeH** [comment]
The wrong type of exception was thrown.
This really was a bug, a fix will be in the next commit.

While this case should now work properly, note that Transcrypt in some cases relies on
the underlying JavaScript exception type, rather than converting it.
This is one place where brief code and seamless integration with JS libs is favored over 100% CPython compatibility.

KR
Jacques
