### ISSUE TITLE
hosted Sphinx documentation unavailable

### ISSUE THREAD

**Issue by dvanduzer** [QQuick/Transcrypt#319]
The online manual at http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/ has not been responding for a few days. The formatting didn't come out quite right automagically, but it was easy to build on RTD, an ad-supported doc hosting service:

http://transcrypt.readthedocs.io/en/latest/

I considered a pull request to update the URL in the README file. Will the official hosted version be back online soon?

**Comment by JdeH** [comment]
Wow, that's bad!
The provider migrated the site to a new server, with some problems evidently.
Will be solved a.s.a.p.
I'll keep you informed.

**Comment by JdeH** [comment]
Unfortunately during the migration provider alwaysdata changed its url scheme.
The docs are now hosted under the Transcrypt URL at:

http://www.transcrypt.org/docs/html/index.html

I am very sorry for the links that will have to be changed.
Since the docs are now refered from the transcrypt.org domain, this should be the first and the last time this happened...

Kind regards
Jacques
