### ISSUE TITLE
max() and min() do not accept sequences.

### ISSUE THREAD

**Issue by Michael-F-Ellis** [QQuick/Transcrypt#331]
In CPython, one can do
In [2]: max([9,10])
Out[2]: 10

or even (seldom useful)
In [3]: max(dict(a=1, b=2))
Out[3]: 'b'

but Transcrypt maps these calls to Math.max and Math.min respectively which return NaN when passed an Array.  (I haven't tested with an Object).

I was able to work around my immediate issue by replacing max(seq) with max(*seq) which generates code like 

```
max.apply (null, seq)
```

that works as expected.  Would it be difficult to imitate CPython's max() and min() by default in Transcrypt?

Thanks,
Mike

**Comment by JdeH** [comment]
Indeed these functions simply refer to the min and max of JS. Since they are used in computations, I figured that being fast here was more important than being complete, since they may be called in an inner computational loop. And most of MY use is min or max of two params. But that needn't hold for everybody.

It is very simple to replace them by something more Pythonesque. But it would be slower, since as far as I can think of, an if would be required to decide wether or not to unpack something.

I still hesitate as to what would be best. Yet another command line or pragma switch feels like overkill.  In general the defaults in Transcrypt favor speed over completeness, to make it truely useable as a production tool. I am open to any convincing arguments for one or the other.

KR
Jacques

**Comment by JdeH** [comment]
Thank you for your well motivated feedback.
I tend to follow your advice.
Still I'll leave this request for feedback open for a short while,
to see if anyone has a different, equally well motivated opinion.

**Comment by fzzylogic** [comment]
It's interesting that unlike Math.min/max, CPython doesn't accept single integers to min/max, only iterables. If we ignore that it does accept multiple iterables and don't try to support that, an interesting middle ground might be to check the number of arguments, since that can be done at compile time instead of runtime. If it's one argument, assume it's an iterable and call the appropriate function, else we're dealing with integers and can use Math.min/max as at present.

**Comment by JdeH** [comment]
@fzzylogic 

That's a fairly clever solution, but...

Python allows redefinition of min and max, even with one parameter.
Compile time discrimination would require making the distinction at the call location,
translating e.g. a single param call to e.g. max_iterable instead of max.
But with a user defined single param max, that would not work.
And at the call location the fact that there's a user defined max would be quite hard to know,
especially in a multi module situation, where imported modules may change.

So... I'm afraid this bird won't fly.
Hopefully I am wrong and overlooking something.
But in that case I need a hint as to what that something is...

**Comment by Michael-F-Ellis** [comment]
Hi Jacques,
I usually code with the 90/4 rule in mind (4% of code typically accounts
for 90% of cpu time). On that basis, it's roughly 25 to 1 that a given
instance of max() or min() will not be a bottleneck.

You've already given us an escape hatch with __pragma__('js', ...) for
cases where performance optimization is vital so I'd argue for making
builtin's like max(), min(), abs(), and sum() behave as closely as possible
to their CPython equivalents.

BTW, thanks for recommending Musée Rodin. The sculpture garden was awesome
even in the rain.

**Comment by fzzylogic** [comment]
Ouch, good point. I was interested in performance of doing something like this client side, so did some tests comparing javascript speed with python speed on the same machine. Interestingly, javascripts Math.min is faster on the same hardware than CPythons (at least in Chrome and Firefox. I haven't done this sort of thing before so i might have made mistakes). But thought the results are worth sharing. 

[JSPerf](https://jsperf.com/math-min-custom-function/1)
On this hardware, min(1, 2, 3) returns about 88mil results per second (give or take a few million depending on cpu load). Firefox claimed over 1bil per second, which i found somewhat hard to believe, especially since all the other tests had similar results.

Python tests (only about 62mil per second):
>>> import timeit
>>> a = [1, 2, 3]
>>> timeit.repeat("min(a)", "from __main__ import a", number=6200000)
[1.0061129949972383, 0.9879220160000841, 0.9880196640006034]
>>> timeit.repeat("min(1, 2, 3)", "from __main__ import a", number=6200000)
[1.0052803240032517, 0.996469805999368, 0.9960179600020638]

The simplified function also tested in the jsperf tests above (which won't parse dicts and assumes 1 arg means an iterable, so it's not correct, but covers 90%) returns about 65mil results per second on this hardware:

```
function myMin2(){
  return arguments.length == 1 ? Math.min.apply(null, arguments[0]) : Math.min.apply(null, arguments)
};
```

**Comment by Michael-F-Ellis** [comment]
"... javascripts Math.min is faster on the same hardware than CPythons ..."
Maybe not so surprising given the many person-years that have gone into
optimizing JS on major browsers like Chrome and FF.  I agree you shouldn't
believe the FF billion/sec.  It probably means the JS interpreter noticed
the result was constant and optimized the call out of existence.

**Comment by all3fox** [comment]
Since this is still open with `need: feedback`, I would say that `min` and `max` should work with sequences out of the box. I have little understanding of the `js` pragma, but looks like you can use it in those 10% of code which needs speed. Other places compatibility is key, when it is easy to have.

**Comment by abozhilov** [comment]
This depends on the target JS engine. If you want ES5 complaint code so, the preposition of @fzzylogic makes sense. If your target environment is ES6 complaint you can use spread operator similar to Python's  prefix `*`. e.g. 
```
Math.min(...iterable)
```
Same is applied for `Math.max`. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator

**Comment by faerot** [comment]
I would also vote for compatability over speed by default. It's like in the old days where you could inject asm instructions in tight loops, now you can go down to pure JS in pragmas if it is absolutely critical. I have outlined my generic thoughts on the matter here too:
https://github.com/QQuick/Transcrypt/issues/402#issuecomment-354591006

**Comment by JdeH** [comment]
OK, improved compatibility it will be.

**Comment by JdeH** [comment]
Committed, thanks @Michael-F-Ellis for bringing this up.
