### ISSUE TITLE
Callable objects

### ISSUE THREAD

**Issue by mythsmith** [QQuick/Transcrypt#339]
How am I supposed to instantiate and use callable objects?
```
class Callme(object):
	def __init__(self, a):
		self.a = a
	
	def __call__(self, b):
		return self.a, b

c = Callme(1)
console.log(callable(c))
console.log(c(2))
```
This prints:
`true`
`TypeError: c is not a function`

**Comment by JdeH** [comment]
Operator overloading is off by default for efficiency reasons.

You can activate it locally, per module or with a command line switch, see

http://www.transcrypt.org/docs/html/special_facilities.html#operator-overloading-pragma-opov-and-pragma-noopov

Since in this case operator overloading is used only in a single line, the most efficent thing would be:

    class Callme(object):
        def __init__(self, a):
            self.a = a
        
        def __call__(self, b):
            return self.a, b

    c = Callme(1)
    console.log (callable(c))

    __pragma__ ('opov')
    console.log (c(2))
    __pragma__ ('noopov')

Of course normally you would activate it in whole sections of code or even whole modules.

See also:

http://www.transcrypt.org/docs/html/supported_constructs.html#operator-overloading

By the way, the answer of this question could also help other developers, so if you find the time could you also pose it on StackOverflow, (tag [Transcrypt]).

Kind regards
Jacques
