### ISSUE TITLE
Truth value testing incorrect for empty lists/dicts

### ISSUE THREAD

**Issue by all3fox** [QQuick/Transcrypt#365]
Take a look at the following code (it creates lists, then dicts, then strings and tests them in `if`):

```
xs = []
ys = [1, 2, 3]

if []:
    print("This is a bug")
else:
    print("This is ok")

if xs:
    print("This is a bug")
else:
    print("This is ok")

if ys:
    print("This is ok")
else:
    print("This is a bug")

xs = {}
ys = {1: 2, 3: 4}

if {}:
    print("This is a bug")
else:
    print("This is ok")

if xs:
    print("This is a bug")
else:
    print("This is ok")

if ys:
    print("This is ok")
else:
    print("This is a bug")

xs = ""
ys = "hello"

if "":
    print("This is a bug")
else:
    print("This is ok")

if xs:
    print("This is a bug")
else:
    print("This is ok")

if ys:
    print("This is ok")
else:
    print("This is a bug")
```

Save it under `demo.py` and create the following `demo.html` next to it:

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
    </head>
    <body>
        <script src="./__javascript__/demo.js"></script>
    </body>
</html>
```

Now, transpile `demo.py` with either `transcrypt -b demo.py` or using EcmaScript 6 with `transcrypt -b -e 6 demo.py`. Either way, you will first see a warning:

```
__javascript__/demo.js:2461: WARNING - unreachable code
		if ('') {
		        ^
0 error(s), 1 warning(s)

Ready
```

Next, open up `demo.html` in your browser of choice and navigate to web console. There you will see a couple `This is ok` print statements as well as a couple of `This is a bug` statements. The latter ones happen when `if`-check is done on empty lists and empty dictionaries.

Is this a bug, an incompatibility or am I missing some transpilation switch?

**Comment by fzzylogic** [comment]
Hi all3fox, haven't tested your example code yet, but this may be useful to you for now:

Python's 'truthiness' for data structures like dict, set and list isn't enabled by default and globally enabling it is discouraged because of potential performance issues related to typechecking. For clarity: Under CPython, an empty dict, set or list has truth value False, whereas in Javascript it's considered 'true'.. 

Example:

```
myList = []
if myList:    # False in CPython bcs it's empty, true in javascript bcs it exists
    # do some things.

```
There are at least three ways to address this:

- Use the -t flag when converting python to javascript e.g.: $ transcrypt -t python.py (not recommended, but probably isn't a problem unless you check for truthiness many times in inner loops of performance sensitive code..)
- Use __pragma__(tconv) or __pragma__(notconv) within your code to tell the transcrypt compiler to switch on automatic conversion to python-like truth values locally.
- Instead of checking for the truth value, avoid the problem altogether by just checking len(myList) > 0... Maybe that will be fine for most situations, does the job for my light use.

**Comment by all3fox** [comment]
Oh, thank you, so I was missing a `pragma` and/or a `-t` switch then.
