### ISSUE TITLE
KeyError not raised when accessing missing dict key

### ISSUE THREAD

**Issue by serin-delaunay** [QQuick/Transcrypt#399]
I compiled this code with Transcrypt 3.6.54:
```py
try:
    {'a':5}['b']
    console.log('no problem')
except KeyError:
    console.log('not found')
```
Output code is:
```js
try {
	dict ({'a': 5}) ['b'];
	console.log ('no problem');
}
catch (__except0__) {
	if (isinstance (__except0__, KeyError)) {
		console.log ('not found');
	}
	else {
		throw __except0__;
	}
}
```
Console output should be `not found`, but instead I see `no problem`.

**Comment by mlyle** [comment]
This affects me too

**Comment by JdeH** [comment]
To allow mixing Transcrypt code with JavaScript libraries seamlessly, Python dicts are in fact JavaScript objects. So aSet ['x'] in TS is literally translated to aSet ['x'].
Since JS (wickedly) doesn't protest in any sense if 'x' doesn't exist, it is not possible to throw an exception in that case, unless code like check (aSet ['x']) would be generated everywhere.
This would mean an unacceptable performance overhead in my view.
So this is one of the places where the design objective to generate fast and small code collides with the desire to be CPython conformant.
In this case for Transcrypt "fast and small" was preferred.

**Comment by serin-delaunay** [comment]
EAFP is a common Python idiom; would it be reasonable to have a `__pragma__` to enable stricter behaviour here? This would make it simpler to translate existing code that uses this access style

Failing that, could the limitation be mentioned in the documentation? This kind of bug can be difficult to find, and it would save time for others who might encounter this.

**Comment by mlyle** [comment]
I've benchmarked a lot of this stuff on Brython-- which does a lot of this stuff correctly-- and performance is not bad.  Obviously adding checks everywhere has a cost, but how is one even supposed to do this in Brython?  What, you get undefined, which you can't even test for in anything near normal Python code -- it's not "is None", etc.

From what I've seen, you can't even use .get() and throw the KeyError yourself, because the catch then doesn't seem to catch it...

IMO a thin layer over javascript where you can write in python-ish syntax but still have to think entirely like it is javascript code, and can't reuse very much code from cpython--- there's just not much utility.  You get the worst of both worlds--- difficulty using Javascript frameworks, inability to draw on existing python code, and odd code that won't run properly in a Python interpreter nor is intuitive to a Javascript practitioner.

I understand there can be corner cases where performance or complexity would be dramatically suffer by having to do it completely correctly, but this is far more fundamental.

I need to do stuff with packing/unpacking binary structures.  You guys don't have struct.  I tried to adapt Brython's struct, but between byte arrays being broken, not getting key errors on dicts, and not being able to catch keyerrors that I threw myself I gave up.  I am not even sure it is possible, and I'm not an idiot.

**Comment by JdeH** [comment]
@serin-delaunay 
 I've added the \_\_keycheck\_\_ pragma as you  suggested:

http://www.transcrypt.org/docs/html/special_facilities.html#pragma-keycheck-and-pragma-nokeycheck

@mlyle 
Transcrypt strikes a balance between completeness and compactess/speed. It's downloads are as small and fast as JS, which is needed for the applications I write (scientific calculation, medical imaging, real time control). 
In difficult cases you can always use \_\_pragma\_\_ ('js', ...) but I actually never need it.
I've  programmed in JS for many years without joy, since I could not find an alternative that suited my needs (fast, compact, multiple inheritance, operator overloading). For me it has meant an enormous productivity boost and made browser programming fun. But of course that's personal. Still demands vary and there are other alternatives around, each with their own pro's and con's.

**Comment by mlyle** [comment]
Can this please default on?  Then it can be turned off for compactness/speed in bits of code where it's safe, but it's possible to include existing modules.

**Comment by JdeH** [comment]
Forgot to tell: there's also a command line switch: -kc or --keycheck.
So no need to change any code.
