### ISSUE TITLE
Undefined instead of TypeError on missing positional arguments.

### ISSUE THREAD

**Issue by Doldol** [QQuick/Transcrypt#402]
**Transcrypt:**
```python
console.log("START-----TEST")
def a(b):
	console.log(b)

a()
console.log("END-------TEST")
```
Output:
```
START-----TEST
undefined
END-------TEST
```

**Python:**
```
>>> def a(a):
...     print(a)
...
>>> a()
```
Output
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: a() missing 1 required positional argument: 'a'
```
Am I missing a pragma?
Python behavior in Transcrypt would be highly preferred.

**Comment by faerot** [comment]
TypeError itself is undefined too:
a.py
```python
raise TypeError('this is type error')
```
result:
```
F:\xxx>python3 -m transcrypt -p .none a.py

Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.50
Copyright (C) Geatec Engineering. License: Apache 2.0

Saving result in: F:/xxx/__javascript__/a.js
Saving minified result in: F:/xxx/__javascript__/a.min.js

Ready

F:\xxx>js __javascript__\a.js
__javascript__\a.js:2437:7 ReferenceError: py_TypeError is not defined
Stack:
  a/<@__javascript__\a.js:2437:7
  a@__javascript__\a.js:2436:3
  @__javascript__\a.js:2443:1
```

**Comment by JdeH** [comment]
@Doldol 

You're not missing a pragma.
Transcrypt has the same lenient attitude towards missing arguments as does JavaScript.
This is because Python function calls are translated directly into JavaScript calls.
Changing this behaviour would require an expensive runtime check.
This is avoided, since speed and code compactness is favored over compliance here.

The disadvantage is that indeed it isn't CPython compliant behavior.
The advantage is that JS libraries can have a TS facade while retaining semantics with respect to missing call time parameters.

Especially when working with a team, checking the match between call signature and defininition signature is an important weapon against bugs. In that the case static tiyping (-ds) option can be applied and certain important API's can be provided with static typing info.

@faerot 

TypeError has been added recently, but it's barely used by TS itself, on in one spot if I remember well.

**Comment by faerot** [comment]
@JdeH 
Let me explain why things like TypeError are important to me, maybe my use case will shed some light.
I am a game developer and we are making desktop games with embedded python. Currently we are looking for ways to make cross-platform games which will be playable in browser too.

I like your focus on speed which is a great feature and very important one to me as a game developer, but you are underestimating the importance of portability. Ability to write small browser scripts in python is cool and all, but ability to write the same code on client and server is a whole different level, especially if that code is without numerous hacks and limitations.

That's why I urge you to focus on compatability with CPython more, especially in those areas where it won't be too hard to do (i.e. TypeError) and won't slow down the code. And even if it slows things down - you can do it switchable with pragmas (which you are doing great btw). Making Transcrypt more compatible to python will make it easier to adopt - users will start using it with all compatible switches on and later when they understand the mechanics under the hood better, they can optionally switch them off in tight spots to speed things up.

Just my 2 cents of worth. I am evaluating Transcrypt for serious commercial game using Cocos2d-js - I can man up and work around the absence of most of the standard library, but constrantly stubmling upon these minor incompatibilities like TypeError and __dict__ makes me wonder if Transcrypt is production ready.

**Comment by JdeH** [comment]
@faerot 

Thanks for the valuable and detailed feedback. I'll try to provide a concise answer.

Let me start with the status that Transcrypt has in my own company. I work and have worked together with several research teams, currently electrocardiologists, but in the past also oil- and gas companies. Development tools in these area's are C++ (traditionally, still very important) and Python (starting some 17 years ago, increasingly important). Things like machine learning are on the rise, e.g. for recognizing pathological ECG rhythms. Applications usually have a strong visualization component, sometimes 2D, sometimes 3D, for which we base ourselves on OpenGL, since its the most portable way. Our applications are currently running under Windows (visualization, both medical and oil and gas) and Linux (computation, again both medical and oil and gas).

For visualization the browser is on the rise, although not yet the main platform. We've seen that trend coming some seven years ago and started out doing things in JavaScript. When coming from Python, JavaScript feels messy to put it kindly. It makes the impression of having grown organically rather than being designed at one point. Coming from C++ I personally particularly missed class based OO and multiple inheritance. On a deeper level I missed a consistent design paradigm. Our initial answer was to write a very compact JS library providing class based OO and multiple inheritance. While it did the job, the syntax was ugly. At that point we got the idea to remedy that, by having that code generated from Python syntax, rather than handwritten. We baptized it "small sane subset compiler" and had absolutely no ambition to get it anywhere near CPython compatible. We thought that was just completely unattainable.

Before embarking on this ourselves we evaluated things like RapydScript, Brython and PyPyJS. They all had their niche, but we had our own shopping list: small, fast code, multiple inheritance, operator overloading (computations), source level debugging, readable JavaScruot and preferably in the long run static typechecking. The most appealing project for our specific needs was PyPyJs but the size of the downloads and the difficulty connecting with JS libs were practical impediments that we anticipated wouldn't go away anytime soon. So we started rolling our own. In important decision was to use Python's native parser, something we still cherish since the syntactical complexities of Python are considerable, especially when adding things like type annotations.

This barebones Transcrypt was used professionally by us right from the start, but we felt there was no point in open-sourcing it, since it was too much a one-problem solution. Nevertheless we it in a public repo, since we don't believe in closed source for development tools. At that point several things happened:

- A broader group of people started to use Transcrypt, so we wrote some documentation and put it on the Internet on an equally bare bones website, featuring frames and things like that, constructed in an afternoon.
- It turned out to be surprisingly easy to built it out and we found ourselves a lot closer to CPython than we ever anticipated.
- We "invented" a CPython to Transcrypt back-to-back testing tool that allowed us to make small incremental improvements and release often, without the risk of anything falling over. This autotest tool is crucial for the reliability of Transcrypt and an absolute necessity for any professional ambitions with it. Every minor change goes through this regression test suite.

While syntactically Transcrypt 3.6.x just IS CPython 3.6.x , by means of using the same parser, semantically it's a different matter. While our back to back testing guarantees semantical equivalence for whatever is in the tests, there's no formal equivalence check, like analysis with denotational semantics. Moreover even CPython doesn't have such a formal definition. CPython is defined by its interpreter.

What then should our ambitions be on the semantical level. We'll never be more compatible than CPython in the browser (PyPyJS). The moment browser manufacturers start to support this, this will be the highway to the stars, but we don't want to wait for that. After all having a code base in a subset of Python will make the transition to CPython in the browser much easier

**Comment by faerot** [comment]
@JdeH 
Thank you for such a comprehensive response.
I am not expecting 100% CPython compatibility, that is very hard to reach and really unnecessary. I am talking about say 95% in those features where compatibility is relatively easy to achieve. It's usually 5% of those remaining features would require 95% of the effort. I am talking about balance of features vs effort required to implement them.

TypeError is not a major issue, it was rather an example of standard Python identifier not being defined, which is not even a library - not a big issue, just a minor bump on the road of trying to dive into Transcrypt for a CPython developer.

I have reviewed other python-JS approaches you've mentioned and indeed Transcrypt looks like somthing which could "fly" in the long run. It's a very serious decision for us right now, for expample we have been using our previous game engine for the past 10 years outliving many libraries it was built upon, so I am looking for technology that won't be a burder for us in the long run.

10 years ago we were doing desktop games and everything was fine, but now you have to do cross-platfrom (browser, mobile, desktop) and the only realistic way to cover browser is JavaScript. Despite following closely to the asm.js / WebAssembly stuff and having high hopes, I have to be very conservative about choosing technology, because this is my business, not just hobby. From what you said above I am sure you are understanding my sentiments.

Therefore right now I have only two choices: switching over to plain JavaScript (the thought of it makes me cringe), or using Transcrypt (which is sort of a shot in the dark, because I don't truly understand all the shortcomings and loopholes yet).

Being said that, I am not trying to port over our existing CPython codebase - I understood it's impossible almost right away. What I have tried to do is writing Transcrypt code with CPython backward compatibility in mind which wasn't easy as despite avoiding advanced CPython techniques like introspection, etc. I was often stumbling upon JS or Transcrypt related limitations. Maybe it's just learning curve with things getting better as I get used to it...

Anyway, coming from python world and doing JavaScript only out of absolute neccessity before, right now I am hoping to use Cocos2d which is a cross-platform engine. Desktop version will use CPython but writing in Transcypt-aware way, while Transcrypt will be used to make browser build. Desktop version would allow me to use all the CPython goodness for debugging (which would be a hell in the browser) while afterwards when doing browser build I will only fix specific browser and transcompilation related bugs.

The main idea is to do as much development outside of the browser as possible and this is were I need as much CPython compatibility as possible.

Speaking about debugging I see you have a nice browser test suite, but I am wondering how to build a test suite which is cross-platform for both browser and CPython? Testing same code for browser and CPython would allow to find varions bugs that occur due to difference in JavaScript and CPython behavior. I am surprised you didn't write your test suite interface to mimic CPython unittest module or at least provide unittest module wrapper around your test suite - that could have solved the issue. 

Nevertheless I am glad to see you are serious about this project and open to various ideas with it. I will try to play with it more to understand the specifics of it better.

Cheers,
Yaroslav
