### ISSUE TITLE
Aliases cause problems when dynamically interacting with attributes

### ISSUE THREAD

**Issue by RunasSudo** [QQuick/Transcrypt#414]
# Example 1

MWE:

```python
class Foo:
	pass

foo = Foo()
foo.bar = 'baz'
foo.name = 'hello'
foo.default = 'world'

print([x for x in dir(foo) if not x.startswith('__')])
```

Expected (Python) output:

    ['bar', 'default', 'name']

Transcrypt output:

    ['bar', 'py_default', 'py_name']

Rather than return the attributes as declared, Transcrypt spits out the raw Javascript attributes, which have been modified by the (default) aliases. This is understandable behaviour, but it would be ideal to have some way of easily extracting the attributes as declared.

Admittedly, this use case is probably somewhat uncommon. The following example is more significant.

# Example 2

MWE:

```python
#__pragma__('kwargs')
def foo(*args, **kwargs):
	default = kwargs.get('default', 'bar')
	return default

print(foo())
print(foo(default='Hello World'))
```

Expected (Python) output:

    bar
    Hello World

Transcrypt output:

    bar
    bar

Transcrypt passes the `default` keyword argument as `py_default`, and then fails to extract this value. A common enough design pattern, this also produces unexpected results for things like `kwargs['default']`, `'default' in kwargs`, and so on. Dealing with this requires an ugly hack like `kwargs.get('default', kwargs.get('py_default', 'bar'))`.

Again, the behaviour is understandable given Transcrypt's internals, but it would ideal to have some method of getting the Pythonic result.

Edit: This is vaguely related to #377, but is broader in scope, relates to situations where the existing workarounds are not feasible.

**Comment by JdeH** [comment]
Not so easy to overcome.
I've added the label postponed since this isn't going to be solved soon.
This means the issue will be closed (after a short while) but that it still can be found
by searching for label postponed.

Some of the postponed issues have been solved by contributers (like e.g. method decorators).
This one also will have to wait for a very clever solution, I guess...

**Comment by RunasSudo** [comment]
I appreciate the response. Example 1 does sound difficult to address. For example 2, is there any simpler measure that can be added for `kwargs` specifically, since this behaviour will almost always be unexpected in such contexts? Since `kwargs` will generally be accessed using the `obj[key]` or `obj.get(key)` notation rather than `obj.key`, the range of potential conflicts with Javascript attributes is reduced.

**Comment by JdeH** [comment]
A partial solution for this will be added.
It will not work for static retrieval of aliased attributes set with setattr, since that would require dynamic check against aliaser list, which is expensive.
kwarg.get (key) will work, kwargs [key], since it would require operator overloading, which is expensive.

The partial solution does cover  your examples, however.
And as a last resort there's the possibility of locally unaliasing an identifier.

**Comment by JdeH** [comment]
Commited
