### ISSUE TITLE
Entity Willing to Accept Payments to Make Specific Improvements 

### ISSUE THREAD

**Issue by notzoom** [QQuick/Transcrypt#420]
I am wondering if there is such an entity around, whether the project itself or a company of a contributor.

Thanks !

**Comment by JdeH** [comment]
Hi,

Thanks for your relevant question that requires a careful answer, since there are several aspects to this.

- Transcrypt is open source, made available under the Apache 2 license. Many people have contributed to it. Whatever additions or improvements Transcrypt itself it will acquire, will forever be free to anyone.

- Anyone is allowed to make money with it. So anyone willing to provide support or advice, developing applications for it etc. is free to do so either on a voluntary or commercial basis. So contributors or non-contributers alike, feel free to do business with it, only bound by the Apache 2 license.

- We've considered bringing Transcrypt under the hood of an official foundation, a non-profit organisation. That would be nice, since such an organisation could acquire funds to e.g. enable people to travel and hold conference talks about Transcrypt, among other things. However this is not without legal consequences and has to be done properly.

You are mentioning specific improvements. Could you elaborate a bit on what these specific improvements would be. Are they of use to developers in general. Or are they e.g. specific to your organisation. Maybe these improvements could also be added for free, if they are of use to others as well.

**Connected to this: The plan is to add a page to the Transcrypt website mentioning people c.q. companies willing to provide professional support. I own a company myself and would probably put it on the page. But I hope others will as well, since other than holding the copyright to enable steering its direction, I am in no way privileged with respect to Transcrypt.**

**Any reactions welcome.**

Kind regards
Jacques

**Comment by notzoom** [comment]
Hello ! Thank you for the prompt and detailed response. 

I am interested in sponsoring tasks that will help whoever is using the project, not just me.

"Maybe these improvements could also be added for free, if they are of use to others as well."

I have plans to use Transcrypt in production and what I seek is just the comfort of knowing there will be someone around I can pay to look into possible issues with high priority - the first step is obviously to report them here but everyone has his own schedule, therefore my idea to pay popped up.

Quick question: For suggestions / ideas, should we create issues here or is there a mailing list/forum available ?

**Comment by JdeH** [comment]
Hi,

> what I seek is just the comfort of knowing there will be someone around I can pay to look into possible issues with high priority

I am one of the persons providing commercial support via my company:

[http://www.geatec.com](url)

However with regard to planning (and feasibility) we'll have to look on a case by case basis. But if I understand you properly you're also looking for commitment and continuity. We now have 13,000+ downloads per month and all I can say is that we are very aware that people depend upon it.

I can only tell you what the plans are, humanly speaking: building it out further and supporting it professionally for years to come.

**Comment by notzoom** [comment]
That is amazing to hear, honestly. 

I stumbled upon the project because I was looking for something like this. 
Not because I am just super productive in Python and because it leads to solutions that are maintained better but because I also derive tons of pleasure using it, in contrast to JavaScript. But sadly we cannot turn our back to the JavaScript ecosystem to do specific things - Transcrypt is the ideal answer to this. 

Thank you so much for the great efforts in making this possible ! 
Be sure that people like me will be contributing with great pleasure.
