### ISSUE TITLE
Transpiling in the Reverse Direction

### ISSUE THREAD

**Issue by notzoom** [QQuick/Transcrypt#423]
I am curious how much effort it would be to also allow JS to be converted to the Python equivalent code so that we can derive codebases from already existing JS projects. 

Do you see that as a possible goal of the project ?

**Comment by JdeH** [comment]
I don't expect functionality like that to be added to the project.
The reason is that JavaScript prototype based objects allow a number of tricks (dirty tricks from a Python point of view) that are out of limits in class based object orientation.
The situation is comparable to trying to translate a language featuring the infamous GOTO statement (like MSBasic) to a structured language (like Modula2). This is almost impossible, since every application would become a Finitite State Machine in a big while loop.

To be a bit more exact:  Translating JavaScript to Python is technically possible, and there are some tools attempting this for a limited subset, but it's bound to result in Python code that would make the original JavaScript seem well structured in comparison. In addition going back from Python to JavaScript again would result in a regular mess (though functionally equivalent).

The best way for JS libs to be, in my view, is in JS. JS isn't principally evil, something like JQuery is a testimony to highly intelligent (albeit somewhat deviant) thinking. In my opinion we should embrace the beauty and sometimes genius of good JavaScript libs, even if they're based on a programming paradigm that I personally don't like. Transcrypt was born because, like you, I perceive programming in Python as "fun" wereas programming in JavaScript for me is "a chore", no fun at all. And I think Python fosters good programming habits and makes large code bases more stable, flexible and comprehensible. 

One thing that _can_ be done with good JS libs, is to encapsulate them in a Python/Transcrypt wrapper. This isn't always worthwhile, but can be a remedy to avoid constantly using JS'esque idiom like \_\_new\_\_. (see e.g. [http://www.transcrypt.org/docs/html/special_facilities.html#creating-javascript-objects-with-new-constructor-call](http://www.transcrypt.org/docs/html/special_facilities.html#creating-javascript-objects-with-new-constructor-call)).
