### ISSUE TITLE
How to make a donation for supporting transcrypt

### ISSUE THREAD

**Issue by amiguet** [QQuick/Transcrypt#427]
Hello,

Each end of year I select an open source project that was particularly useful to me during the year and make a donation.

This year I'd like to donate to transcrypt, but I could not find any information about donations. Did I miss something? Or does transcrpyt have a "no donation" policy for some reason?

Cheers,

Matthieu

**Comment by JdeH** [comment]
Hi Matthieu,

Good to hear that Transcrypt has been useful to you!

We've thought about accepting donations for quite  some time,
since Transcrypt consumes quite some resources.
Just never got around to really enabling them,
but now a donate button was added to the bottom of:

http://www.transcrypt.org

Thanks in advance, we'll try to further improve and promote Python in the Browser and especially Transcrypt with any donations made.

Kind regards
Jacques de Hooge

**Comment by amiguet** [comment]
Great, donation made :-)

Thanks again for all the great work. I'm looking forward to further explore the possibilities of transcrpyt next year!

Cheers,

Matthieu

**Comment by JdeH** [comment]
Thanks for your generous donation.
And I sincerely hope Transcrypt will continue to serve you well!

Kind regards
Jacques
