### ISSUE TITLE
Is Guido aware of Transcrypt ? Should we let him know ? 

### ISSUE THREAD

**Issue by notzoom** [QQuick/Transcrypt#454]
I am asking since I went through the documentation of Transcrypt last night and it's quite stunning how advanced Transcrypt is. Guido has said a few years ago in an interview that it will be hard to bring Python to the client-side of the browser - I am really wondering if he knows about Transcrypt. If not, why shouldn't he ?

**Comment by fzzylogic** [comment]
[Yes](https://github.com/python/mypy/issues/2097), though Jacques would have more details.

**Comment by JdeH** [comment]
Indeed I think Guido knows through a small contribution I made to the MyPy project that's he's in, in order to be able to use static typechecking from Transcrypt. But I imagine he's very thinly spread and I am hesitant to explicitly contact him about it.

Personally I feel that Transcrypt can serve many more developers than it currently does, base on it's features. Still the bulk of them has never heard of it. This can also be seen by the growth curve of github stars, which is typical a market that isn't even near saturation. It'll become gradually more known, e.g. by publications like this:

https://www.safaribooksonline.com/library/view/python-in-a/9781491913833/ch01.html#idm139800537970608

If Guido would mention it somewhere it certainly would be a great boost, but I don' want to force anything here. If he thinks it's worthwhile he probably will.

**Comment by notzoom** [comment]
@JdeH I have sent you an important email regarding this to info@geatec.com.
