### ISSUE TITLE
Reverse string slice goes into infinite loop

### ISSUE THREAD

**Issue by sirex** [QQuick/Transcrypt#455]
How to reproduce:

```javascript
"abc".__getslice__(null, null, -1)
```
This goes on forever.

Basically what I'm trying to do is this:

```python
assert "abc"[::-1] == "cba"
```

**Comment by sirex** [comment]
```python
assert ''.join(reversed("abc")) == "cba"
```

This does not work to, it gives:

> TypeError: iterable.reverse is not a function

**Comment by neriusmika** [comment]
`''.join(reversed(list('abc')))`

**Comment by sirex** [comment]
I found this work around myself, but what I'm trying to tell, is that what works in python, does not work in transcrypt. So I support it's a bug.

**Comment by neriusmika** [comment]
It's a limitation and if you read documentation, Transcrypt will never be fully compatible with python, otherwise it will be useless in real world applications, like almost all other implementations (very slow or very huge).

**Comment by JdeH** [comment]
Google Translate:

Since your strings are not duplicated, they will not be done with them. Try it before using Array.from () to use it or convert to a list (it's true, I have never tried it myself). Somewhere here it was already said that, so far, it's not very relevant to do iterations, because speed will be affected. In any case, the ES6 and the javascript itself are not an easy solution. Usually uses split and join, but it does not work if there are unicode characters.

**Comment by pjz** [comment]
I just bumped into this, and while I can accept that receiving 

    TypeError: iterable.reverse is not a function

is a limitation, I think the originally-described behavior of going into an infinite loop in the browser should qualify as a bug.  Failing and throwing an error to the console would be a, to me, totally acceptable fix - it'd be way better than causing the browser to become nonresponsive as it goes into an infinite loop.
