### ISSUE TITLE
accessing a Javascript constructor in sublibrary

### ISSUE THREAD

**Issue by chopin** [QQuick/Transcrypt#458]
While I am using Babylon.js, I encountered a case to access a constructor in sub-library.  TextBlock() below is a constructor of BABYLON.GUI. It dies when the created value of textBlock is passed to Babylon.js possibility because of missing a proper process for a constructor.

`textBlock = BABYLON.GUI.TextBlock("but1", "hello") `

So, as usual, I tried an constructor process using _ ctor() calling _ _ new _ _ () which is done in org/babylonjs/_ _ init _ _.py 
```
from org import babylonjs as babylon
textBlock = babylon.GUI.TextBlock("but1", 'hello') 
```
A runtime error was raised  "Uncaught TypeError: Cannot read property 'TextBlock' of undefined". It implies babylon.GUI is undefined. So, I created "org/babylonjs/GUI/" directory, and I copied "_ _ init _ _.py" and modified as following  But the same error was raised.
```
#__pragma__ ('noanno')
def _ctor(obj):
    def _c_(*args):
        return __new__(obj (*args))
    return _c_
api = __pragma__ ('js',
    '{}',
    'BABYLON.GUI'
)
TextBlock=_ctor(api.TextBlock)
```
Should the final directory GUI be explicitly imported? I tried. It worked at this time.
```
from org.babylonjs import GUI as babylon_GUI
textBlock = babylon_GUI.TextBlock("but1", 'hello') 
```
Well, it works, but it is not pretty. Is there a better way for this? I wonder why GUI directory should be explicitly imported. In standard Python, all sub directories are accessible after the top directory is imported.

Thanks in advance.

**Comment by chopin** [comment]
By the way, Transcrypt worked well with Three.js. I moved to Babylon.js due to secondary library integration issues not because of Transcrypt. I found that Transcrypt worked well with Babylon.js too. 

I used Pyjs, Brython before, but they were too slow.  About 10~30 times slower than CPython in my experience. Moreover, they have a critical problem in integration of Javascript library. I think that Transcrypt is the best so far in speed and Javascript integration point of views. Thanks to the simplicity approach, I think that Transcrypt can be a faster implementation of Python based on Javascript. I want to thank you for developing this great tool. As a Python lover, I am really happy to find Transcrypt.

**Comment by JdeH** [comment]
There are slight differences beween the import mechanism in Transcrypt and CPython:

http://www.transcrypt.org/docs/html/special_facilities.html#transcrypt-s-module-mechanism

Main reason is that the import mechanism is kept much simpler. I will take another look at the things you ran into, but I am afraid this has to be labeled as a rather persistent limitation, be it a small one.

About performance. I want to avoid direct comparison with other transpilers, since they serve a different purpose. Brython e.g. allows transpilation in the browser, which makes it very easy to use directly, hence a great tool for many developers. There's also Skulpt, which manages to simulate blocking I/O, making it popular in education.

However I've compared it to CPython, using the PyStone benchmark, and it seems to be 3-4 times faster than CPython using the Google JS VM (#457). Verification will be appreciated, curious how it runs on different machines.

Transcrypt seems to land well, which is good, I love Python too. Together with C++ they provide all I need to do my job.

**Comment by chopin** [comment]
I tried to use a full path. It worked too. It looks better. If I change 'babylonjs' to 'babylon' the fullpath looks pretty similar to the original Javascript code.  
```
import org.babylonjs.GUI
self.textBlock = org.babylonjs.GUI.TextBlock("but1", 'hello')  
```

**Comment by JdeH** [comment]
OK thanks!
I will devote some more attention to this, hopefully this week.

**Comment by chopin** [comment]
I knew that Transcrypt is faster than CPython right after I looked at the compiled code.  I was thinking about porting by old Python programs to Transcrypt for faster implementation. Congratulation on the benchmark tests on speed performance. I hope that you keep going on this direction.

**Comment by chopin** [comment]
I tried  the idea using a full path further. I removed 'org' directory and erased 'js' suffix from the library name

```
import babylon.GUI
self.textBlock = babylon.GUI.TextBlock("but1", 'hello')  
```
It worked. And it looks almost same to the original javascript code. So, whenever a sub library module is accessed, simply importing the full path is the best. If an additional constructor process is required, insert it to _ _ init _ _ .py file.  

I think that it is the best way. I am closing this issue
