### ISSUE TITLE
Request to use a variable sized font for the website.

### ISSUE THREAD

**Issue by chopin** [QQuick/Transcrypt#468]
The current Transcrypt web site is using small fixed fonts which is not readable by users with bad eyesight like me. Could you please change it to display with variable-sized fonts?

I usually use ctrl-key with mouse-wheel to zoom in a webpage, but it doesn't work in the Transcrypt web site. I think that using variable-sized font is crucial for smartphone users too. 

When I visited the Transcrypt website for the first time, I immediately gave up looking into it because I could't read it.  Later I found a way to read it by copy-and-pasting the webpage into a texteditor allowing zooming. I still have to do it to read the webpages. 

I am happy to using Transcrypt, but I was almost lost a chance to find the best Python transcompiler because of  the fixed-size fonts. How sad it is if there are people who lose a chance to know it because of the font size? 

Thanks.

**Comment by JdeH** [comment]
Thanks a lot for letting me know!
Wasn't at all aware of that.
Will improve this and if it's done will ask your feedback in this issue.

Kind regards
Jacques

**Comment by JdeH** [comment]
I think the website is a bit more accessible now by scaling the font.
Also I try to use the full screenwidth at scales > 130%, to be able to still show a reasonable amount of text if zoomed in.
At larger scales things start to overlap.
Thought about blocking > 200%, but haven't, since that's when people may need scaling most,
and form follows function.
Zooming doesn't function properly on iPod/iPad/iPhone, couldn't get that working within reasonable time (as usual).

**Comment by Michael-F-Ellis** [comment]
FWIW, I've had good luck recently with specifying margins and font sizes in viewport-width units, e.g.
```
            h4 {
                font-size: 3vw;
                margin-left: 2vw;
                margin-top: 1vw;
                margin-bottom: 1vw;
            }

            p {
                font-size: 2vw;
                margin-left: 2vw;
                margin-right: 4vw;
                margin-top: 1vw;
                margin-bottom: 1vw;
            }
```
It's not a perfect solution, but it keeps the text readable on desktop and mobile devices with less effort than anything else I've tried.  It also gives the user freedom to adjust by changing the window  width.

See http://ellisgrant.pythonanywhere.com/ for a simple demo made with Transcrypt and htmltree. Change the page width to scale the text to your preference.

**Comment by chopin** [comment]
Now I can read the website.  Thank you so much for your efforts.

**Comment by JdeH** [comment]
@Michael-F-Ellis 

As an experiment the Transcrypt site uses Transcrypt rather than plain CSS in a lot of places.
The character size is made proportional to the window area, to accommodate for equal amounts of text on different monitor types.

Hadn't taken accessibility  in to account yet. Maybe a simpler approach, indeed using viewport units would have been better. I am afraid it shines through here that I spend more time on the backend than on the frontend. Rightnow I try to keep the website in order with minimal investment of effort. I'll remember your hint, however, it may come in handy in the future.

Thanks
Jacques

**Comment by Michael-F-Ellis** [comment]
@JdeH 
I'm not fond of separate CSS files, either, so the sample I quoted is part of a ```<style>``` tag created in Python with htmltree.  The Tbon demo site is, _quelle surprise_, derived from a copy of NearlyPurePythonWebAppDemo.  

On the server side, I have a generated index.html created with an empty ```<body>``` tag that gets filled with html generated by Transcrypted Python running in the browser.  That allows the possibility to customize the html based on information available from JS calls but I don't really do much of that for that particular page.  

In some other work, I've found ```getBoundingClientRect()``` really useful for dynamically positioning the components of page.  For example, here's some code I use to scroll a location in a really long page of text to a position just beneath a fixed header at the top of the page.

```
    def scrollToContentElement(_id):
        """
        Move the content element with id=_id to a position just beneath
        the bottom of the page header element.
        See
        https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop
        https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect
        """
        el = document.getElementById(_id)
        hdr = document.getElementById('page-header')
        eltop = el.getBoundingClientRect().top
        hdrbottom = hdr.getBoundingClientRect().bottom
        fudge = 4 ## a little space below hdrbottom

        ## Scroll the element into view and return it
        ## in case we want to do something further with it.
        document.body.scrollTop += eltop - hdrbottom - fudge
        return el
```

**Comment by JdeH** [comment]
Thanks for the hints.
There's a workable solution now, although still on Apple it doesn't quite look like it should.
