### ISSUE TITLE
How to use new Image()

### ISSUE THREAD

**Issue by notzoom** [QQuick/Transcrypt#476]
If you try to do:
drawing = new Image()
Transcrypt throws an error:
```
Error while compiling (offending file last):
	File '/home/user/Desktop/geometry.py', line 14, namely:
	
	drawing = new Image <SYNTAX FAULT]  ()

Aborted
```
I need this to load an image from a URL on the canvas. What can we do in this case ?

**Comment by neriusmika** [comment]
drawing = \_\_new\_\_(Image())

https://www.transcrypt.org/docs/html/special_facilities.html#creating-javascript-objects-with-new-constructor-call

**Comment by notzoom** [comment]
@neriusmika Thanks a lot, sadly I can't open the site now :P

**Comment by neriusmika** [comment]
"While creating objects in Transcrypt mostly happens in the plain Python way, e.g. canvas = Canvas (<parameters>), objects from 3rd party JavaScript libraries often have to be created using new. In Transcrypt such objects are created by calling the \_\_new\_\_ function, e.g. canvas = \_\_new\_\_ (Canvas (<parameters>), as can be seen in the Pong example. This mechanism is simple, follows Python's syntax rules and doesn't require updating of an encapsulation layer if a later version of the underlying JavaScript library features additional constructor functions. Therefore in most cases it is the preferred way to create objects who's initialization requires calling 3rd party JavaScript constructor functions.

As an alternative, instantiation and construction can be encapsulated in one function call. Since this in fact creates an alternative API facade for the 3rd party JavaScript library, such an encapsulation should be kept separate from the original library, e.g. by putting it in a separate importable module. The JavaScript code for this encapsulation would e.g. be <facade module name>.Canvas = function (<parameters>) {return new Canvas (<parameters>);};. After importing the facade module, canvas creation is straightforward: canvas = Canvas (<parameters>).

As a third alternative, encapsulation can be done in Python rather than JavaScript: def Canvas (<parameters>): return \_\_new\_\_ (<3rd party module name>.Canvas (<parameters>). Also in this case the creation syntax is simple: canvas = Canvas (<parameters>)."

**Comment by JdeH** [comment]
@notzoom 
There's a local copy of the docs in your installation dir.
I don't know where TS is installed on your machine, but for me it is:

file:///D:/python36_anaconda/Lib/site-packages/transcrypt/docs/sphinx/_build/html/index.html

**Comment by notzoom** [comment]
@JdeH That's good to know, I will try to find it locally until the site is up.

**Comment by JdeH** [comment]
If you can't find it, let me know, I'll send you a zipped copy.

**Comment by neriusmika** [comment]
@notzoom, I think the site is not down. Your error shows dns problem. It can't find transcrypt.org domain.

**Comment by notzoom** [comment]
@neriusmika Right, I was referring to the fact that it's not loading.
