### ISSUE TITLE
Blender game engine to JS exporter

### ISSUE THREAD

**Issue by BluePrintRandom** [QQuick/Transcrypt#489]
what it be possible to export Blender game engine projects to JS somehow?

what sort of work would it entail?

Do you know anyone who may be interested?

distribution is killing bge**

**Comment by theodox** [comment]
There's a blender importer for the [Babylon.js](https://www.babylonjs.com) engine, so that's a good place to start for looking at already working model code.

The core of entire engine is C++ howerver, it'd be very hard to get it 'ported' -- you might be able to emulate it, but that would be a lot of workl
