### ISSUE TITLE
Named parameters don't work

### ISSUE THREAD

**Issue by typescriptstudies** [QQuick/Transcrypt#533]
`test.py:`

```
class Test:
    def __init__(self, fixarg, one = 1, two = 2):
        print(fixarg, one, two)
        
Test(0)
Test(4, 5, 6)
Test(15, 25)
Test(9, one = 4)
Test(9, two = 6)
Test(9, two = 11, one = 34)
```

compiled it with:

`transcrypt -b -p .none --nomin test.py`

run it with:

`node __javascript__\test.js`

printed:

```
0 1 2
4 5 6
15 25 2
9 1 2
9 1 2
9 1 2
```

Last 3 outputs are clearly wrong. Named parameters are ignored.

**Comment by neriusmika** [comment]
http://transcrypt.org/docs/html/special_facilities.html#keeping-your-code-lean-pragma-kwargs-and-pragma-nokwargs

**Comment by typescriptstudies** [comment]
Thanks a lot!

```
__pragma__("kwargs")

class Test1:
    def __init__(self, fixarg, one = 1, two = 2):
        print(fixarg, one, two)

__pragma__("nokwargs")

class Test2:
    def __init__(self, fixarg, one = 1, two = 2):
        print(fixarg, one, two)
        
Test1(0)
Test1(4, 5, 6)
Test1(15, 25)
Test1(9, one = 4)
Test1(9, two = 6)
Test1(9, two = 11, one = 34)
Test1(9, 2, one = 34)

print("")

Test2(0)
Test2(4, 5, 6)
Test2(15, 25)
Test2(9, one = 4)
Test2(9, two = 6)
Test2(9, two = 11, one = 34)
Test2(9, 2, one = 34)
```

prints:

```
0 1 2
4 5 6
15 25 2
9 4 2
9 1 6
9 34 11
9 34 2

0 1 2
4 5 6
15 25 2
9 1 2
9 1 2
9 1 2
9 2 2
```

**Comment by theodox** [comment]
might want to close this one if it's taken care of for you,

**Comment by erelsgl** [comment]
I have the same issue. If I understand correctly, the recommended solution is to add "__pragma__" before and after each function with which I want to use named arguments. However, I have Python code that I use in other server-side projects (in fact, for me, that's the whole point of using Transcrypt in the first place - being able to use the same code for server-side and client-side). Since the "__pragma__" is not recognized by the Python 3.7 interpreter, I cannot put __pragma__ in this code. Is there another solution?
