### ISSUE TITLE
3.7.5 : is and js_is aliases conflict

### ISSUE THREAD

**Issue by bradiso** [QQuick/Transcrypt#562]
Hi,

This is about latest version.

I think there is a conflict between "is" ans "js_is" aliases : "js_is" is replaced by "is" then replaced again by "py_is".
In the end "js_is" is translated in "py_is" (should be "is").

By the way py_is looks like not being defined.

Here is a **very dirty workaround** doing the job in my case, it just breaks the loop when "is" or "js_is" :

in compiler.py file :

```
    def filterId (self, qualifiedId):   # Convention: only called at emission time
        if self.idFiltering:
            for aliaser in self.aliasers:
                if re.match(aliaser [1], qualifiedId) and qualifiedId in ("is", "js_is"):
                    qualifiedId = re.sub (aliaser [1], aliaser [2], qualifiedId)
                    break
                else:
                    qualifiedId = re.sub (aliaser [1], aliaser [2], qualifiedId)
        return qualifiedId
```

Except this minor issue, everything works fine (for now) migrating from 3.6.101 to 3.7.5. The code is even shorter. I use bundle.js as recommended to get a monolitic file (better fit my use).

Congrats for this wonderful tool.

**Comment by JdeH** [comment]
Thanks for the feedback!
We will look into this a.s.a.p.

**Comment by bradiso** [comment]
# this pragma for 3.6.101
```
__pragma__ ("alias", "js_is", "is")

if S("#page").js_is(":visible"):
	print("ok")
```

-b -n -e 5 main.py

```
		if (S ('#page').is (':visible')) {
			print ('ok');
		}
```

-b -n -e 6 main

```
if (S ('#page').py_is (':visible')) {
	print ('ok');
}
```

**Comment by JdeH** [comment]
The problem is caused by the fact that the following default aliases were unfortunately omitted from 3.7.101:

            ('is', 'py_is'),                        ('js_is', 'is'),

You added a custom alias, which was the right thing to do.
However it bites the default aliases that have been added in 3.7.x,
since they are applied later, hence cause cyclic replacement.

If you're only using 3.7.x, you can leave out the alias for js_is, since it is now a default alias.
The code would then just be:

```
__pragma__ ("alias", "S", "$")

if S("#page").js_is(":visible"):
	print("ok")

```

If you want it to work both in 3.6.101 and 3.7.x,
the following should do the trick:

```
__pragma__ ("alias", "S", "$")

# remove default alias in 3.7.x
__pragma__ ("noalias", "is", "py_is")

# this pragma for 3.6.101
__pragma__ ("alias", "js_is", "is")

if S("#page").js_is(":visible"):
	print("ok")
```

Feel free to reopen if there are still problems with this.

KR
Jacques
