### ISSUE TITLE
Incorrectly binding __new__ and *args 

### ISSUE THREAD

**Issue by ceronman** [QQuick/Transcrypt#62]
Using `__new__` with `*args` ends up in incorrect binding of the function.
Here is an example to reproduce the issue:

``` python
def createWebSocket(*args):
    return __new__(WebSocket(*args))

ws = createWebSocket("ws://127.0.0.1:8080")
```

This will generate the following JS code:

``` javascript
var createWebSocket = function () {
    var args = tuple ([].slice.apply (arguments).slice (0));
    return new WebSocket.apply (null, args);
};
createWebSocket ('ws://127.0.0.1:8080');
```

When executed on Chrome, this code throws the following error:

`VM222:3 Uncaught TypeError: WebSocket.apply is not a constructor(…)`

According to this [StackOverflow question](http://stackoverflow.com/questions/1606797/use-of-apply-with-new-operator-is-this-possible), the proper way of generating such code should be:

``` javascript
var createWebSocket = function () {
    var args = Array.prototype.concat.apply([null], arguments);
    return new (Function.prototype.bind.apply(WebSocket,args));
};
```

**Comment by JdeH** [comment]
Hi,

There are 3 options to make this work:

1) Make function calls inside a call to __new__ context-aware in such a way that *args would be translated using Function.prototype.bind.apply only in the context of at least one enclosing __new__. Since a calls to __new__ can  be nested in the param list of another __new__, this would involve counting the nesting level. This is doable, I expect, but it's also a bit hacky,

2) Using Function.prototype.bind.apply everywhere in case of *args. This would bloat all code using *args a bit, so I prefer not to do that. Of course a command line switch or pragma could be used, but pragma's and switches put the burden on the individual developer, so there shouldn't be too much of those.

3) Waiting for the spread operator to arrive in all browsers. Currently only Opera doesn't have it. This would make all *args calls more concise, including the ones not inside a __new__ paramlist, which I like.

There are more issues that wait for newer versions of JS to become pervasive, like translating Python comprehensions to JS comprehensions, rather than to JS for loops.

Therefore I think the best thing to do is to wait a little and keep this issue in stock as an enhancement for a next major version of Transcrypt, maybe only activating it in the JS6 mode. That will be a while, since I don't want do alienate to many people that have to live with older browsers.

All this under the assumption that temporarily working around this limitation, either bij using the \_\_pragma\_\_ ('js', ...) or unpacking params in advance is doable.

Let me know what you think.

Jacques

**Comment by ceronman** [comment]
Hi Jacques,

Thanks for the detailed response. I think option 2 is out of question, as it's an unnecessary bloat for a not so common feature.

This feature is easy to workaround, so I'm ok with leaving it as a nice-to-have or enhancement. I'm still curious to see if it's possible to achieve option 1 in a not very hacky way, but I'm fine with leaving it as a low priority.

Thanks,

Manuel.

**Comment by JdeH** [comment]
With ref to issue #258, not expecting to work on this anytime soon.
