### ISSUE TITLE
Is it possible use smtplib.py?

### ISSUE THREAD

**Issue by tst32** [QQuick/Transcrypt#775]
I need  these libs

import os
import telebot
import smtplib
import textwrap
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication

`transcrypt   -m -b -n .\sendtask-bot.py`

Import error, can't find any of:
                ./email/mime/application/MIMEApplication.py

**Comment by JennaSys** [comment]
Are you going to be running the transcrypted JavaScript code in a web browser or locally on a Node.js server?

Generally speaking, most of the standard library and 3rd party Python libraries will not be usable with Transcrypt unless they are pure Python.  Being that Transcrypt is normally used to generate JavaScript code that runs in a web browser, you would usually substitute a JavaScript library for the Python library you would normally use.  IOW, use npm instead of pip.  You don't have to code in JavaScript to use the JavaScript libraries, you just need to know the API it uses and you can use Python (with Transcrypt) to code directly to that.  Transcrypt does support almost all of Python's built-ins and language structures though.

So for example, if you wanted to make an HTTP request from a web browser, instead of reaching for urllib or the Python requests library, you would use window.fetch() or the JavaScript axios library instead. That said, I'm not sure it's possible to send an email from a web browser directly with JavaScript, without using the users email client.

**Comment by tst32** [comment]
I understand your explanation. Thanks. I have the option to run on the server side, but in any case, Transcrypt is not the easy way to make a telegram bot. To be more specific I am limited to ECMASCRIPT 5 because I write a web application in gogle app script, I think i have option to switch out to google apps engine and keep my python code or stay in google web app and rewrte all on javascript ecmascript v5 .
