### ISSUE TITLE
Replacement for urlsplit in Transcrypt?

### ISSUE THREAD

**Issue by halloleo** [QQuick/Transcrypt#802]
In Transcrypt I cannot import `urlsplit`/`urlunsplit` from `urllib.parse`. (I get an "Can't import from module 'collections'" error.)

If I want to parse and construct URLs what can I use as a replacement? I know JS offers the URL Object via `new URL(...)`), but how can I use that in Transcrypt? Does Transcrypt has a binding for this?

Thanks for pointers!

**Comment by JennaSys** [comment]
Not sure what your exact requirements are, but I use JS functions for getting URLs and query parameters from the web browser and converting them to a Python dictionary with the following code:
```python
querystring = window.location.search
param_entries = __new__(window.URLSearchParams(querystring)).entries()
url_data = {'pathname': window.location.pathname,
            'params': {p[0]: p[1] for p in param_entries if p}}

```
Transcrypt has the `__new__()` function for creating JavaScript objects in your Python code.

Here is also a helper function I use for taking a Python dictionary and turning it into an encoded query string using a JS function:

```python
def buildParams(param_dict: dict):
    param_list = [f"&{key}={window.encodeURIComponent(val)}" 
                  for key, val in param_dict.items() if val]
    params = ''.join(param_list)
    return f"?{params[1:]}" if len(params) > 0 else ''
```
So whatever you need to do is probably available in JS.  You just might need to use the `__new__()` function when a JS object needs to be created.  Hopefully these examples will give you an idea of how to approach it.

As an aside, I usually put these helper functions in their own Python module called _jsutils.py_ or something so that I can keep the rest of my modules pure Python.

**Comment by halloleo** [comment]
Thanks @JennaSys. Makes sense.

Great tip to put the JS related stuff in its own module!
