### ISSUE TITLE
List addition converts data to a string

### ISSUE THREAD

**Issue by ZLJasonG** [QQuick/Transcrypt#805]
test = [1]
test += [2]
print(test)

Expected
[1,2]

Actual
"12"

**Comment by ZLJasonG** [comment]
Can be worked around by converting the source python to use [1].extend([2]) where python source edits are possible

**Comment by JennaSys** [comment]
I haven't tested your specific case, but do you have [operator overloads](https://www.transcrypt.org/docs/html/special_facilities.html#operator-overloading-pragma-opov-and-pragma-noopov) enabled? I would usually use the[ single line pragma](https://www.transcrypt.org/docs/html/special_facilities.html#the-single-line-activation-variety) in this case:

```
test = [1]
test += [2]  # __:opov
print(test)
```
I don't recall if I've used `+=` with it before, but I know this works with just `+`.

And as the docs mention, it's best to not enable operator overloading globally since it will affect performance.

**Comment by ZLJasonG** [comment]
Thanks that does resolve the issue, I hadn't expected the built-in types like lists to be considered as overloads.
