### ISSUE TITLE
Support __getattr__

### ISSUE THREAD

**Issue by katsko** [QQuick/Transcrypt#89]
```
class A(object):

    def __init__(self):
        self.x = 111

    def __getattr__(self, name):
        return name


a = A()
print(a.x)
print(a.y)
```

Result in browser console:

> > 111
> > (Empty string)

`__getattr__` isn't support?

**Comment by AXGKl** [comment]
you can do `getattr(obj, key, default)` but currently not overload __getattr__ and __setattr__ . 

I like the feature as well but it would be *pretty* expensive to pass every dot operation through a function.
So maybe via local pragmas, telling the compiler to create an ES6 proxy object, see http://stackoverflow.com/questions/1529496/is-there-a-javascript-equivalent-of-pythons-getattr-method

For 'older' browsers (hello IE) its technically not even possible.

I like the feature as said, also `__setattr__` - think e.g. about using it in combination with a redux store, that would rock. 

Final verdict is on Jacques though.

**Comment by JdeH** [comment]
For now __setattr__ and __getattr__ are not in. But I'll seriously consider it for the long run, controlled indeed by a __pragma__.

**Comment by AXGKl** [comment]
@JdeH: Strictly personal opinion follows:

Thinking about not "only" __getattr__ but also `@property`, which allows to specify attribute access w/o the need to change all callers.
Mr. "there must be a better way" Hettinger expains it nicely: https://youtu.be/HTLu2DFOdTg?t=2347, so there will be request to have that as well, for good reasons. Also building in __getattr__ later w/o having to dig through the callers and insert __pragmas__ is comparable to later turn a previous public attribute into a property function. The nice thing of that is: I don't need to change the callers. 
In other words: IF I need to change the callers and put the pragma in THEN I could as well turn the .foo into .foo() and I'm done and you save the work and the thing will run faster than turning all dot ops into functions.

You decide, but I think its partly a waste or your precious time to compile different code for the callers, i.e. to change attribute access via dot into `__getattr__` `__setattr__` calls, IF they put the pragma in. Because thats exactly the feature of Transcrypt to allow Pythonic thinking and a part of it is: I can allow direct attribute access and LATER I can modify the result W/O any change on the clients.

All I'm trying to say:  I would wrap a class which has __getattr__, __setattr__, @property in it into this Ecma6 Proxy object, i.e. support it on the callee side only - then w/o any change on the callers.

```
let handler = {
  get(target,name) {
    return `Value for attribute ${name}`
  }
}

let x1 = new Proxy({},handler);
console.log(x1.fubar); 

-> Value for attribute fubar
```

and so in the handler function all can be handled quite straight forward, e.g. call __getattr__  or property functions, or `@foo.setter` 

![screen shot 2016-11-04 at 13 48 52](https://cloud.githubusercontent.com/assets/9989548/20005954/77771c66-a295-11e6-9327-1ceaa837a5a2.png)


The "only" big downside: No IE. Edge can, IE not.  I know, big problem for non closed Environments but time will resolve the problem and pretty much everybody has an alternative browser at hand, especially audience for sites of people how develop in Transcrypt, e.g. in schools or in programming courses....

https://kangax.github.io/compat-table/es6/#Proxy
http://www.ecma-international.org/ecma-262/6.0/#sec-proxy-object-internal-methods-and-internal-slots

**Comment by JdeH** [comment]
A quick reaction only on @property:

What exactly does this add compared to the properties as done in the property testlet at:

http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/supported_constructs.html#properties

I've only skimmed throug this issue, since I  am currently a bit flooded in work, but is there something, apart from minor syntactic convenience that @property can do and the syntax below

`x, y, y2 = property (getX, setX), property (getY, setY), property (getY2, setY2)`

can't. I have the feeling I've missed something very basic here. Or is it indeed just syntax?

**Comment by AXGKl** [comment]
Hi Jacques,

simple answer regarding @property:
I completely forgot that js property descriptions are already in (allthough I was using them a month ago, memory wear out, overloaded my self as well).

I beg a pardon, you already have it all, already.

So, ... thats the way how YOU wanted to handle the superclass change propagation of my other ticket as well, you intended the necessary pragma anyway always on the callee side not at the caller side.
Turning, when the pragma is there, the attributes into underbared "private" ones and provide setter and getter functions...


Reason for me totally on the wrong foot regarding that: I thought all the time you intended to handle this ticket here by a pragma on the **caller** side, turning their  `obj.foo operations into obj.__getattr__('foo')`

Why did I think so? Because there is this one reason where your approach fails (if I'm not again mistaken) and that is handling access to non existing attrs. defineProperty is explicit about the name of the property. But pythons `__getattr__` can do much more, take any name and get the value from exchangable sources.


I suggest the following to save you work:

I'll come up with some sort of patterns, how you workaround currently not supported things in Transcrypt, have a few little tools and need to train them internally anyway.  Stuff like how to get to the mro() of a class from all bases and their bases and so on...  There I'll also explain how your create a Proxy Object for handling this use case, returning values for non existing attributes. 

-> I think this one here can be safely **postponed**. Everybody who wants to allow `__getattr__` for known attributes can declare them already in property functions, and sorry again to have forgotten about their presence. 

And the use case of passing *any* dot access into a function we handle via such a Proxy Object for now, which anybody can do via a normal js pragma and do in the handler function his custom handling.

**Comment by JdeH** [comment]
Will be in the next commit.

**Comment by JdeH** [comment]
Done
