### ISSUE TITLE
Regular expressions, Python API, JS engine

### ISSUE THREAD

**Issue by JdeH** [QQuick/Transcrypt#98]
Many people use regular expressions in their programs, but for me this unfortunately happens to be a very persistent blind spot. Somehow they don't fit into my brain, I can understand them but not remember them, despite many years of using them in quite complicated ways.

In Transcrypt the 'normal' JavaScript regular expressions can of course be used without restriction, as can any part of JS. However it would be nice to have a re (old) or regex (new) module with an API as close as possible to the API CPython provides.

Writing Python-style pattern matching algorithms directly in JavaScript or Transcrypt would be FAR to slow!!!! So under this API, **the re or regex module should use JavaScript's regular expression facilities (which are written in C, just like Python's) as its workhorse as much as possible**. This is a mandatory requirement for any regular expression module suitable for real and heavy use. Also its footprint should be small, suitable for the niche that Transcrypt is aiming at: fast, small JavaScript code. So what's needed is a thin wrapper around JS, also in this case. Pareto's rule should be used as a guideline: Just leave out that 10% functionality that costs you 90 % of the effort and bloats the library in addition.

This is a labor-intensive, difficult job! Such a module would have to be VERY reliable and an extensive autotest (back to back with CPython, as any Transcrypt autotest, see docs) should come with it. It's ok, probably even advisable, to **start out with limited functionality**, assuming that it's clearly documented what's in and what isn't. But what's there should be rock solid!

I am aware that there are at least three Python-based RE modules out there, one for RapydScript (NT), one for RPython and one for Brython. If you use any code written by someone else, please respect licences, include copyright notices etc.! People should be credited for what they create. If you'd rather make a fresh start,  however tiny, that's fine as well.

To minimize logistic and license compatibility problems, the Transcrypt regular expression module should be distibuted using PyPi, rather than be part of the Transcrypt distribution, and have its own GitHub repository. However a link to it can be placed on the Transcrypt site to let developers know it exists.

Having efficient, fast CPython-style regular expressions available in a compact module would be of great value to Transcrypt developers.

**Comment by AXGKl** [comment]
Can just comment, I'm in the same group than you unfortunatelly (user when I have to but not really understander...)
Wanted to add here a good site to compare python and js, feature wise:

http://www.regular-expressions.info/refcharclass.html

In fact they seem to be quite similar in features.

**Comment by JdeH** [comment]
Indeed, that's why I hope that behind a CPython re api there can be an (efficient) JS re implementation.

**Comment by GULPF** [comment]
I've been working a bit on this (https://github.com/GULPF/rescrypt). Most of the regex syntax stuff (named groups/backreferences, conditionals, small stuff like $ behaving differently) is done, but I haven't implemented much of the API. No transcrypt style tests yet, only some provisional browser tests.

It's very early in development, but it might lead somewhere :)

**Comment by JdeH** [comment]
That's quite a job! I've taken a brief look at your code and my impression is you're doing quite a thorough job here. If I saw right, you translate Python regexes to JS regexes, which I think is an efficient way to approach the matter.

So I am very happy you picked this up. Regexes are central to many programs, and having to learn JS regex syntax in addition to Python regex syntax is confusing. So a good Python-style regex module is a very important addition to Transcrypt.

Currently I am preparing a release, think the move from 3.5 to 3.6 justifies that. After that I'll download your code and take a better look.

**Comment by RCL-Carl** [comment]
Ooops - I got scooped. I've been working on an initial attempt as well: 

https://github.com/RCL-Carl/Transcrypt/tree/regexmod

@GULPF - as you mentioned it may make sense to collaborate. My thought process was to use the javascript regex engine explicitly - ie, not attempt to translate the regex from python format to javascript format at all. It would then be up to the user to make intelligent choices about what regex strings to use. I have implemented a fair number of unit tests but no where near comprehensive. 

Along with the idiosyncrasies of the javascript regex format, there are some API differences that I've tried to work around. I think these could be reused targeting your regex translation engine. Without the translating concept, there are some aspects of the python regex api that we will never be able get to with the js regex engine. My implementation is resigned to that fact and tries to work around it.

As to whether translation or using javascript regex format directly is the correct path, I think that a lot of that will come down to a performance vs standard adherence. It looks like to me your are doing the translation in compilation, which for a majority of applications will likely be pretty fast.

**Comment by RCL-Carl** [comment]
One other item I want to mention is that for several of the API methods in re, the "IndexError" exception is thrown which, doesn't seem to be defined (unless I missed it). Are the built-in exceptions defined anywhere or is this an open item ?

**Comment by JdeH** [comment]
@RCL-Carl:

Some built-in exceptions are already defined. I think we should expand them gradually with what's most needed, to keep it all small. The current exceptions at the start of: 

https://github.com/QQuick/Transcrypt/blob/master/transcrypt/modules/org/transcrypt/__standard__.py

@RCL-Carl @GULPF:

Would it indeed be sensible to merge your efforts on the re's? I find it hard to judge that.

**Comment by GULPF** [comment]
If performance is a concern, we could support both re regexes and js regexes with a parameter (or maybe a regex flag?) to `compile` and the other top level functions. The `Regex` and `Match` classes should then be written to support both cases.

The performance for the translation step _should_ not be a concern, though. In almost all cases, compiling a regex only happens a few times in an applications life time.

I think the biggest argument for using the translation step is not the additional features like named groups and conditionals, but the fact that it will be more intuitive for a python programmer. The translation step handles lots of minor differences between re regexes and js regexes, like `\A` and `\Z`being used for start and end of input in re. It's a big gain to not have to keep differences like these in mind when writing regexes for transcrypt.

As for cooperation. @RCL-Carl's API-implementation could be augmented to use the output of my translation step. My API-implementation is not as complete, and @RCL-Carl's code looks great.

**Comment by RCL-Carl** [comment]
> The performance for the translation step should not be a concern, though. In almost all cases, compiling a regex only happens a few times in an applications life time.

Agreed. 

For a quick and dirty test, I've copied your code from the `rescrypt` repo into my local directory to do some testing. Not working yet - but I'm progressing toward an initial integration. 

@JdeH @GULPF  How do you want to integrate the code the `rescrypt` - should it be a submodule referencing the GULPF repo or are you planning to just merge them together ?

**Comment by RCL-Carl** [comment]
@GULPF 

I'm having a trouble integrating your code. I can't seem to get it to run in the autotester. Can you please tell me how you are testing your code so that I can have a base of comparison? 

I've create a new module `trancrypt/modules/re2` that directly copies your code and then setup a separate test in `transcrypt/development/automated_tests/re2` with your autotesters.py and autotesters_re.py. In both chrome and firefox in Ubuntu and OSX, when I run the autotester in the js runtime, it crashes the browser. I'm having a lot difficulty tracking down exactly where the problem lies because the browser and the debugger lock up. I'm pretty sure that it has something to do with the string that is fed to the js regex engine - I've been able to get it to crash feeding it named groups before.  Any suggestions ?  

----------------

On line [translate.py:263](https://github.com/GULPF/rescrypt/blob/master/src/translate.py#L263), you have: 
```
stack[-2:] = [Token('\\' + namedGroups[s1.paras[0]])]
```
This is not valid Python at runtime. This would work in javascript but not Python. `namedGroups` is a dict of str:int key value pairs. This throws a TypeError exception in the Python runtime. I get that this code will never run in CPython but it is my opinion that the code that is written in python, whether it gets compiled or not, should be valid python and not a mixture of valid python and valid javascript. @JdeH Perhaps this is question that should be discussed at a higher level?

The difficulty here is that JS won't throw an exception here and it seems that the static type checker did not catch this as a problem (probably because it is runtime dependent).

**Comment by JdeH** [comment]
@RCL-Carl 

> How do you want to integrate the code the rescrypt - should it be a submodule referencing the GULPF repo or are you planning to just merge them together ?

I would say, just merge them together.

**Comment by RCL-Carl** [comment]
> I would say, just merge them together.

Yup - working on it.

**Comment by JdeH** [comment]
About mixing Python and JavaScript syntax c.q. semantics: Let's keep them separate in Transcrypt, JS being easily recognizable by the \_\_pragma\_\_ ('js', {}, ...) marker. In applications there's some deliberate freedom, e.g.  http://sterlicht.alwaysdata.net/transcrypt.org/docs/html/special_facilities.html#keeping-your-code-lean-pragma-jskeys-and-pragma-nojskeys, to make it possible for dev's using Transcrypt to adhere to docs of a library (no extra quotes in object literals that are often used to set parameters).

**Comment by GULPF** [comment]
The crash might be because I've been using the `-t` flag, instead of pragmas. Not using it will probably lock the code in a infinite loop. Should be changed, either to pragmas or just checking the length of lists instead.

> This is not valid Python at runtime.

I assume it's not valid python because the implicit type conversion, and adding an explicit `str()` call makes it valid? I agree that it's preferable to use valid python, I missed that one since it's allowed in a lot of languages.

**Comment by RCL-Carl** [comment]
> The crash might be because I've been using the -t flag, instead of pragmas. Not using it will probably lock the code in a infinite loop. Should be changed, either to pragmas or just checking the length of lists instead.

OK - great. Adding `__pragma__('tconv')`to the translate file makes your unit tests pass. From the code translation that I've seen, I think that checking the length of the list will have better performance. Some of the checks on lists happen inside the shiftReduce loop and expand to two calls to `__t__`. I'll work on that when I get more of the unit tests integrated. 

> adding an explicit str() call makes it valid?

Agreed - I'm working on another PR and I'll include this fix.

**Comment by RCL-Carl** [comment]
Ok - latest status of the `re` module is that I think most of the core functionality is present except for conditional groups in the python translated regexes. There seems to be a problem with how matches are shown due to how the regex gets expanded to support conditional groups. I believe this can be fixed by modifying the match object only - I don't believe it requires modification to the regex or PyRegExp objects.

@GULPF - you mention in the comments that `n_skips` can help solve this but it would seem that the latest code in `GUPF/rescrypt` does not use the `n_skips` parameter in the PyRegExp object. So can you confirm that at present you haven't commit a solution I can just copy - this would have to be solved on its own, correct?

**Comment by GULPF** [comment]
Correct, I haven't written a solution for it. It should hopefully be easy to solve by checking the JS match object for the first non-undefined match, which will indicate which of the regex splits (e.g which `rgxN` of `rgx1|rgx2|rgx3|rgx4` was used). So it requires the number of capture groups as well as the number of splits (i.e `n__splits`) to be known.

**Comment by GULPF** [comment]
Another thing - references to capture groups in repl strings for `sub` and `subn` is currently not supported. I don't know if it's a good idea to support it, since it would require parsing the repl string which (since it can't be pre-parsed) will impact performance.

A nice workaround might be to also offer a `sub/subn` implementation which uses JavaScripts `String.prototype.replace`, which has support for capture group references and more, but with a different syntax. It would probably be really hard to make it work correctly with regex conditionals, but since regex conditionals are rare anyway it might be fine to just throw an exception when they are used in that context.

**Comment by JdeH** [comment]
According to Pareto's rule, I consider this a complete enough addition to Transcrypt.
So I'll close the issue.
@GULPF and @RCL-Carl: A fine piece of work!

**Comment by JdeH** [comment]
Some points left afterall, so I've reopened it.
Will outcomment small parts of the re autotest, using @JdeH label, to be enable finding and restoring them easily.

**Comment by JdeH** [comment]
Module re now part of shipment test for Py3.5 an Py3.6.
Some parts commented out, all marked with @JdeH.
CI tests gives still errors for Py3.6, so re module commented out there.

Seems like it's largely functioning, but some strange things happen, 
especially when autotesting `checkMatchWithNamedGroups(test)`.
This causes an error at the end of the whole autotest.
Tried quite some things, but no clue whatsoever...

Still I like that what's there (by far the largest part) is now routinely tested.

**Comment by JdeH** [comment]
This seems to have come to a standstill.
I'll close for now.
Feel free to reopen if work continues.

KR
Jacques
